//! `LiftTo` impls: the shape each target's parser builds for a literal.
//!
//! @generated by `bin/gen-lifts` from `quilt/src/lift/mk_lifts.rs.quilt` —
//! do not edit by hand. `bin/check-lifts` regenerates it and fails if it
//! differs, so a lift cannot drift from the grammar it is meant to match.
//!
//! Every shape below was read off a *parsed sample literal*. The generator
//! parses e.g. `py↖"s"↗` with the vendored grammar and lifts
//! with `↑`, which prints the builder calls that rebuild it; the sample's
//! own text is then replaced by the runtime expression. So the tags, the
//! child structure and the layout are the parser's, not a transcription of
//! it. Two hand surveys had to be done before this existed (#176, then
//! `fed278b`); generating it is issue #203.
//!
//! Three families are still deliberately *not* the parser's shape:
//!
//! * WGSL literals parse wrapped in a `const_literal`; these lifts produce
//!   the inner node, which is the tag `conformance/spec/wgsl.toml` pins.
//!   Adopting the wrapper moves a declared claim — the open call in #174.
//! * A negative Python or Nix integer parses as a `unary_operator` /
//!   `unary_expression` over a positive literal; these lift one signed
//!   literal. Same call. Lean's negatives *are* the parser's shape.
//! * A string containing escapes parses with `escape_sequence` children
//!   inside its content, which no runtime reproduces (#174, finding A2).

use super::{
    lean_dquote_escape, mysql_squote_escape, nix_dquote_escape, py_dquote_escape, sh_dquote_escape,
    sql_squote_escape, Bash, Lean, LiftTo, MySql, Nix, Python, Sql, Wgsl, Zsh,
};
use crate::qterm::{leaf, sym, tb, QTerm};
use std::sync::Arc;

/// WGSL `3u` / `3i`. The parser wraps a literal in a
/// `const_literal`; this is the inner node, which is what
/// `conformance/spec/wgsl.toml` pins — see issue #174.
///
/// WGSL has no 64-bit integers, so `u64`/`i64` get no impl
/// below: lifting one is a compile error in the expanded
/// program rather than a silent truncation.
pub fn wgsl_int_term(text: &str) -> Arc<QTerm> {
    leaf("int_literal", text)
}
impl LiftTo<Wgsl> for u8 {
    fn lift_to(&self) -> Arc<QTerm> {
        wgsl_int_term(&format!("{self}u"))
    }
}
impl LiftTo<Wgsl> for u16 {
    fn lift_to(&self) -> Arc<QTerm> {
        wgsl_int_term(&format!("{self}u"))
    }
}
impl LiftTo<Wgsl> for u32 {
    fn lift_to(&self) -> Arc<QTerm> {
        wgsl_int_term(&format!("{self}u"))
    }
}
impl LiftTo<Wgsl> for usize {
    fn lift_to(&self) -> Arc<QTerm> {
        wgsl_int_term(&format!("{self}u"))
    }
}
impl LiftTo<Wgsl> for i8 {
    fn lift_to(&self) -> Arc<QTerm> {
        wgsl_int_term(&format!("{self}i"))
    }
}
impl LiftTo<Wgsl> for i16 {
    fn lift_to(&self) -> Arc<QTerm> {
        wgsl_int_term(&format!("{self}i"))
    }
}
impl LiftTo<Wgsl> for i32 {
    fn lift_to(&self) -> Arc<QTerm> {
        wgsl_int_term(&format!("{self}i"))
    }
}
impl LiftTo<Wgsl> for isize {
    fn lift_to(&self) -> Arc<QTerm> {
        wgsl_int_term(&format!("{self}i"))
    }
}
/// WGSL `1.5f`.
pub fn wgsl_float_term(text: &str) -> Arc<QTerm> {
    leaf("float_literal", text)
}
impl LiftTo<Wgsl> for f32 {
    fn lift_to(&self) -> Arc<QTerm> {
        wgsl_float_term(&format!("{self}f"))
    }
}
/// WGSL `true` / `false`. The keyword is a child token of the
/// `bool_literal`, not its text — a lift that spelled it as
/// text coparsed identically and matched nothing.
pub fn wgsl_bool_term(b: bool) -> Arc<QTerm> {
    if b {
        tb("bool_literal").c(&sym("true")).b()
    } else {
        tb("bool_literal").c(&sym("false")).b()
    }
}
impl LiftTo<Wgsl> for bool {
    fn lift_to(&self) -> Arc<QTerm> {
        wgsl_bool_term(*self)
    }
}
/// Python `3`. Python integers are arbitrary-precision, so
/// every Rust integer width lifts losslessly.
pub fn py_int_term(text: &str) -> Arc<QTerm> {
    leaf("integer", text)
}
impl LiftTo<Python> for u8 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for u16 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for u32 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for u64 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for u128 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for usize {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for i8 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for i16 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for i32 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for i64 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for i128 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
impl LiftTo<Python> for isize {
    fn lift_to(&self) -> Arc<QTerm> {
        py_int_term(&self.to_string())
    }
}
/// Python `1.5`.
pub fn py_float_term(text: &str) -> Arc<QTerm> {
    leaf("float", text)
}
impl LiftTo<Python> for f32 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_float_term(&format!("{self:?}"))
    }
}
impl LiftTo<Python> for f64 {
    fn lift_to(&self) -> Arc<QTerm> {
        py_float_term(&format!("{self:?}"))
    }
}
/// Python `True` / `False` — two different node kinds, not one
/// kind with two spellings.
pub fn py_bool_term(b: bool) -> Arc<QTerm> {
    if b {
        leaf("true", "True")
    } else {
        leaf("false", "False")
    }
}
impl LiftTo<Python> for bool {
    fn lift_to(&self) -> Arc<QTerm> {
        py_bool_term(*self)
    }
}
/// Python `"s"` — a three-child `string`, and for the empty
/// string a two-child one, because the parser emits no
/// `string_content` when there is no content.
///
/// Public because `quilt-python`'s own `qlift` needs exactly
/// this shape: there were two implementations of "lift a string
/// into Python", and they disagreed (#176). Sharing the
/// constructor is what keeps them from drifting apart again —
/// and generating it is what keeps *this* one honest.
pub fn py_string_term(s: &str) -> Arc<QTerm> {
    if s.is_empty() {
        tb("string")
            .c(&leaf("string_start", "\""))
            .c(&leaf("string_end", "\""))
            .b()
    } else {
        tb("string")
            .c(&leaf("string_start", "\""))
            .c(&leaf("string_content", &py_dquote_escape(s)))
            .c(&leaf("string_end", "\""))
            .b()
    }
}
impl LiftTo<Python> for str {
    fn lift_to(&self) -> Arc<QTerm> {
        py_string_term(self)
    }
}
impl LiftTo<Python> for String {
    fn lift_to(&self) -> Arc<QTerm> {
        py_string_term(self)
    }
}
/// The container shape, with the elements as a parameter. Derived from
/// the empty, one- and two-element samples: what surrounds the first
/// element is the opener, what sits between two of them is the
/// separator, and what the empty container still writes is neither.
pub fn py_list_term(items: &[Arc<QTerm>]) -> Arc<QTerm> {
    let mut b = tb("list");
    b.child(&sym("["));
    for (i, x) in items.iter().enumerate() {
        if i > 0 {
            b.child(&sym(","));
            b.write(" ");
        }
        b.child(x);
    }
    b.child(&sym("]"));
    b.b()
}
impl<T: LiftTo<Python>> LiftTo<Python> for [T] {
    fn lift_to(&self) -> Arc<QTerm> {
        py_list_term(&self.iter().map(|x| x.lift_to()).collect::<Vec<_>>())
    }
}
impl<T: LiftTo<Python>> LiftTo<Python> for Vec<T> {
    fn lift_to(&self) -> Arc<QTerm> {
        self.as_slice().lift_to()
    }
}
/// Bash `3` — a bare `number` word.
pub fn bash_number_term(text: &str) -> Arc<QTerm> {
    leaf("number", text)
}
impl LiftTo<Bash> for u8 {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_number_term(&self.to_string())
    }
}
impl LiftTo<Bash> for u16 {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_number_term(&self.to_string())
    }
}
impl LiftTo<Bash> for u32 {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_number_term(&self.to_string())
    }
}
impl LiftTo<Bash> for u64 {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_number_term(&self.to_string())
    }
}
impl LiftTo<Bash> for usize {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_number_term(&self.to_string())
    }
}
impl LiftTo<Bash> for i8 {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_number_term(&self.to_string())
    }
}
impl LiftTo<Bash> for i16 {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_number_term(&self.to_string())
    }
}
impl LiftTo<Bash> for i32 {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_number_term(&self.to_string())
    }
}
impl LiftTo<Bash> for i64 {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_number_term(&self.to_string())
    }
}
impl LiftTo<Bash> for isize {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_number_term(&self.to_string())
    }
}
/// Bash `"s"`. Double-quoted so the value is inert data:
/// everything the shell would interpret inside `"…"` is
/// backslash-escaped first.
pub fn bash_string_term(s: &str) -> Arc<QTerm> {
    if s.is_empty() {
        tb("string").c(&sym("\"")).c(&sym("\"")).b()
    } else {
        tb("string")
            .c(&sym("\""))
            .c(&leaf("string_content", &sh_dquote_escape(s)))
            .c(&sym("\""))
            .b()
    }
}
impl LiftTo<Bash> for str {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_string_term(self)
    }
}
impl LiftTo<Bash> for String {
    fn lift_to(&self) -> Arc<QTerm> {
        bash_string_term(self)
    }
}
/// Zsh `3` — derived from the zsh grammar, not assumed equal to
/// bash's. Eleven constructs the two shells were assumed to
/// share had quietly drifted apart once already (#150).
pub fn zsh_number_term(text: &str) -> Arc<QTerm> {
    leaf("number", text)
}
impl LiftTo<Zsh> for u8 {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_number_term(&self.to_string())
    }
}
impl LiftTo<Zsh> for u16 {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_number_term(&self.to_string())
    }
}
impl LiftTo<Zsh> for u32 {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_number_term(&self.to_string())
    }
}
impl LiftTo<Zsh> for u64 {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_number_term(&self.to_string())
    }
}
impl LiftTo<Zsh> for usize {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_number_term(&self.to_string())
    }
}
impl LiftTo<Zsh> for i8 {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_number_term(&self.to_string())
    }
}
impl LiftTo<Zsh> for i16 {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_number_term(&self.to_string())
    }
}
impl LiftTo<Zsh> for i32 {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_number_term(&self.to_string())
    }
}
impl LiftTo<Zsh> for i64 {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_number_term(&self.to_string())
    }
}
impl LiftTo<Zsh> for isize {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_number_term(&self.to_string())
    }
}
/// Zsh `"s"`.
pub fn zsh_string_term(s: &str) -> Arc<QTerm> {
    if s.is_empty() {
        tb("string").c(&sym("\"")).c(&sym("\"")).b()
    } else {
        tb("string")
            .c(&sym("\""))
            .c(&leaf("string_content", &sh_dquote_escape(s)))
            .c(&sym("\""))
            .b()
    }
}
impl LiftTo<Zsh> for str {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_string_term(self)
    }
}
impl LiftTo<Zsh> for String {
    fn lift_to(&self) -> Arc<QTerm> {
        zsh_string_term(self)
    }
}
/// Nix `3`. Nix integers are 64-bit, matching the shell widths.
pub fn nix_int_term(text: &str) -> Arc<QTerm> {
    leaf("integer_expression", text)
}
impl LiftTo<Nix> for u8 {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_int_term(&self.to_string())
    }
}
impl LiftTo<Nix> for u16 {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_int_term(&self.to_string())
    }
}
impl LiftTo<Nix> for u32 {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_int_term(&self.to_string())
    }
}
impl LiftTo<Nix> for u64 {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_int_term(&self.to_string())
    }
}
impl LiftTo<Nix> for usize {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_int_term(&self.to_string())
    }
}
impl LiftTo<Nix> for i8 {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_int_term(&self.to_string())
    }
}
impl LiftTo<Nix> for i16 {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_int_term(&self.to_string())
    }
}
impl LiftTo<Nix> for i32 {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_int_term(&self.to_string())
    }
}
impl LiftTo<Nix> for i64 {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_int_term(&self.to_string())
    }
}
impl LiftTo<Nix> for isize {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_int_term(&self.to_string())
    }
}
/// Nix `1.5`.
pub fn nix_float_term(text: &str) -> Arc<QTerm> {
    leaf("float_expression", text)
}
impl LiftTo<Nix> for f32 {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_float_term(&format!("{self:?}"))
    }
}
impl LiftTo<Nix> for f64 {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_float_term(&format!("{self:?}"))
    }
}
/// Nix `true` / `false`. They are builtins rather than
/// keywords, so the parser reads them as a variable reference
/// and the name is its own node.
pub fn nix_bool_term(b: bool) -> Arc<QTerm> {
    if b {
        tb("variable_expression").c(&leaf("identifier", "true")).b()
    } else {
        tb("variable_expression")
            .c(&leaf("identifier", "false"))
            .b()
    }
}
impl LiftTo<Nix> for bool {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_bool_term(*self)
    }
}
/// Nix `"s"`. Besides `"` and `\`, the antiquotation opener is
/// escaped, so the value stays data rather than interpolating.
pub fn nix_string_term(s: &str) -> Arc<QTerm> {
    if s.is_empty() {
        tb("string_expression").c(&sym("\"")).c(&sym("\"")).b()
    } else {
        tb("string_expression")
            .c(&sym("\""))
            .c(&leaf("string_fragment", &nix_dquote_escape(s)))
            .c(&sym("\""))
            .b()
    }
}
impl LiftTo<Nix> for str {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_string_term(self)
    }
}
impl LiftTo<Nix> for String {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_string_term(self)
    }
}
/// The container shape, with the elements as a parameter. Derived from
/// the empty, one- and two-element samples: what surrounds the first
/// element is the opener, what sits between two of them is the
/// separator, and what the empty container still writes is neither.
pub fn nix_list_term(items: &[Arc<QTerm>]) -> Arc<QTerm> {
    let mut b = tb("list_expression");
    b.child(&sym("["));
    b.write(" ");
    for (i, x) in items.iter().enumerate() {
        if i > 0 {
            b.write(" ");
        }
        b.child(x);
    }
    if !items.is_empty() {
        b.write(" ");
    }
    b.child(&sym("]"));
    b.b()
}
impl<T: LiftTo<Nix>> LiftTo<Nix> for [T] {
    fn lift_to(&self) -> Arc<QTerm> {
        nix_list_term(&self.iter().map(|x| x.lift_to()).collect::<Vec<_>>())
    }
}
impl<T: LiftTo<Nix>> LiftTo<Nix> for Vec<T> {
    fn lift_to(&self) -> Arc<QTerm> {
        self.as_slice().lift_to()
    }
}
/// Lean `3` and `-3`. `Nat`/`Int` are arbitrary-precision, so
/// every Rust integer width lifts losslessly; `num_lit` itself
/// is unsigned, so the sign is a node rather than a character.
pub fn lean_num_term(negative: bool, text: &str) -> Arc<QTerm> {
    if negative {
        tb("unary_op").c(&sym("-")).c(&leaf("num_lit", text)).b()
    } else {
        leaf("num_lit", text)
    }
}
impl LiftTo<Lean> for u8 {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(false, &self.to_string())
    }
}
impl LiftTo<Lean> for u16 {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(false, &self.to_string())
    }
}
impl LiftTo<Lean> for u32 {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(false, &self.to_string())
    }
}
impl LiftTo<Lean> for u64 {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(false, &self.to_string())
    }
}
impl LiftTo<Lean> for u128 {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(false, &self.to_string())
    }
}
impl LiftTo<Lean> for usize {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(false, &self.to_string())
    }
}
impl LiftTo<Lean> for i8 {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Lean> for i16 {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Lean> for i32 {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Lean> for i64 {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Lean> for i128 {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Lean> for isize {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_num_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
/// Lean `1.5` and `-1.5`.
pub fn lean_float_term(negative: bool, text: &str) -> Arc<QTerm> {
    if negative {
        tb("unary_op")
            .c(&sym("-"))
            .c(&leaf("scientific_lit", text))
            .b()
    } else {
        leaf("scientific_lit", text)
    }
}
impl LiftTo<Lean> for f32 {
    fn lift_to(&self) -> Arc<QTerm> {
        {
            let s = format!("{self:?}");
            match s.strip_prefix('-') {
                Some(mag) => lean_float_term(true, mag),
                None => lean_float_term(false, &s),
            }
        }
    }
}
impl LiftTo<Lean> for f64 {
    fn lift_to(&self) -> Arc<QTerm> {
        {
            let s = format!("{self:?}");
            match s.strip_prefix('-') {
                Some(mag) => lean_float_term(true, mag),
                None => lean_float_term(false, &s),
            }
        }
    }
}
/// Lean `true` / `false`.
pub fn lean_bool_term(b: bool) -> Arc<QTerm> {
    if b {
        tb("true_const").c(&sym("true")).b()
    } else {
        tb("false_const").c(&sym("false")).b()
    }
}
impl LiftTo<Lean> for bool {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_bool_term(*self)
    }
}
/// Lean `"s"`. The quote tokens are children and the body sits
/// between them as raw text, not as a node of its own.
pub fn lean_string_term(s: &str) -> Arc<QTerm> {
    if s.is_empty() {
        tb("str_lit").c(&sym("\"")).c(&sym("\"")).b()
    } else {
        tb("str_lit")
            .c(&sym("\""))
            .w(&lean_dquote_escape(s))
            .c(&sym("\""))
            .b()
    }
}
impl LiftTo<Lean> for str {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_string_term(self)
    }
}
impl LiftTo<Lean> for String {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_string_term(self)
    }
}
/// The container shape, with the elements as a parameter. Derived from
/// the empty, one- and two-element samples: what surrounds the first
/// element is the opener, what sits between two of them is the
/// separator, and what the empty container still writes is neither.
pub fn lean_list_term(items: &[Arc<QTerm>]) -> Arc<QTerm> {
    let mut b = tb("list_lit");
    b.child(&sym("["));
    for (i, x) in items.iter().enumerate() {
        if i > 0 {
            b.child(&sym(","));
            b.write(" ");
        }
        b.child(x);
    }
    b.child(&sym("]"));
    b.b()
}
/// SQL `7` and `-7`. The sign is a child token of the
/// `literal` rather than part of its text, because `_integer`
/// is `seq(optional(choice("-", "+")), …)` — so a lift that
/// spelled `-7` as one leaf built a tree the parser never
/// produces, which `smatch` and `rewrite` can see (#174).
pub fn sql_number_term(negative: bool, text: &str) -> Arc<QTerm> {
    if negative {
        tb("literal").c(&sym("-")).w(text).b()
    } else {
        leaf("literal", text)
    }
}
impl LiftTo<Sql> for u8 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<Sql> for u16 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<Sql> for u32 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<Sql> for u64 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<Sql> for u128 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<Sql> for usize {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<Sql> for i8 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Sql> for i16 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Sql> for i32 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Sql> for i64 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Sql> for i128 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Sql> for isize {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<Sql> for f32 {
    fn lift_to(&self) -> Arc<QTerm> {
        {
            let s = format!("{self:?}");
            match s.strip_prefix('-') {
                Some(mag) => sql_number_term(true, mag),
                None => sql_number_term(false, &s),
            }
        }
    }
}
impl LiftTo<Sql> for f64 {
    fn lift_to(&self) -> Arc<QTerm> {
        {
            let s = format!("{self:?}");
            match s.strip_prefix('-') {
                Some(mag) => sql_number_term(true, mag),
                None => sql_number_term(false, &s),
            }
        }
    }
}
/// SQL `TRUE` / `FALSE`. The keyword is its own node inside the
/// `literal`, unlike the numeric and string forms.
pub fn sql_bool_term(b: bool) -> Arc<QTerm> {
    if b {
        tb("literal").c(&leaf("keyword_true", "TRUE")).b()
    } else {
        tb("literal").c(&leaf("keyword_false", "FALSE")).b()
    }
}
impl LiftTo<Sql> for bool {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_bool_term(*self)
    }
}
/// SQL `'s'` — one `literal` token, quotes included. The empty
/// string needs no separate branch and an escaped quote needs
/// no exemption, because nothing inside the quotes is a node of
/// its own: `'O''Hara'` is still a single token.
pub fn sql_string_term(s: &str) -> Arc<QTerm> {
    leaf("literal", &format!("'{}'", sql_squote_escape(s)))
}
impl LiftTo<Sql> for str {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_string_term(self)
    }
}
impl LiftTo<Sql> for String {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_string_term(self)
    }
}
/// The container shape, with the elements as a parameter. Derived from
/// the empty, one- and two-element samples: what surrounds the first
/// element is the opener, what sits between two of them is the
/// separator, and what the empty container still writes is neither.
pub fn sql_list_term(items: &[Arc<QTerm>]) -> Arc<QTerm> {
    let mut b = tb("list");
    b.child(&sym("("));
    for (i, x) in items.iter().enumerate() {
        if i > 0 {
            b.child(&sym(","));
            b.write(" ");
        }
        b.child(x);
    }
    b.child(&sym(")"));
    b.b()
}
impl<T: LiftTo<Sql>> LiftTo<Sql> for [T] {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_list_term(&self.iter().map(|x| x.lift_to()).collect::<Vec<_>>())
    }
}
impl<T: LiftTo<Sql>> LiftTo<Sql> for Vec<T> {
    fn lift_to(&self) -> Arc<QTerm> {
        self.as_slice().lift_to()
    }
}
impl LiftTo<MySql> for u8 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<MySql> for u16 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<MySql> for u32 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<MySql> for u64 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<MySql> for u128 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<MySql> for usize {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(false, &self.to_string())
    }
}
impl LiftTo<MySql> for i8 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<MySql> for i16 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<MySql> for i32 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<MySql> for i64 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<MySql> for i128 {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<MySql> for isize {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_number_term(*self < 0, &self.unsigned_abs().to_string())
    }
}
impl LiftTo<MySql> for f32 {
    fn lift_to(&self) -> Arc<QTerm> {
        {
            let s = format!("{self:?}");
            match s.strip_prefix('-') {
                Some(mag) => sql_number_term(true, mag),
                None => sql_number_term(false, &s),
            }
        }
    }
}
impl LiftTo<MySql> for f64 {
    fn lift_to(&self) -> Arc<QTerm> {
        {
            let s = format!("{self:?}");
            match s.strip_prefix('-') {
                Some(mag) => sql_number_term(true, mag),
                None => sql_number_term(false, &s),
            }
        }
    }
}
impl LiftTo<MySql> for bool {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_bool_term(*self)
    }
}
/// `MySQL` `'s'`. Identical in shape to `sql_string_term` and
/// different only in the escaper it calls — see
/// `mysql_squote_escape` for why that difference exists.
pub fn mysql_string_term(s: &str) -> Arc<QTerm> {
    leaf("literal", &format!("'{}'", mysql_squote_escape(s)))
}
impl LiftTo<MySql> for str {
    fn lift_to(&self) -> Arc<QTerm> {
        mysql_string_term(self)
    }
}
impl LiftTo<MySql> for String {
    fn lift_to(&self) -> Arc<QTerm> {
        mysql_string_term(self)
    }
}
impl<T: LiftTo<MySql>> LiftTo<MySql> for [T] {
    fn lift_to(&self) -> Arc<QTerm> {
        sql_list_term(&self.iter().map(|x| x.lift_to()).collect::<Vec<_>>())
    }
}
impl<T: LiftTo<MySql>> LiftTo<MySql> for Vec<T> {
    fn lift_to(&self) -> Arc<QTerm> {
        self.as_slice().lift_to()
    }
}
impl<T: LiftTo<Lean>> LiftTo<Lean> for [T] {
    fn lift_to(&self) -> Arc<QTerm> {
        lean_list_term(&self.iter().map(|x| x.lift_to()).collect::<Vec<_>>())
    }
}
impl<T: LiftTo<Lean>> LiftTo<Lean> for Vec<T> {
    fn lift_to(&self) -> Arc<QTerm> {
        self.as_slice().lift_to()
    }
}
