//! Heterogeneous lifting: turn host-language (Rust) values into `QTerm`s of a
//! *target* object language, selected by a zero-sized marker type.
//!
//! The homogeneous `↑` (Rust lifting into Rust) is `QLift`/`qlift()` in
//! `langs::rust::ops`; this module generalizes it to `LiftTo<L>`, indexed by
//! the target language. Inside `wgsl↖ … ↙x.↑↘ … ↗` the `↑` expands to
//! `qlift_to::<Wgsl>()` (see `langs::rust::ops::lift_spelling`), so a Rust
//! `3u32` lifts to the WGSL term `3u` instead of the Rust term `3`.
//!
//! The impls themselves live in [`gen`], generated by `bin/gen-lifts` from
//! sample literals parsed by the vendored grammars — so a lift's tags, child
//! structure and layout are the parser's rather than a transcription of it
//! (issue #203). What stays here by hand is what is not a shape: the markers,
//! the trait, and the per-target escaping rules the generated shapes call.
//!
//! This module is deliberately *not* gated behind the per-language parser
//! features: lift impls are runtime code for expanded programs, which may not
//! enable the target language's parser (e.g. `nanobots-web` builds quilt with
//! only the `rust` feature but splices WGSL terms). The markers index lifting;
//! they don't need the parser.

use crate::qterm::{leaf, sym, tb, QTerm};
use std::sync::Arc;

mod gen;
pub use gen::*;

/**************************************************************/

/// Marker: the Rust object language (the homogeneous case; see `QLift`).
pub struct Rust;

/// Marker: the Python object language.
pub struct Python;

/// Marker: the WGSL object language.
pub struct Wgsl;

/// Marker: the Zsh object language.
pub struct Zsh;

/// Marker: the Bash object language.
pub struct Bash;

/// Marker: the Nix object language.
pub struct Nix;

/// Marker: the Lean 4 object language.
pub struct Lean;

/// Marker: the SQL object language.
pub struct Sql;

/**************************************************************/

/// Lift a value to a `QTerm` of the object language `L` (the `↑` operator).
///
/// Implement this per (Rust type, target language) pair; the impl owns the
/// target language's spelling and tags (e.g. WGSL `u32` literals are
/// `int_literal`s spelled `3u`).
pub trait LiftTo<L> {
    fn lift_to(&self) -> Arc<QTerm>;
}

/// Postfix sugar for [`LiftTo`]: `x.qlift_to::<Wgsl>()`. Blanket-implemented,
/// so it is always in scope via the prelude; the bound is only required at the
/// call site.
pub trait QLiftTo {
    fn qlift_to<L>(&self) -> Arc<QTerm>
    where
        Self: LiftTo<L>,
    {
        LiftTo::<L>::lift_to(self)
    }
}

impl<T: ?Sized> QLiftTo for T {}

/**************************************************************/
// Escaping rules. A generated shape in `gen` holds the literal's *structure*
// and calls one of these for its content, so each is the single place its
// target's quoting is decided. Several are shared further — with a host
// (`langs::shell::ops`) or a binding (`quilt-python`) — which is the point:
// two implementations of one escaping rule is how #150, #176 and #192 each
// started.

/// Escape a string for inclusion in a Python double-quoted literal.
///
/// Public because the `quilt-python` runtime's own `qlift` needs exactly this
/// rule: there were two implementations of "lift a string into Python" — this
/// one, and the binding's, which did no escaping at all, so `qlift('a"b')`
/// produced an unparseable literal and `qlift('a\\b')` silently changed the
/// value (`\\b` is a backspace escape in Python). Sharing the function is what
/// keeps them from drifting apart again. Found by the shared runtime corpus
/// (#159), which runs the same cases against all three published runtimes.
pub fn py_dquote_escape(s: &str) -> String {
    use std::fmt::Write as _;
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' | '\\' => {
                out.push('\\');
                out.push(c);
            }
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => write!(out, "\\x{:02x}", c as u32).unwrap(),
            c => out.push(c),
        }
    }
    out
}

/**************************************************************/
// HTML. There is no `LiftTo<Html>` marker yet (issue #149), so this is a free
// function rather than an impl — but the escaping rule already has two callers,
// and that is what it is here for.

/// Escape `& < > " '` so `s` is inert HTML wherever a hole can sit: as text
/// content, and inside a single- or double-quoted attribute value.
///
/// Public for the same reason as [`py_dquote_escape`]: the `quilt-python` and
/// `quilt-wasm` runtimes each need exactly this rule for their `qlift_html`,
/// and each had grown its own byte-identical copy. Three copies of an escaping
/// table is three chances to fix a hole in one of them — the class of bug the
/// conformance epic (#144) exists to close — so the rule lives here and the
/// bindings call it. Tested directly here; issue #192 is where the two copies
/// having no direct test at all was written up.
///
/// Not idempotent, and deliberately so: escaping `&amp;` yields `&amp;amp;`,
/// because the input is a *value*, not markup. A caller lifting an
/// already-escaped fragment wants the term pass-through both `qlift_html`
/// implementations do, not a second trip through this function.
#[must_use]
pub fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#x27;"),
            _ => out.push(c),
        }
    }
    out
}

/**************************************************************/
// Shells (Zsh, Bash). A Rust string lifts to a double-quoted `string` literal
// so the value is treated as inert data: characters the shell would interpret
// inside `"…"` (`"`, `\`, `$`, `` ` ``) are backslash-escaped. The two shells
// share a grammar lineage, so one escaping rule serves both — their *shapes*
// are still derived separately, since #150 is what assuming otherwise costs.

/// Escape a string for inclusion in a POSIX shell double-quoted literal.
///
/// Shared with the shell *hosts* (`langs::shell::ops`, #151), which reconstruct
/// a quoted fragment as one of these literals: a lifted value and the literal
/// text around it land in the same generated word, so escaping them two
/// different ways is the drift issue #150 is about. It lives here rather than
/// beside the host because `lift.rs` is compiled unconditionally, while
/// `langs::shell` needs the `bash` or `zsh` feature.
pub(crate) fn sh_dquote_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(c, '"' | '\\' | '$' | '`') {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/**************************************************************/
// Nix. Nix is a pure expression language, so every value lifts to its literal
// expression; a string lifts to a double-quoted `string_expression`.

/// Escape a string for inclusion in a Nix double-quoted literal. Besides `"`
/// and `\`, the antiquotation opener `${` is escaped (to `\${`) so the value
/// stays inert data rather than triggering interpolation.
fn nix_dquote_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '"' | '\\' => {
                out.push('\\');
                out.push(c);
            }
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '$' if chars.peek() == Some(&'{') => out.push_str("\\$"),
            c => out.push(c),
        }
    }
    out
}

/**************************************************************/
// Lean. A string lifts to a `str_lit`, whose body is raw text between two quote
// tokens rather than a node of its own.

/// Escape a string for inclusion in a Lean double-quoted literal. Lean's string
/// escapes are the familiar C-like set; note `{` is *not* escaped here — that is
/// only special inside an interpolated `s!"…"`, which a lifted literal is not.
fn lean_dquote_escape(s: &str) -> String {
    use std::fmt::Write as _;
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' | '\\' => {
                out.push('\\');
                out.push(c);
            }
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => write!(out, "\\u{:04x}", c as u32).unwrap(),
            c => out.push(c),
        }
    }
    out
}

/**************************************************************/
// SQL lifts. This is the module's security-relevant corner (#219): a value
// spliced into a quoted query with `↑` becomes a *literal node*, so it is data
// the parser has already accepted as a single token rather than text pasted
// into a statement. Every scalar therefore lifts to a `literal`, which is the
// one tag this grammar gives every constant — integers, decimals, strings and
// the `TRUE`/`FALSE`/`NULL` keywords alike.
//
// SQL's integer literals are unbounded in the standard and the grammar accepts
// a leading sign inside the literal, so every Rust width lifts as one token.

/// Escape a string for inclusion in a SQL single-quoted literal.
///
/// Standard SQL has exactly **one** escape inside `'…'`: a single quote is
/// written twice. Backslash is an ordinary character — this grammar's
/// `_single_quote_string` rule (`/([uU]&|[nN])?'([^']|'')*'/`) says the same —
/// so it is passed through unchanged. Escaping it would be a silent corruption
/// of the value under the standard, not extra safety.
///
/// That makes the result safe against quote-breakout for standard SQL and for
/// `PostgreSQL` with `standard_conforming_strings = on` (the default since 9.1).
/// It is **not** safe for a `MySQL` connection left in the default
/// backslash-escapes mode, where a trailing `\` in the value would escape the
/// closing quote; see issue #233.
fn sql_squote_escape(s: &str) -> String {
    s.replace('\'', "''")
}

impl LiftTo<Sql> for str {
    fn lift_to(&self) -> Arc<QTerm> {
        // `'a''b'` parses as a single `(literal)` with no children — the
        // quotes and the doubled quote are all inside one token.
        leaf("literal", &format!("'{}'", sql_squote_escape(self)))
    }
}

impl LiftTo<Sql> for String {
    fn lift_to(&self) -> Arc<QTerm> {
        LiftTo::<Sql>::lift_to(self.as_str())
    }
}

/// Build the SQL `literal` term for an already-formatted number.
///
/// The sign is *outside* the number token in this grammar — `_integer` is
/// `seq(optional(choice("-", "+")), /…/)` and `_decimal_number` the same — so
/// `-7` parses as `(literal "-" …)`: a `-` child token followed by the
/// magnitude as the literal's own text. `7` is a plain leaf. A lift has to
/// reproduce that *shape*, not merely the text, or `smatch` / `rewrite` see a
/// tree the parser never produces (#174).
fn sql_number_term(s: &str) -> Arc<QTerm> {
    match s.strip_prefix('-') {
        Some(magnitude) => tb("literal").c(&sym("-")).w(magnitude).b(),
        None => leaf("literal", s),
    }
}

macro_rules! sql_lift_int {
    ($($t:ty),* $(,)?) => {$(
        impl LiftTo<Sql> for $t {
            fn lift_to(&self) -> Arc<QTerm> {
                sql_number_term(&self.to_string())
            }
        }
    )*};
}

sql_lift_int!(u8, u16, u32, u64, u128, usize, i8, i16, i32, i64, i128, isize);

macro_rules! sql_lift_float {
    ($($t:ty),* $(,)?) => {$(
        impl LiftTo<Sql> for $t {
            fn lift_to(&self) -> Arc<QTerm> {
                // `{:?}` keeps the decimal point (`1.0`, not `1`), which is
                // what makes the literal parse as `_decimal_number` rather
                // than as an integer.
                sql_number_term(&format!("{self:?}"))
            }
        }
    )*};
}

sql_lift_float!(f32, f64);

impl LiftTo<Sql> for bool {
    fn lift_to(&self) -> Arc<QTerm> {
        // `TRUE` parses as `(literal (keyword_true))` — the keyword is its own
        // node inside the literal, unlike the numeric and string forms.
        tb("literal")
            .c(&if *self {
                leaf("keyword_true", "TRUE")
            } else {
                leaf("keyword_false", "FALSE")
            })
            .b()
    }
}

impl<T: LiftTo<Sql>> LiftTo<Sql> for [T] {
    fn lift_to(&self) -> Arc<QTerm> {
        // A parenthesised comma list — the shape `IN (…)` takes. `(1, 2)`
        // parses as `(list "(" (literal) "," (literal) ")")`: the parentheses
        // and commas are child tokens, not literal text.
        let mut b = tb("list").c(&sym("("));
        for (i, x) in self.iter().enumerate() {
            if i > 0 {
                b = b.c(&sym(",")).w(" ");
            }
            b = b.c(&x.lift_to());
        }
        b.c(&sym(")")).b()
    }
}

impl<T: LiftTo<Sql>> LiftTo<Sql> for Vec<T> {
    fn lift_to(&self) -> Arc<QTerm> {
        self.as_slice().lift_to()
    }
}

/**************************************************************/

#[cfg(test)]
mod tests {
    use super::*;
    use crate::term::STerm;

    #[test]
    fn wgsl_ints() {
        assert_eq!(3u32.qlift_to::<Wgsl>().coparse(), "3u");
        assert_eq!(7usize.qlift_to::<Wgsl>().coparse(), "7u");
        assert_eq!((-2i32).qlift_to::<Wgsl>().coparse(), "-2i");
    }

    #[test]
    fn wgsl_float_bool() {
        assert_eq!(1.5f32.qlift_to::<Wgsl>().coparse(), "1.5f");
        assert_eq!(true.qlift_to::<Wgsl>().coparse(), "true");
    }

    #[test]
    fn wgsl_tags() {
        let QTerm::Tuple { tag, .. } = &*3u32.qlift_to::<Wgsl>() else {
            panic!("expected tuple");
        };
        assert_eq!(&**tag, "int_literal");
    }

    #[test]
    fn sql_scalars() {
        assert_eq!(42u64.qlift_to::<Sql>().coparse(), "42");
        assert_eq!((-7i32).qlift_to::<Sql>().coparse(), "-7");
        assert_eq!(1.0f64.qlift_to::<Sql>().coparse(), "1.0");
        assert_eq!(2.5f32.qlift_to::<Sql>().coparse(), "2.5");
        assert_eq!((-1.5f32).qlift_to::<Sql>().coparse(), "-1.5");
        assert_eq!(true.qlift_to::<Sql>().coparse(), "TRUE");
        assert_eq!(false.qlift_to::<Sql>().coparse(), "FALSE");
    }

    /// The sign is a child token in this grammar, not part of the number, so a
    /// negative lift is a tuple and a positive one is a leaf. Text alone would
    /// not catch a lift that got that backwards; `smatch` / `rewrite` would.
    #[test]
    fn sql_negative_numbers_are_signed_tuples() {
        let QTerm::Tuple { tag, terms, .. } = &*(-7i32).qlift_to::<Sql>() else {
            panic!("expected tuple");
        };
        assert_eq!(&**tag, "literal");
        assert_eq!(terms.len(), 1, "the `-` is the literal's only child");
        assert_eq!(terms[0].coparse(), "-");

        let QTerm::Tuple { terms, .. } = &*7i32.qlift_to::<Sql>() else {
            panic!("expected tuple");
        };
        assert!(terms.is_empty(), "a positive literal is a leaf");
    }

    /// The whole point of the SQL target (#219): a value carrying the delimiter
    /// comes back as one literal with the quote doubled, never as syntax.
    #[test]
    fn sql_strings_cannot_break_out() {
        assert_eq!("hi".qlift_to::<Sql>().coparse(), "'hi'");
        assert_eq!(String::new().qlift_to::<Sql>().coparse(), "''");
        assert_eq!("O'Hara".qlift_to::<Sql>().coparse(), "'O''Hara'");
        assert_eq!(
            "x'; DROP TABLE t; --".qlift_to::<Sql>().coparse(),
            "'x''; DROP TABLE t; --'"
        );
        // Backslash is an ordinary character in a standard SQL literal, so it
        // passes through: doubling it would change the value. See issue #233
        // for the MySQL mode where that is not enough.
        assert_eq!(r"a".qlift_to::<Sql>().coparse(), r"'a'");
    }

    #[test]
    fn sql_lists_are_paren_lists() {
        // The shape an `IN (…)` right-hand side takes.
        assert_eq!(vec![1u32, 2, 3].qlift_to::<Sql>().coparse(), "(1, 2, 3)");
        // `Vec<String>`, not `Vec<&str>`: the element bound is `LiftTo<Sql>`,
        // which `str` satisfies and `&str` does not.
        let names = vec![String::from("a"), String::from("b'c")];
        assert_eq!(names.qlift_to::<Sql>().coparse(), "('a', 'b''c')");
    }

    #[test]
    fn python_scalars() {
        assert_eq!(42u64.qlift_to::<Python>().coparse(), "42");
        assert_eq!((-7i32).qlift_to::<Python>().coparse(), "-7");
        assert_eq!(1.0f64.qlift_to::<Python>().coparse(), "1.0");
        assert_eq!(2.5f32.qlift_to::<Python>().coparse(), "2.5");
        assert_eq!(true.qlift_to::<Python>().coparse(), "True");
        assert_eq!(false.qlift_to::<Python>().coparse(), "False");
    }

    #[test]
    fn python_strings() {
        // Characters Python interprets inside "…" are backslash-escaped.
        let owned = String::from("hi there");
        assert_eq!(owned.qlift_to::<Python>().coparse(), "\"hi there\"");
        assert_eq!(
            "say \"hi\\\"\nbye".qlift_to::<Python>().coparse(),
            "\"say \\\"hi\\\\\\\"\\nbye\""
        );
        assert_eq!("".qlift_to::<Python>().coparse(), "\"\"");
    }

    /// A lifted Python string is the term the Python parser produces for the same
    /// text — not merely something that coparses to it.
    ///
    /// The lift used to be a single flat `leaf("string", "\"…\"")`, a shape
    /// tree-sitter-python never emits, which the text-level assertions above
    /// could not see. Structure matters because `smatch`/`rewrite` compare it.
    ///
    /// Only escape-free strings are checked: with escapes the parser nests
    /// `escape_sequence` children inside `string_content`, which neither this
    /// lift nor `quilt-python`'s `qlift` reproduces (issue #174, finding A2).
    #[cfg(feature = "parse")]
    #[test]
    fn python_string_lift_matches_the_parser() -> crate::prelude::Result<()> {
        use crate::lang::{flat_nodes, Language};
        use crate::langs::python::lang::PythonLanguage;

        let mut py = PythonLanguage::default();
        for s in ["", "hi there", "/usr/bin", "no escapes at all"] {
            let lifted = s.qlift_to::<Python>();
            let text = lifted.coparse();
            let parsed = py.parse_as(None, &flat_nodes(&text))?;
            assert_eq!(
                &*parsed,
                &*lifted,
                "lift of {s:?} is {:?} but the parser reads {text} as {:?}",
                lifted.sexp(),
                parsed.sexp()
            );
        }
        Ok(())
    }

    #[test]
    fn python_lists() {
        let squares: Vec<u64> = (1..=5).map(|n| n * n).collect();
        assert_eq!(squares.qlift_to::<Python>().coparse(), "[1, 4, 9, 16, 25]");
        let nested = vec![vec![1u8], vec![2, 3]];
        assert_eq!(nested.qlift_to::<Python>().coparse(), "[[1], [2, 3]]");
        let empty: Vec<u8> = Vec::new();
        assert_eq!(empty.qlift_to::<Python>().coparse(), "[]");
    }

    #[test]
    fn python_tags() {
        let QTerm::Tuple { tag, .. } = &*3u32.qlift_to::<Python>() else {
            panic!("expected tuple");
        };
        assert_eq!(&**tag, "integer");
        let QTerm::Tuple { tag, .. } = &*vec![1u8].qlift_to::<Python>() else {
            panic!("expected tuple");
        };
        assert_eq!(&**tag, "list");
    }

    #[test]
    fn zsh_strings() {
        // String, &str (via deref to `str`), and a literal all lift to a
        // double-quoted zsh string.
        let owned = String::from("hi there");
        let borrowed: &str = "/var/log";
        assert_eq!(owned.qlift_to::<Zsh>().coparse(), "\"hi there\"");
        assert_eq!(borrowed.qlift_to::<Zsh>().coparse(), "\"/var/log\"");
        assert_eq!("plain".qlift_to::<Zsh>().coparse(), "\"plain\"");
    }

    #[test]
    fn zsh_escaping() {
        // Characters zsh interprets inside "…" are backslash-escaped.
        assert_eq!(
            "say \"$x\" `now`".qlift_to::<Zsh>().coparse(),
            "\"say \\\"\\$x\\\" \\`now\\`\""
        );
    }

    #[test]
    fn zsh_ints() {
        assert_eq!(42u32.qlift_to::<Zsh>().coparse(), "42");
        assert_eq!((-7i32).qlift_to::<Zsh>().coparse(), "-7");
    }

    #[test]
    fn bash_lifts() {
        // Bash shares the shell lift behaviour with zsh.
        let p: &str = "/var/log";
        assert_eq!(p.qlift_to::<Bash>().coparse(), "\"/var/log\"");
        assert_eq!(
            "echo `id`".qlift_to::<Bash>().coparse(),
            "\"echo \\`id\\`\""
        );
        assert_eq!(42u32.qlift_to::<Bash>().coparse(), "42");
    }

    #[test]
    fn nix_scalars() {
        assert_eq!(42u64.qlift_to::<Nix>().coparse(), "42");
        assert_eq!((-7i32).qlift_to::<Nix>().coparse(), "-7");
        assert_eq!(1.0f64.qlift_to::<Nix>().coparse(), "1.0");
        assert_eq!(2.5f32.qlift_to::<Nix>().coparse(), "2.5");
        assert_eq!(true.qlift_to::<Nix>().coparse(), "true");
        assert_eq!(false.qlift_to::<Nix>().coparse(), "false");
    }

    #[test]
    fn nix_strings() {
        let owned = String::from("/etc/nixos");
        assert_eq!(owned.qlift_to::<Nix>().coparse(), "\"/etc/nixos\"");
        // `"`, `\` are escaped, and the antiquotation opener `${` becomes `\${`.
        assert_eq!(
            "say \"hi\" ${x}".qlift_to::<Nix>().coparse(),
            "\"say \\\"hi\\\" \\${x}\""
        );
    }

    #[test]
    fn nix_lists() {
        let squares: Vec<u64> = (1..=3).map(|n| n * n).collect();
        // Nix lists are space-separated, not comma-separated.
        assert_eq!(squares.qlift_to::<Nix>().coparse(), "[ 1 4 9 ]");
        let empty: Vec<u8> = Vec::new();
        assert_eq!(empty.qlift_to::<Nix>().coparse(), "[ ]");
    }

    #[test]
    fn lean_ints() {
        assert_eq!(3u32.qlift_to::<Lean>().coparse(), "3");
        assert_eq!(7usize.qlift_to::<Lean>().coparse(), "7");
        // `num_lit` is unsigned, so a negative lifts as a `unary_op`.
        assert_eq!((-2i32).qlift_to::<Lean>().coparse(), "-2");
        assert_eq!(i32::MIN.qlift_to::<Lean>().coparse(), "-2147483648");
    }

    #[test]
    fn lean_floats_and_bools() {
        assert_eq!(1.5f64.qlift_to::<Lean>().coparse(), "1.5");
        // Keeps the decimal point so it stays a float, not a `Nat`.
        assert_eq!(2.0f32.qlift_to::<Lean>().coparse(), "2.0");
        assert_eq!((-0.5f64).qlift_to::<Lean>().coparse(), "-0.5");
        assert_eq!(true.qlift_to::<Lean>().coparse(), "true");
        assert_eq!(false.qlift_to::<Lean>().coparse(), "false");
    }

    #[test]
    fn lean_strings() {
        let owned = String::from("Nat.succ");
        assert_eq!(owned.qlift_to::<Lean>().coparse(), "\"Nat.succ\"");
        assert_eq!(
            "say \"hi\"\n".qlift_to::<Lean>().coparse(),
            r#""say \"hi\"\n""#
        );
        // A brace is *not* escaped: a lifted literal is a plain string, not an
        // interpolated `s!"…"`.
        assert_eq!("{x}".qlift_to::<Lean>().coparse(), "\"{x}\"");
    }

    #[test]
    fn lean_lists() {
        let squares: Vec<u64> = (1..=3).map(|n| n * n).collect();
        assert_eq!(squares.qlift_to::<Lean>().coparse(), "[1, 4, 9]");
        let empty: Vec<u8> = Vec::new();
        assert_eq!(empty.qlift_to::<Lean>().coparse(), "[]");
    }

    #[test]
    fn lean_tags() {
        let QTerm::Tuple { tag, .. } = &*3u32.qlift_to::<Lean>() else {
            panic!("expected tuple");
        };
        assert_eq!(&**tag, "num_lit");
        let QTerm::Tuple { tag, .. } = &*vec![1u8].qlift_to::<Lean>() else {
            panic!("expected tuple");
        };
        assert_eq!(&**tag, "list_lit");
    }

    /// The whole escape table, one character at a time. The runtime corpus
    /// reaches `escape_html` only through `qlift_html`, and only with a string
    /// containing `& < > "` — so `'` was the one entry in the table with no
    /// coverage anywhere, in either binding (issue #192).
    #[test]
    fn html_escape_table() {
        assert_eq!(escape_html("&"), "&amp;");
        assert_eq!(escape_html("<"), "&lt;");
        assert_eq!(escape_html(">"), "&gt;");
        assert_eq!(escape_html("\""), "&quot;");
        assert_eq!(escape_html("'"), "&#x27;");
    }

    /// A single-quoted attribute value is why `'` is in the table: without it,
    /// `<a title='…'>` breaks out of the attribute the same way `"` does.
    #[test]
    fn html_escape_closes_both_attribute_quotings() {
        assert_eq!(
            escape_html("\" onclick='x'"),
            "&quot; onclick=&#x27;x&#x27;"
        );
        assert_eq!(
            escape_html("<script>alert(1)</script>"),
            "&lt;script&gt;alert(1)&lt;/script&gt;"
        );
    }

    /// `&` is escaped first in the sense that matters: the replacements
    /// themselves introduce `&`, and a rule that rescanned its own output would
    /// turn `<` into `&amp;lt;`. One pass over the *input* is the fix, so this
    /// pins that a mixed string escapes each character exactly once.
    #[test]
    fn html_escape_does_not_rescan_its_own_output() {
        assert_eq!(escape_html("a & b < c"), "a &amp; b &lt; c");
        // Not idempotent, by design: the input is a value, not markup.
        assert_eq!(escape_html("&amp;"), "&amp;amp;");
    }

    /// Everything outside the table is passed through byte-for-byte — the
    /// runtime must not apply Quilt's own glyph escaping to target text.
    #[test]
    fn html_escape_leaves_everything_else_alone() {
        assert_eq!(escape_html(""), "");
        assert_eq!(escape_html("plain text"), "plain text");
        assert_eq!(escape_html("héllo ← ↖ 世界"), "héllo ← ↖ 世界");
        assert_eq!(escape_html("a\nb\t\\c"), "a\nb\t\\c");
    }

    /// The rule *set*, not just the rules that happen to have a line above: a
    /// sixth escape added without a test shows up right here. Came from the
    /// per-binding copies this function replaced, and is the reason the table
    /// is worth having in one place — it can only be stated once.
    #[test]
    fn html_escape_table_is_exactly_five_characters() {
        let changed: String = (0u8..=127)
            .map(char::from)
            .filter(|c| {
                let s = c.to_string();
                escape_html(&s) != s
            })
            .collect();
        assert_eq!(changed, "\"&'<>");
    }

    #[test]
    fn nix_tags() {
        let QTerm::Tuple { tag, .. } = &*3u32.qlift_to::<Nix>() else {
            panic!("expected tuple");
        };
        assert_eq!(&**tag, "integer_expression");
        let QTerm::Tuple { tag, .. } = &*vec![1u8].qlift_to::<Nix>() else {
            panic!("expected tuple");
        };
        assert_eq!(&**tag, "list_expression");
    }
}
