//! `QTree`: the directory analog of [`QTerm`](crate::qterm::QTerm).
//!
//! Where a `QTerm` represents a single generated *file*, a `QTree` represents a
//! whole generated *directory tree*. Its leaves are ordinary `QTerm`s (generated
//! source, serialized later via [`STerm::coparse`](crate::term::STerm::coparse))
//! or raw byte blobs (assets copied verbatim). The host program builds a `QTree`
//! the same way it builds a `QTerm` — with host-language control flow, glyph
//! quotes, lifts, and emits — and a later materialization step (the sinks in
//! `sink.rs`) walks the tree and writes it out.
//!
//! This module is **always compiled** and has **no tree-sitter dependency**, so
//! wasm / no-parse consumers get it too — the same posture as
//! [`lift`](crate::lift). The tree is a plain runtime value: no grammar, no
//! expander, and no new surface syntax are involved (see
//! `docs/design/directory-scaffolding.md` §6.1–6.2, §6.8).
//!
//! ```
//! use quilt::prelude::*;
//!
//! let main_rs = leaf("source_file", "fn main() {}");
//! let t = tree! {
//!     "Cargo.toml" => raw(b"[package]\n".to_vec()),
//!     "src"        => dir! { "main.rs" => file(main_rs) },
//!     ".gitignore" => raw(b"/target\n".to_vec()),
//!     "tests"      => dir! {},   // empty dir kept
//! };
//! assert_eq!(t.len(), 4);
//! ```

use crate::qterm::QTerm;
use miette::{miette, IntoDiagnostic, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::sync::Arc;

/**************************************************************/

/// A single, validated path component (no `/`): non-empty, not `.`/`..`, no
/// `/`, `\`, or NUL, and never absolute.
///
/// Path templating happens *before* construction — the host computes the string
/// (`format!("{module}.rs")`) and hands a finished segment in. The tree never
/// interprets `/` itself; nested directories are nested [`QTree`]s. The
/// convenience builders ([`QTree::emit`], [`tree!`]) split a `"src/main.rs"`
/// string into segments at insert time, validating each component.
///
/// Serializes as a plain string; **deserialization re-validates** through
/// [`Segment::new`], so a tree read off the wire (`quilt scaffold`'s
/// [`emit_tree`]) can never smuggle in a `/`, `..`, or NUL segment.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct Segment(String);

impl TryFrom<String> for Segment {
    type Error = String;
    fn try_from(s: String) -> std::result::Result<Self, String> {
        Self::new(s).map_err(|e| e.to_string())
    }
}

impl From<Segment> for String {
    fn from(seg: Segment) -> String {
        seg.0
    }
}

impl Segment {
    /// Validate `s` as a single path component. See the type docs for the rules.
    pub fn new(s: impl Into<String>) -> Result<Self> {
        let s = s.into();
        if s.is_empty() {
            return Err(miette!("path segment must not be empty"));
        }
        if s == "." || s == ".." {
            return Err(miette!("path segment must not be {s:?}"));
        }
        if s.contains('/') {
            return Err(miette!("path segment must not contain '/': {s:?}"));
        }
        // Reject the Windows separator too: defense-in-depth so a segment can
        // never be read as a path on any platform.
        if s.contains('\\') {
            return Err(miette!("path segment must not contain '\\': {s:?}"));
        }
        if s.contains('\0') {
            return Err(miette!("path segment must not contain NUL: {s:?}"));
        }
        Ok(Self(s))
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for Segment {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Split a `/`-joined path into validated [`Segment`]s. Empty components (from a
/// leading, trailing, or doubled `/`) are an error, as are any segments that
/// fail [`Segment::new`].
fn split_segments(path: &str) -> Result<Vec<Segment>> {
    if path.is_empty() {
        return Err(miette!("empty path"));
    }
    path.split('/').map(Segment::new).collect()
}

/**************************************************************/

/// Whether to stamp the `DO NOT EDIT. GENERATED BY …` marker on a leaf, and how
/// the comment is introduced. The actual stamping happens at write time (the
/// write-policy layer, issue #93); the tree just records the intent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum HeaderPolicy {
    /// Stamp the marker as a line comment introduced by this leader
    /// (e.g. `"//"` for Rust/C-likes, `"#"` for shell/Python/TOML).
    Stamp(String),
    /// Do not stamp a header (the default for raw assets the user owns).
    Skip,
}

/// Per-leaf metadata: unix permission bits and the header-stamp policy.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FileMeta {
    /// Unix permission bits (e.g. `0o755`). `None` leaves the sink's default.
    pub mode: Option<u32>,
    /// Whether the write layer stamps the DO-NOT-EDIT marker on this leaf.
    pub header: HeaderPolicy,
}

impl FileMeta {
    /// Metadata for a generated source file: header stamped (`//` leader).
    #[must_use]
    pub fn source() -> Self {
        Self {
            mode: None,
            header: HeaderPolicy::Stamp("//".to_string()),
        }
    }

    /// Metadata for a verbatim asset: no header.
    #[must_use]
    pub fn asset() -> Self {
        Self {
            mode: None,
            header: HeaderPolicy::Skip,
        }
    }
}

impl Default for FileMeta {
    fn default() -> Self {
        Self::asset()
    }
}

/**************************************************************/

/// A node in a [`QTree`]: a subdirectory, a generated file, a raw blob, or a
/// symlink.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Node {
    /// A subdirectory (possibly empty — empty dirs are kept).
    Dir(QTree),
    /// A generated source file, serialized later via `QTerm::coparse()`.
    File { content: Arc<QTerm>, meta: FileMeta },
    /// Verbatim bytes — assets, `LICENSE`, images, lockfiles.
    Raw { bytes: Vec<u8>, meta: FileMeta },
    /// A symlink whose target is a relative path *within* the tree (the sink
    /// rejects targets that escape — see issue #92).
    Link { target: PathBuf },
}

impl Node {
    /// Set unix permission bits on a `File`/`Raw` leaf. No-op for dirs/links.
    #[must_use]
    pub fn mode(mut self, mode: u32) -> Self {
        if let Self::File { meta, .. } | Self::Raw { meta, .. } = &mut self {
            meta.mode = Some(mode);
        }
        self
    }

    /// Override the header policy on a `File`/`Raw` leaf. No-op for dirs/links.
    #[must_use]
    pub fn header(mut self, policy: HeaderPolicy) -> Self {
        if let Self::File { meta, .. } | Self::Raw { meta, .. } = &mut self {
            meta.header = policy;
        }
        self
    }

    /// Convenience: stamp no header on this leaf.
    #[must_use]
    pub fn no_header(self) -> Self {
        self.header(HeaderPolicy::Skip)
    }
}

/// A generated source-file leaf (header stamped by default). Accepts a `QTerm`
/// or `Arc<QTerm>`.
pub fn file(content: impl Into<Arc<QTerm>>) -> Node {
    Node::File {
        content: content.into(),
        meta: FileMeta::source(),
    }
}

/// A verbatim byte blob leaf (no header). Accepts anything `Into<Vec<u8>>`
/// (`&[u8]`, `Vec<u8>`, `String`, …).
pub fn raw(bytes: impl Into<Vec<u8>>) -> Node {
    Node::Raw {
        bytes: bytes.into(),
        meta: FileMeta::asset(),
    }
}

/// A symlink leaf pointing at a relative path within the tree.
pub fn link(target: impl Into<PathBuf>) -> Node {
    Node::Link {
        target: target.into(),
    }
}

/**************************************************************/

/// A directory tree whose leaves are [`Node`]s. Children are kept in insertion
/// order (a `Vec`, not a map) so output and manifests are deterministic; sort
/// only when a canonical form is wanted.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct QTree {
    entries: Vec<(Segment, Node)>,
}

impl QTree {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Number of direct children.
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// The direct children, in insertion order.
    #[must_use]
    pub fn entries(&self) -> &[(Segment, Node)] {
        &self.entries
    }

    /// Look up a direct child by segment.
    #[must_use]
    pub fn get(&self, seg: &Segment) -> Option<&Node> {
        self.entries.iter().find(|(s, _)| s == seg).map(|(_, n)| n)
    }

    /// Insert (or replace) a leaf at `path`, creating intermediate directories.
    ///
    /// `path` is split on `/` into validated [`Segment`]s. Intermediate
    /// components are created as (or reused from) directories; it is an error if
    /// an intermediate component already exists as a non-directory. The final
    /// component is set, **replacing** any existing entry there (right wins) —
    /// use [`QTree::overlay`]/[`QTree::merge`] for structural composition.
    ///
    /// This is the directory analog of `←` (emit a file per loop iteration).
    pub fn emit(&mut self, path: impl AsRef<str>, node: Node) -> Result<()> {
        let segs = split_segments(path.as_ref())?;
        self.emit_segs(&segs, node)
    }

    fn emit_segs(&mut self, segs: &[Segment], node: Node) -> Result<()> {
        match segs {
            [] => Err(miette!("empty path")),
            [last] => {
                self.set(last.clone(), node);
                Ok(())
            }
            [head, rest @ ..] => self.descend_dir(head)?.emit_segs(rest, node),
        }
    }

    /// Get a `&mut` to the child directory at `seg`, creating it if absent.
    /// Errors if `seg` exists as a non-directory.
    fn descend_dir(&mut self, seg: &Segment) -> Result<&mut Self> {
        let idx = if let Some(i) = self.entries.iter().position(|(s, _)| s == seg) {
            i
        } else {
            self.entries.push((seg.clone(), Node::Dir(Self::new())));
            self.entries.len() - 1
        };
        match &mut self.entries[idx].1 {
            Node::Dir(t) => Ok(t),
            _ => Err(miette!(
                "path component {:?} is a file, not a directory",
                seg.as_str()
            )),
        }
    }

    /// Set a direct child, replacing any existing entry at the same segment but
    /// preserving its position; otherwise append.
    fn set(&mut self, seg: Segment, node: Node) {
        if let Some(i) = self.entries.iter().position(|(s, _)| *s == seg) {
            self.entries[i].1 = node;
        } else {
            self.entries.push((seg, node));
        }
    }

    /// Overlay `other` onto `self`: for each entry in `other`, **right wins**.
    /// Two directories at the same segment are overlaid recursively; any other
    /// collision replaces the left node with the right one.
    #[must_use]
    pub fn overlay(mut self, other: Self) -> Self {
        for (seg, node) in other.entries {
            if let Some(i) = self.entries.iter().position(|(s, _)| *s == seg) {
                if let (Node::Dir(existing), Node::Dir(new)) = (&mut self.entries[i].1, &node) {
                    let merged = std::mem::take(existing).overlay(new.clone());
                    self.entries[i].1 = Node::Dir(merged);
                } else {
                    self.entries[i].1 = node;
                }
            } else {
                self.entries.push((seg, node));
            }
        }
        self
    }

    /// Merge `other` into `self`, **erroring on any collision** except two
    /// directories at the same segment (which merge recursively).
    pub fn merge(mut self, other: Self) -> Result<Self> {
        for (seg, node) in other.entries {
            if let Some(i) = self.entries.iter().position(|(s, _)| *s == seg) {
                let placeholder = Node::Dir(Self::new());
                let existing = std::mem::replace(&mut self.entries[i].1, placeholder);
                let merged = match (existing, node) {
                    (Node::Dir(a), Node::Dir(b)) => Node::Dir(a.merge(b)?),
                    _ => return Err(miette!("merge collision at {:?}", seg.as_str())),
                };
                self.entries[i].1 = merged;
            } else {
                self.entries.push((seg, node));
            }
        }
        Ok(self)
    }

    /// Place `sub` under `prefix` (a `/`-joined path) and overlay it onto
    /// `self`. `QTree::new().graft("packages/hello", sub)` yields
    /// `packages/hello/<sub…>`.
    pub fn graft(self, prefix: impl AsRef<str>, sub: Self) -> Result<Self> {
        let segs = split_segments(prefix.as_ref())?;
        let mut nested = sub;
        for seg in segs.into_iter().rev() {
            let mut t = Self::new();
            t.entries.push((seg, Node::Dir(nested)));
            nested = t;
        }
        Ok(self.overlay(nested))
    }

    /// Recursively drop empty subdirectories (after pruning their children).
    /// Leaves and non-empty directories are kept.
    #[must_use]
    pub fn prune_empty(mut self) -> Self {
        self.entries = self
            .entries
            .into_iter()
            .filter_map(|(seg, node)| match node {
                Node::Dir(t) => {
                    let t = t.prune_empty();
                    if t.is_empty() {
                        None
                    } else {
                        Some((seg, Node::Dir(t)))
                    }
                }
                other => Some((seg, other)),
            })
            .collect();
        self
    }

    /// Transform every leaf (non-directory node), passing its relative path.
    /// Directories are recursed into but not themselves passed to `f`.
    #[must_use]
    pub fn map(mut self, mut f: impl FnMut(&Path, Node) -> Node) -> Self {
        self.map_at(&mut PathBuf::new(), &mut f);
        self
    }

    fn map_at(&mut self, base: &mut PathBuf, f: &mut impl FnMut(&Path, Node) -> Node) {
        for (seg, node) in &mut self.entries {
            base.push(seg.as_str());
            if let Node::Dir(t) = node {
                t.map_at(base, f);
            } else {
                let taken = std::mem::replace(node, Node::Dir(Self::new()));
                *node = f(base, taken);
            }
            base.pop();
        }
    }

    /// Keep only the leaves for which `pred` returns true (by relative path).
    /// Directories are recursed into and retained (use [`QTree::prune_empty`] to
    /// drop ones left empty).
    #[must_use]
    pub fn filter(self, mut pred: impl FnMut(&Path, &Node) -> bool) -> Self {
        let mut base = PathBuf::new();
        self.filter_at(&mut base, &mut pred)
    }

    /// A human-readable listing of every path in the tree, in walk order, one
    /// per line and tagged with its node kind. Used by [`emit_tree`] when a
    /// scaffold program runs standalone (no `quilt scaffold` driving it), so
    /// `quilt run prog.tree.rs.quilt` still shows what *would* be built.
    #[must_use]
    pub fn listing(&self) -> String {
        let mut out = String::new();
        self.listing_at(&mut PathBuf::new(), &mut out);
        out
    }

    fn listing_at(&self, base: &mut PathBuf, out: &mut String) {
        use std::fmt::Write as _;
        for (seg, node) in &self.entries {
            base.push(seg.as_str());
            let p = base.to_string_lossy();
            match node {
                Node::Dir(t) => {
                    let _ = writeln!(out, "{p}/");
                    t.listing_at(base, out);
                }
                Node::File { .. } => {
                    let _ = writeln!(out, "{p} (file)");
                }
                Node::Raw { bytes, .. } => {
                    let _ = writeln!(out, "{p} (raw, {} bytes)", bytes.len());
                }
                Node::Link { target } => {
                    let _ = writeln!(out, "{p} -> {}", target.display());
                }
            }
            base.pop();
        }
    }

    fn filter_at(self, base: &mut PathBuf, pred: &mut impl FnMut(&Path, &Node) -> bool) -> Self {
        let entries = self
            .entries
            .into_iter()
            .filter_map(|(seg, node)| {
                base.push(seg.as_str());
                let kept = match node {
                    Node::Dir(t) => Some((seg, Node::Dir(t.filter_at(base, pred)))),
                    leaf if pred(base, &leaf) => Some((seg, leaf)),
                    _ => None,
                };
                base.pop();
                kept
            })
            .collect();
        Self { entries }
    }
}

/**************************************************************/
// `quilt scaffold` side channel (issue #95): a ground-first host program builds
// a `QTree` and `emit_tree`s it; the CLI runs the program and materializes the
// result. The wire format is postcard (the same one the expand cache uses); the
// tree is handed over via a sidecar file so it never collides with the program's
// own stdout/stderr.

/// Environment variable naming the sidecar file `quilt scaffold` reads the
/// emitted [`QTree`] back from. The CLI sets it to a temp path before running
/// the program; [`emit_tree`] writes the postcard-serialized tree there.
pub const TREE_OUT_ENV: &str = "QUILT_TREE_OUT";

/// Prefix for the per-parameter environment variables `quilt scaffold` exports
/// from its `--set name=value` / `--values` arguments, read back by
/// [`scaffold_param`]. A parameter `name` is passed as `QUILT_PARAM_<name>`.
pub const PARAM_ENV_PREFIX: &str = "QUILT_PARAM_";

/// Emit a [`QTree`] for `quilt scaffold` to materialize (issue #95). When the
/// scaffold CLI is driving the program it sets [`TREE_OUT_ENV`] to a sidecar
/// file, and this writes the postcard-serialized tree there. Run standalone (no
/// `quilt scaffold`), it prints a human-readable [`listing`](QTree::listing)
/// instead, so `quilt run prog.tree.rs.quilt` still shows what would be built.
pub fn emit_tree(tree: &QTree) -> Result<()> {
    if let Some(path) = std::env::var_os(TREE_OUT_ENV) {
        let bytes = postcard::to_stdvec(tree).into_diagnostic()?;
        std::fs::write(path, bytes).into_diagnostic()
    } else {
        // Standalone run: show what would be built instead of writing it.
        print!("{}", tree.listing());
        Ok(())
    }
}

/// Read a scaffold parameter passed by `quilt scaffold --set <name>=<value>`
/// (or `--values`). The CLI exposes each as `QUILT_PARAM_<name>` (see
/// [`PARAM_ENV_PREFIX`]); a scaffold program reads them to vary the tree it
/// builds. Returns `None` when the parameter was not supplied.
#[must_use]
pub fn scaffold_param(name: &str) -> Option<String> {
    std::env::var(format!("{PARAM_ENV_PREFIX}{name}")).ok()
}

/**************************************************************/

/// Build a [`QTree`] from `"segment-path" => Node` entries. Keys may contain
/// `/` (split into nested directories at build time); values are [`Node`]s
/// (`file(..)`, `raw(..)`, or a nested [`dir!`]). Later keys win on collision.
///
/// ```
/// use quilt::prelude::*;
/// let t = tree! {
///     "Cargo.toml" => raw(b"[package]\n".to_vec()),
///     "src"        => dir! { "main.rs" => raw(b"fn main(){}".to_vec()) },
/// };
/// assert_eq!(t.len(), 2);
/// ```
#[macro_export]
macro_rules! tree {
    ($($key:expr => $val:expr),* $(,)?) => {{
        let mut __t = $crate::tree::QTree::new();
        $( __t.emit($key, $val).expect("invalid tree path in tree!{}"); )*
        __t
    }};
}

/// Build a directory [`Node`] from `"segment" => Node` entries (the same syntax
/// as [`tree!`]). `dir! {}` is an empty directory.
#[macro_export]
macro_rules! dir {
    ($($key:expr => $val:expr),* $(,)?) => {
        $crate::tree::Node::Dir($crate::tree! { $($key => $val),* })
    };
}

/**************************************************************/

#[cfg(test)]
mod tests {
    use super::*;
    use crate::qterm::leaf;

    fn src() -> Arc<QTerm> {
        leaf("source_file", "fn main() {}")
    }

    #[test]
    fn segment_validation() {
        assert!(Segment::new("main.rs").is_ok());
        assert!(Segment::new("a.b.c").is_ok());
        assert!(Segment::new(".github").is_ok()); // dotfiles are fine
        assert!(Segment::new("").is_err());
        assert!(Segment::new(".").is_err());
        assert!(Segment::new("..").is_err());
        assert!(Segment::new("a/b").is_err());
        assert!(Segment::new("/abs").is_err());
        assert!(Segment::new("a\\b").is_err());
        assert!(Segment::new("a\0b").is_err());
    }

    #[test]
    fn emit_nested_creates_dirs() {
        let mut t = QTree::new();
        t.emit("src/main.rs", file(src())).unwrap();
        t.emit("src/lib.rs", file(src())).unwrap();
        // One "src" dir reused, holding two files.
        assert_eq!(t.len(), 1);
        let Some(Node::Dir(srcdir)) = t.get(&Segment::new("src").unwrap()) else {
            panic!("expected src dir");
        };
        assert_eq!(srcdir.len(), 2);
    }

    #[test]
    fn emit_rejects_bad_path_and_type_conflict() {
        let mut t = QTree::new();
        assert!(t.emit("a/../b", file(src())).is_err());
        assert!(t.emit("", file(src())).is_err());
        // "a" is a file; descending through it must fail.
        t.emit("a", raw(b"x".to_vec())).unwrap();
        assert!(t.emit("a/b", file(src())).is_err());
    }

    #[test]
    fn emit_last_wins() {
        let mut t = QTree::new();
        t.emit("f", raw(b"first".to_vec())).unwrap();
        t.emit("f", raw(b"second".to_vec())).unwrap();
        assert_eq!(t.len(), 1);
        assert_eq!(
            t.get(&Segment::new("f").unwrap()),
            Some(&raw(b"second".to_vec()))
        );
    }

    #[test]
    fn empty_dir_is_kept() {
        let t = tree! { "tests" => dir! {} };
        assert_eq!(t.len(), 1);
    }

    #[test]
    fn overlay_right_wins_and_merges_dirs() {
        let a = tree! {
            "keep.txt" => raw(b"a".to_vec()),
            "src" => dir! { "main.rs" => raw(b"a-main".to_vec()) },
            "shared.txt" => raw(b"a".to_vec()),
        };
        let b = tree! {
            "src" => dir! { "lib.rs" => raw(b"b-lib".to_vec()) },
            "shared.txt" => raw(b"b".to_vec()),
        };
        let t = a.overlay(b);
        // keep.txt survives; shared.txt overwritten; src dirs merged.
        assert_eq!(t.len(), 3);
        assert_eq!(
            t.get(&Segment::new("shared.txt").unwrap()),
            Some(&raw(b"b".to_vec()))
        );
        let Some(Node::Dir(srcdir)) = t.get(&Segment::new("src").unwrap()) else {
            panic!("src dir");
        };
        assert_eq!(srcdir.len(), 2); // main.rs + lib.rs
    }

    #[test]
    fn merge_errors_on_leaf_collision_but_merges_dirs() {
        let a = tree! { "src" => dir! { "a.rs" => raw(b"a".to_vec()) }, "x" => raw(b"1".to_vec()) };
        let b = tree! { "src" => dir! { "b.rs" => raw(b"b".to_vec()) } };
        let merged = a.clone().merge(b).unwrap();
        let Some(Node::Dir(srcdir)) = merged.get(&Segment::new("src").unwrap()) else {
            panic!("src dir");
        };
        assert_eq!(srcdir.len(), 2);

        let collide = tree! { "x" => raw(b"2".to_vec()) };
        assert!(a.merge(collide).is_err());
    }

    #[test]
    fn graft_prefixes() {
        let sub = tree! { "main.rs" => raw(b"m".to_vec()) };
        let t = QTree::new().graft("packages/hello", sub).unwrap();
        let Some(Node::Dir(pkgs)) = t.get(&Segment::new("packages").unwrap()) else {
            panic!("packages");
        };
        let Some(Node::Dir(hello)) = pkgs.get(&Segment::new("hello").unwrap()) else {
            panic!("hello");
        };
        assert_eq!(hello.len(), 1);
    }

    #[test]
    fn prune_empty_drops_empty_dirs_recursively() {
        let t = tree! {
            "keep" => dir! { "f" => raw(b"x".to_vec()) },
            "empty" => dir! { "alsoempty" => dir! {} },
        };
        let t = t.prune_empty();
        assert_eq!(t.len(), 1);
        assert!(t.get(&Segment::new("empty").unwrap()).is_none());
    }

    #[test]
    fn map_and_filter_see_relative_paths() {
        let t = tree! {
            "a.txt" => raw(b"a".to_vec()),
            "src" => dir! { "b.rs" => raw(b"b".to_vec()), "c.txt" => raw(b"c".to_vec()) },
        };
        // filter: keep only *.rs leaves.
        let only_rs = t
            .clone()
            .filter(|p, _| p.extension().and_then(|e| e.to_str()) == Some("rs"));
        let pruned = only_rs.prune_empty();
        assert_eq!(pruned.len(), 1); // just "src"
        let Some(Node::Dir(srcdir)) = pruned.get(&Segment::new("src").unwrap()) else {
            panic!("src");
        };
        assert_eq!(srcdir.len(), 1); // just b.rs

        // map: rewrite every leaf's bytes to its path string.
        let mapped = t.map(|p, _| raw(p.to_string_lossy().into_owned().into_bytes()));
        assert_eq!(
            mapped.get(&Segment::new("a.txt").unwrap()),
            Some(&raw(b"a.txt".to_vec()))
        );
        let Some(Node::Dir(srcdir)) = mapped.get(&Segment::new("src").unwrap()) else {
            panic!("src");
        };
        assert_eq!(
            srcdir.get(&Segment::new("b.rs").unwrap()),
            Some(&raw(PathBuf::from("src/b.rs")
                .to_string_lossy()
                .into_owned()
                .into_bytes()))
        );
    }

    #[test]
    fn postcard_round_trip_preserves_tree() {
        // The `quilt scaffold` wire format (issue #95): a tree with every node
        // kind survives a postcard round trip unchanged.
        let t = tree! {
            "Cargo.toml" => raw(b"[package]\n".to_vec()),
            "run.sh" => raw(b"#!/bin/sh\n".to_vec()).mode(0o755),
            "src" => dir! { "main.rs" => file(src()) },
            "empty" => dir! {},
        };
        let bytes = postcard::to_stdvec(&t).unwrap();
        let back: QTree = postcard::from_bytes(&bytes).unwrap();
        assert_eq!(t, back);
    }

    #[test]
    fn deserialize_rejects_bad_segment() {
        // A hand-rolled wire tree with an illegal segment must fail validation
        // on the way back in (Segment's `try_from`), not slip through.
        let good = tree! { "ok.txt" => raw(b"x".to_vec()) };
        let bytes = postcard::to_stdvec(&good).unwrap();
        // Sanity: the good one decodes.
        assert!(postcard::from_bytes::<QTree>(&bytes).is_ok());
        // A segment carrying a path separator is rejected by `Segment::try_from`.
        assert!(Segment::try_from("a/b".to_string()).is_err());
        assert!(Segment::try_from("..".to_string()).is_err());
    }

    #[test]
    fn listing_reports_every_path_and_kind() {
        let t = tree! {
            "a.txt" => raw(b"hi".to_vec()),
            "src" => dir! { "main.rs" => file(src()) },
        };
        let listing = t.listing();
        assert!(listing.contains("a.txt (raw, 2 bytes)"), "got: {listing}");
        assert!(listing.contains("src/"), "got: {listing}");
        assert!(listing.contains("src/main.rs (file)"), "got: {listing}");
    }

    #[test]
    fn node_meta_builders() {
        let n = file(src()).mode(0o755);
        let Node::File { meta, .. } = &n else {
            panic!("file");
        };
        assert_eq!(meta.mode, Some(0o755));
        assert!(matches!(meta.header, HeaderPolicy::Stamp(_)));

        let r = raw(b"x".to_vec()).header(HeaderPolicy::Stamp("#".to_string()));
        let Node::Raw { meta, .. } = &r else {
            panic!("raw");
        };
        assert_eq!(meta.header, HeaderPolicy::Stamp("#".to_string()));

        // mode/header are no-ops on dirs.
        let d = dir! {}.mode(0o755);
        assert!(matches!(d, Node::Dir(_)));
    }
}
