//! Quilt's conformance harness (issue #144).
//!
//! One capability matrix, declared in `conformance/spec/*.toml`, verified
//! against the real implementations, and rendered into the two artifacts the
//! rest of the project consumes:
//!
//! * `conformance/support-matrix.json` — read by the website to build its
//!   language support table, so the table cannot claim capability we do not
//!   test;
//! * `docs/wiki/support-matrix.md` — the same data as a wiki page.
//!
//! Both are generated by `bin/gen-matrix` and gated by `bin/check-matrix`,
//! which regenerates them and fails on drift — the same pattern as
//! `bin/check-bootstrap` and `bin/check-grammars`.

pub mod battery;
pub mod cross;

/// Structural `QTerm` rendering now lives in the `quilt` crate, where the
/// expander's own snapshot tests need it too (#157).
pub use quilt::qsnap;

pub mod matrix;
pub mod registry;
pub mod runtime;
pub mod spec;

use matrix::Matrix;
use miette::Result;
use std::path::{Path, PathBuf};

/// Repo root, derived from this crate's manifest directory.
pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crate dir has a parent")
        .to_path_buf()
}

pub fn spec_dir() -> PathBuf {
    repo_root().join("conformance/spec")
}

pub fn matrix_json_path() -> PathBuf {
    repo_root().join("conformance/support-matrix.json")
}

pub fn matrix_md_path() -> PathBuf {
    repo_root().join("docs/wiki/support-matrix.md")
}

/// Load every spec, run the battery over all of them, and return the matrix
/// alongside whatever failed.
///
/// The whole run happens in one process so each language's parser is built
/// exactly once; callers that only need one language should use
/// [`battery::run_language`] directly.
pub fn run_all() -> Result<(Matrix, Vec<battery::Failure>)> {
    let specs = spec::Spec::load_all(&spec_dir())?;
    let mut rows = Vec::with_capacity(specs.len());
    let mut failures = Vec::new();
    for spec in &specs {
        let outcome = battery::run_language(spec)?;
        rows.push(outcome.row);
        failures.extend(outcome.failures);
    }
    Ok((Matrix::new(rows), failures))
}
