// The Node runtime for expanded `.ts.quilt` programs — what `quilt run
// foo.ts.quilt` binds the bare `quilt` specifier to (issue #153).
//
// It is the CLI twin of `examples/web/quilt-rt.js`: both re-export the
// quilt-wasm builder and add the one operator the wasm runtime cannot provide
// itself, `↓` (reduce). Reduce must *re-expand* — a generated stage's coparse()
// is still Quilt source — and the expander is not in the runtime crate. In the
// browser that means calling an in-page WASI expander; here it means shelling
// out to the `quilt` binary, exactly as quilt-python's `expand()` does.
//
// Two things differ from the browser shim, both because Node has more to work
// with:
//
//   * reduce is **block-aware**. `node:vm` hands back a script's completion
//     value, so a stage that ends in a trailing expression after some
//     statements reduces to that expression — the semantics quilt-python
//     documents and the browser's `new Function("return (…)")` cannot express.
//   * type annotations are **stripped** before evaluation, so a stage may be
//     real TypeScript and not merely annotation-free JavaScript.
//
// Requires the wasm runtime built for Node: `bin/build-ts`.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import nodeModule, { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createContext, runInContext } from "node:vm";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));

// `--target nodejs` output: CommonJS with the wasm inlined-and-instantiated on
// require, so there is no init() to await (see the default export below).
const PKG = join(here, "..", "pkg", "quilt_wasm.js");
let RT;
try {
  RT = require(PKG);
} catch (cause) {
  throw new Error(
    `the quilt-wasm runtime is not built for Node at ${PKG} — run \`bin/build-ts\`` +
      " (wasm-pack build quilt-wasm --target nodejs --out-dir pkg)",
    { cause },
  );
}

export const {
  tb, leaf, sym, quote, unquote, cmd, write, push,
  name, qlift, qlift_html, NL, POP, HOLE,
  WasmQTerm, WasmBuilder, WasmStrCmd, WasmCmdOrHole,
} = RT;

// The browser build is `--target web`, whose default export is the wasm init()
// that callers `await`. Node's build instantiates on require, so this is a
// no-op — it exists so a program written for the playground (`import init from
// "quilt"; await init()`) also runs under `quilt run`.
export default async function init() {
  return RT;
}

/**************************************************************/

// Presence of any glyph means coparse() returned Quilt source (a generated
// stage that itself quotes), so it must be expanded before it can run.
const GLYPHS = "↖↗↙↘↑↓←⟨⟩";
const hasGlyph = (s) => [...GLYPHS].some((g) => s.includes(g));

// `quilt expand` prepends a `DO NOT EDIT` banner commented for the generated
// language (`//` for TypeScript). Match the banner itself rather than "leading
// comment lines", so a fragment that legitimately opens with a comment keeps it.
const BANNER = /^\/\/!? DO NOT EDIT\. GENERATED BY /;

function stripBanner(src) {
  const lines = src.split("\n");
  while (lines.length && BANNER.test(lines[0])) lines.shift();
  return lines.join("\n").replace(/^\n+/, "");
}

// The language chain a *generated* stage is written in. `quilt run` passes the
// running program's own chain (ground first) as $QUILT_CHAIN; without it, assume
// plain TypeScript.
//
// A stage is the content of a depth-1 quote, and the chain is indexed by quote
// depth, so the stage's own quotes read the chain one entry along. Hence: drop
// the first entry — *except* that a stage you can reduce is by definition a
// program in the host language, so the ground never drops. Both shapes occur:
//
//   dashboard.html.ts.ts  → [ts, ts, html] → stage is [ts, html]
//   cards.html.ts         → [ts, html]     → stage is [ts, html] (unchanged:
//                                             dropping "ts" would make the
//                                             stage an HTML program). Here the
//                                             reducible quote has to be written
//                                             `ts↖…↗`, and the tail is unused
//                                             because its inner quotes must be
//                                             annotated too.
function stageChain() {
  const chain = (process.env.QUILT_CHAIN || "").split(".").filter(Boolean);
  if (chain.length === 0) return ["ts"];
  const [ground, ...rest] = chain;
  return rest[0] === ground ? rest : chain;
}

/**
 * Expand Quilt source text to plain TypeScript by invoking `quilt expand`.
 *
 * The counterpart to reduce()'s plain evaluation: this handles source that
 * still contains Quilt glyphs — a generated stage that itself quotes. It shells
 * out to the prebuilt `quilt` binary, so nothing is compiled.
 *
 * `chain` is ground-language-first (`["ts", "html"]` for a TypeScript program
 * whose un-annotated quotes are HTML), matching `quilt expand`'s file stem read
 * right to left.
 */
export function expand(src, chain = stageChain()) {
  const bin = process.env.QUILT || "quilt";
  const dir = mkdtempSync(join(tmpdir(), "quilt-expand-"));
  try {
    const stem = `frag.${[...chain].reverse().join(".")}`;
    writeFileSync(join(dir, `${stem}.quilt`), src);
    try {
      execFileSync(bin, ["expand", join(dir, `${stem}.quilt`)], {
        stdio: ["ignore", "pipe", "pipe"],
      });
    } catch (cause) {
      if (cause.code === "ENOENT") {
        throw new Error(
          "expand(): cannot find the `quilt` binary — set $QUILT or put `quilt` " +
            "on PATH (it is set automatically when run via `quilt`)",
          { cause },
        );
      }
      const detail = (cause.stderr ?? "").toString().trim();
      throw new Error(`expand(): quilt expand failed${detail ? `\n${detail}` : ""}`, { cause });
    }
    return stripBanner(readFileSync(join(dir, stem), "utf8")); // expand strips `.quilt`
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// Reduce target/Quilt source to a value — the engine behind `↓`.
//
// Glyph-bearing source is expanded first, then evaluated as a *script*: any
// leading statements run and the value is the trailing expression — the same
// block-value semantics as quilt-python's `_reduce_src`, and of a Rust block.
// A script ending in a statement reduces to undefined.
//
// The sandbox inherits from the real `globalThis` (so a stage can still use
// `console`, timers, `Math`, …) with the runtime's builders layered on top, so
// expanded `tb(…)`/`qlift(…)` calls resolve without an import. Terms are
// therefore built by the *same* wasm instance as the caller's, and splice
// straight back into the reducing program.
function reduceSrc(src) {
  const code = hasGlyph(src) ? expand(src) : src;
  const sandbox = Object.assign(Object.create(globalThis), RT, { expand, reduce });
  createContext(sandbox);
  const opts = { filename: "<quilt-reduce>" };
  try {
    return runInContext(code, sandbox, opts);
  } catch (err) {
    // A stage may be annotated TypeScript, which `node:vm` — a JavaScript
    // evaluator — rejects at compile time. Strip the types and retry, but only
    // then: `stripTypeScriptTypes` is experimental, so calling it up front
    // would print a warning on every reduce of the plain-JS stages that are the
    // common case. (`name`, not `instanceof`: the error comes from the sandbox
    // realm, whose `SyntaxError` is a different intrinsic.) Nothing has run at
    // this point — a syntax error is raised before execution begins.
    if (err?.name !== "SyntaxError" || typeof nodeModule.stripTypeScriptTypes !== "function") {
      throw err;
    }
    let stripped;
    try {
      stripped = nodeModule.stripTypeScriptTypes(code, { mode: "strip" });
    } catch {
      throw err; // not TypeScript either: the JavaScript error is the useful one
    }
    return runInContext(stripped, sandbox, opts);
  }
}

/** Reduce a term to a value — the `↓` operator (block-aware; see reduceSrc). */
export function reduce(term) {
  return reduceSrc(term.coparse());
}

// Install `↓` itself: the TypeScript meta spells `term.↓` as `term.reduce()`.
RT.WasmQTerm.prototype.reduce = function reduce() {
  return reduceSrc(this.coparse());
};
