//! DO NOT EDIT. GENERATED BY `quilt expand /Users/avarga/Documents/QuiltLang/quilt/examples/countdown.rs.quilt`.

#!/usr/bin/env quilt
use quilt::prelude::*;

fn main() -> Result<()>{
    // Countdown start: the first CLI argument, or 10 by default.
    let n: i32 = std::env::args()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(10);
    
    // Build a block expression that counts down from `n`, then greets the new
    // year. The splice runs an ordinary loop at *generation* time, emitting one
    // `println!` statement per number into the quoted block. Each number is
    // lifted into the printed string literal.
    //
    // It's a block (an expression), not a `fn main` (an item), because the
    // reduce operator below evaluates it as `let output = <program>;` — and an
    // item can't go in expression position.
    let program = tb("expression_statement").c(&{
        let mut b_ = tb("block");
        sym("{").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            for c in (1..=n).rev() {
                tb("expression_statement").c(&tb("macro_invocation").c(&leaf("identifier", "println")).c(&sym("!")).c(&tb("token_tree").c(&sym("(")).c(&c.to_string().qlift()).c(&sym(")")).b()).b()).c(&sym(";")).b().emit(&mut b_);
                NL.emit(&mut b_);
            }
            tb("expression_statement").c(&tb("macro_invocation").c(&leaf("identifier", "println")).c(&sym("!")).c(&tb("token_tree").c(&sym("(")).c(&tb("string_literal").c(&sym("\"")).c(&leaf("string_content", "Happy New Year!")).c(&sym("\"")).b()).c(&sym(")")).b()).b()).c(&sym(";")).b().emit(&mut b_);
        };
        b_.pop();
        b_.nl();
        sym("}").emit(&mut b_);
        b_.b()
    }).b();
    
    // Print the generated source, then run it (the block evaluates to `()`).
    println!("{}", program.coparse());
    program.reduce()
}
