//! DO NOT EDIT. GENERATED BY `quilt expand examples/db_menu.py.rs.quilt`.

#!/usr/bin/env quilt
//! Machines at generation time (docs/design/machines.md): a live sqlite3
//! machine computes over data this meta-program feeds it, and the generated
//! Python ships only the answers. Three languages cooperate — Rust is the
//! meta-language, SQL fragments are built as terms and fed to the machine,
//! Python is the target — and the ground program is a *meta-machine*: a Rust
//! machine whose values include a SQL machine.
//!
//! Run with `quilt run examples/db_menu.py.rs.quilt` (needs sqlite3 on PATH).
use quilt::lang::InnerKind;
use quilt::prelude::*;

fn main() -> Result<()> {
    // The SQL machine: a live sqlite3 process; its temp tables are its
    // definitions. The machine glyph (issue #273) names the *language* and
    // lets the registered spec pick the provider — so this program says
    // nothing about sqlite3, and stays right when the provider improves. It
    // expands to `qspawn("sql")`, which reads the same spec table
    // `Multi::machine("sql")` reaches through the language registry — from
    // the runtime-only side of the feature gate, which is where an expanded
    // `.rs.quilt` file is built.
    let mut db = qspawn("sql")?;
    db.feed(InnerKind::Item, &tb("program").c(&tb("statement").c(&tb("create_table").c(&leaf("keyword_create", "CREATE")).w(" ").c(&leaf("keyword_temp", "TEMP")).w(" ").c(&leaf("keyword_table", "TABLE")).w(" ").c(&tb("object_reference").c(&leaf("identifier", "menu")).b()).c(&tb("column_definitions").c(&sym("(")).c(&tb("column_definition").c(&leaf("identifier", "item")).w(" ").c(&leaf("keyword_text", "TEXT")).b()).c(&sym(",")).w(" ").c(&tb("column_definition").c(&leaf("identifier", "price")).w(" ").c(&tb("double").c(&leaf("keyword_real", "REAL")).b()).b()).c(&sym(")")).b()).b()).b()).c(&sym(";")).b())?;
    
    // Each row is built as a SQL *term*, with `↑` lifting the Rust values
    // into SQL literals — a lifted string becomes a literal node with every
    // quote doubled, so O'Malley's apostrophe cannot escape the string and
    // continue the statement (issue #219).
    let menu = [("espresso", 2.50), ("latte", 3.75), ("O'Malley's blend", 4.20)];
    for (item, price) in menu {
        db.feed(InnerKind::Stmt, &tb("program").c(&tb("statement").c(&tb("insert").c(&leaf("keyword_insert", "INSERT")).w(" ").c(&leaf("keyword_into", "INTO")).w(" ").c(&tb("object_reference").c(&leaf("identifier", "menu")).b()).w(" ").c(&leaf("keyword_values", "VALUES")).w(" ").c(&{
            let mut b_ = tb("list");
            sym("(").emit(&mut b_);
            item.qlift_to::<Sql>().emit(&mut b_);
            sym(",").emit(&mut b_);
            b_.write(" ");
            price.qlift_to::<Sql>().emit(&mut b_);
            sym(")").emit(&mut b_);
            b_.b()
        }).b()).b()).c(&sym(";")).b())?;
    }
    
    // Ask the machine. Answers come back as SQL literals — text the meta-
    // program parses into Rust values.
    let count: i64 = query(&mut *db, &tb("statement").c(&sym("(")).c(&tb("select").c(&leaf("keyword_select", "SELECT")).w(" ").c(&tb("select_expression").c(&tb("term").c(&tb("invocation").c(&tb("object_reference").c(&leaf("identifier", "COUNT")).b()).c(&sym("(")).c(&tb("term").c(&tb("all_fields").c(&sym("*")).b()).b()).c(&sym(")")).b()).b()).b()).b()).w(" ").c(&tb("from").c(&leaf("keyword_from", "FROM")).w(" ").c(&tb("relation").c(&tb("object_reference").c(&leaf("identifier", "menu")).b()).b()).b()).c(&sym(")")).b())?
        .parse()
        .map_err(|e| miette!("count did not parse: {e}"))?;
    let total: f64 = query(&mut *db, &tb("statement").c(&sym("(")).c(&tb("select").c(&leaf("keyword_select", "SELECT")).w(" ").c(&tb("select_expression").c(&tb("term").c(&tb("invocation").c(&tb("object_reference").c(&leaf("identifier", "SUM")).b()).c(&sym("(")).c(&tb("term").c(&tb("field").c(&leaf("identifier", "price")).b()).b()).c(&sym(")")).b()).b()).b()).b()).w(" ").c(&tb("from").c(&leaf("keyword_from", "FROM")).w(" ").c(&tb("relation").c(&tb("object_reference").c(&leaf("identifier", "menu")).b()).b()).b()).c(&sym(")")).b())?
        .parse()
        .map_err(|e| miette!("total did not parse: {e}"))?;
    let dearest = query(
        &mut *db,
        &tb("statement").c(&sym("(")).c(&tb("select").c(&leaf("keyword_select", "SELECT")).w(" ").c(&tb("select_expression").c(&tb("term").c(&tb("field").c(&leaf("identifier", "item")).b()).b()).b()).b()).w(" ").c(&tb("from").c(&leaf("keyword_from", "FROM")).w(" ").c(&tb("relation").c(&tb("object_reference").c(&leaf("identifier", "menu")).b()).b()).w(" ").c(&tb("order_by").c(&leaf("keyword_order", "ORDER")).w(" ").c(&leaf("keyword_by", "BY")).w(" ").c(&tb("order_target").c(&tb("field").c(&leaf("identifier", "price")).b()).w(" ").c(&tb("direction").c(&leaf("keyword_desc", "DESC")).b()).b()).b()).w(" ").c(&tb("limit").c(&leaf("keyword_limit", "LIMIT")).w(" ").c(&leaf("literal", "1")).b()).b()).c(&sym(")")).b(),
    )?;
    
    // Generate the Python report — `↑` again, now lifting the same Rust
    // values into *Python* literals. The emitted program needs no database.
    let program = tb("module").c(&tb("function_definition").c(&sym("def")).w(" ").c(&leaf("identifier", "report")).c(&tb("parameters").c(&sym("(")).c(&sym(")")).b()).c(&sym(":")).p("    ").n().c(&tb("block").c(&tb("call").c(&leaf("identifier", "print")).c(&{
        let mut b_ = tb("argument_list");
        sym("(").emit(&mut b_);
        tb("string").c(&leaf("string_start", "\"")).c(&leaf("string_content", "menu items:")).c(&leaf("string_end", "\"")).b().emit(&mut b_);
        sym(",").emit(&mut b_);
        b_.write(" ");
        count.qlift_to::<Python>().emit(&mut b_);
        sym(")").emit(&mut b_);
        b_.b()
    }).b()).n().c(&tb("call").c(&leaf("identifier", "print")).c(&{
        let mut b_ = tb("argument_list");
        sym("(").emit(&mut b_);
        tb("string").c(&leaf("string_start", "\"")).c(&leaf("string_content", "total:")).c(&leaf("string_end", "\"")).b().emit(&mut b_);
        sym(",").emit(&mut b_);
        b_.write(" ");
        total.qlift_to::<Python>().emit(&mut b_);
        sym(")").emit(&mut b_);
        b_.b()
    }).b()).n().c(&tb("call").c(&leaf("identifier", "print")).c(&{
        let mut b_ = tb("argument_list");
        sym("(").emit(&mut b_);
        tb("string").c(&leaf("string_start", "\"")).c(&leaf("string_content", "dearest:")).c(&leaf("string_end", "\"")).b().emit(&mut b_);
        sym(",").emit(&mut b_);
        b_.write(" ");
        dearest.qlift_to::<Python>().emit(&mut b_);
        sym(")").emit(&mut b_);
        b_.b()
    }).b()).b()).x().b()).n().n().c(&tb("call").c(&leaf("identifier", "report")).c(&tb("argument_list").c(&sym("(")).c(&sym(")")).b()).b()).b();
    println!("{}", program.coparse());
    Ok(())
}

/// One Expr feed, unwrapped to the answered literal's text. Takes a *term*,
/// like everything else here: `qspawn` hands back a `Box<dyn Machine>`, whose
/// door is the terms-first `feed` rather than any one provider's raw-text
/// shortcut — which is the right door anyway for a file whose point is that
/// SQL is composed as data.
fn query(db: &mut dyn Machine, q: &Arc<QTerm>) -> Result<String> {
    let answer = db.feed(InnerKind::Expr, q)?;
    let value = answer.value.ok_or_else(|| {
        miette!("the sql machine answered no value for {:?}", q.coparse())
    })?;
    Ok(value.into())
}
