//! DO NOT EDIT. GENERATED BY `quilt expand examples/expr_compose.py.quilt`.

#!/usr/bin/env quilt run
from quilt import *

# Quilt's Python mode: quoting builds a QTerm for a Python expression;
# unquoting splices a QTerm back into a surrounding quote.
# Everything below is *generation-time* structure building -- no eval() anywhere.
# coparse() shows what the composed expression looks like as source.

print("=== Simple quoted expressions ===")
data = tb("list").c(sym("[")).c(leaf("integer", "1")).c(sym(",")).w(" ").c(leaf("integer", "2")).c(sym(",")).w(" ").c(leaf("integer", "3")).c(sym(",")).w(" ").c(leaf("integer", "4")).c(sym(",")).w(" ").c(leaf("integer", "5")).c(sym(",")).w(" ").c(leaf("integer", "6")).c(sym(",")).w(" ").c(leaf("integer", "7")).c(sym(",")).w(" ").c(leaf("integer", "8")).c(sym(",")).w(" ").c(leaf("integer", "9")).c(sym(",")).w(" ").c(leaf("integer", "10")).c(sym("]")).b()
base = leaf("integer", "2")
exp  = leaf("integer", "10")
print("data :", data.coparse())
print("base :", base.coparse())
print("exp  :", exp.coparse())

print("\n=== Composition by splicing ===")
# Unquoting base and exp fills holes in the surrounding quote.
power   = tb("binary_operator").c(base).w(" ").c(sym("**")).w(" ").c(exp).b()
product = tb("binary_operator").c(base).w(" ").c(sym("*")).w(" ").c(power).b()
print("2**10        :", power.coparse())
print("2 * 2**10    :", product.coparse())

print("\n=== Nesting: comprehensions from quoted parts ===")
# Each step quotes an expression referencing the previous step's QTerm.
evens   = tb("list_comprehension").c(sym("[")).c(leaf("identifier", "x")).w(" ").c(tb("for_in_clause").c(sym("for")).w(" ").c(leaf("identifier", "x")).w(" ").c(sym("in")).w(" ").c(data).b()).w(" ").c(tb("if_clause").c(sym("if")).w(" ").c(tb("comparison_operator").c(tb("binary_operator").c(leaf("identifier", "x")).w(" ").c(sym("%")).w(" ").c(leaf("integer", "2")).b()).w(" ").c(sym("==")).w(" ").c(leaf("integer", "0")).b()).b()).c(sym("]")).b()
doubled = tb("list_comprehension").c(sym("[")).c(tb("binary_operator").c(leaf("identifier", "x")).w(" ").c(sym("*")).w(" ").c(leaf("integer", "2")).b()).w(" ").c(tb("for_in_clause").c(sym("for")).w(" ").c(leaf("identifier", "x")).w(" ").c(sym("in")).w(" ").c(evens).b()).c(sym("]")).b()
total   = tb("call").c(leaf("identifier", "sum")).c(tb("argument_list").c(sym("(")).c(doubled).c(sym(")")).b()).b()
print("evens  :", evens.coparse())
print("doubled:", doubled.coparse())
print("total  :", total.coparse())

print("\n=== Conditional expression ===")
# power is 2**10; the whole ternary is a new quoted expression.
parity = tb("conditional_expression").c(tb("string").c(leaf("string_start", "\"")).c(leaf("string_content", "even")).c(leaf("string_end", "\"")).b()).w(" ").c(sym("if")).w(" ").c(tb("comparison_operator").c(tb("binary_operator").c(power).w(" ").c(sym("%")).w(" ").c(leaf("integer", "2")).b()).w(" ").c(sym("==")).w(" ").c(leaf("integer", "0")).b()).w(" ").c(sym("else")).w(" ").c(tb("string").c(leaf("string_start", "\"")).c(leaf("string_content", "odd")).c(leaf("string_end", "\"")).b()).b()
print("parity :", parity.coparse())
