//! DO NOT EDIT. GENERATED BY `quilt expand examples/factorials.py.rs.quilt`.

#!/usr/bin/env quilt run
use quilt::prelude::*;

// Rust generating Python. The .py.rs chain (extensions read right-to-left)
// makes Rust the ground language and Python the default language for
// un-annotated quotes. (The arrow glyphs are live even in comments, so we
// can't spell them here.)
//
// The factorial table is computed here, at generation time; the emitted
// Python module is pure data plus an O(1) lookup.

/// Inject a Rust value as a Python leaf node with the given tree-sitter tag.
fn py(tag: &str, s: impl std::fmt::Display) -> Arc<QTerm> {
    leaf(tag, &s.to_string())
}

fn main() -> Result<()> {
    let n: u64 = std::env::args()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(10)
        .min(20); // 21! overflows u64
    
    let mut table = vec![1u64];
    for i in 1..=n {
        table.push(table[(i - 1) as usize] * i);
    }
    let list = format!(
        "[{}]",
        table.iter().map(u64::to_string).collect::<Vec<_>>().join(", ")
    );
    
    let module = {
        let mut b_ = tb("module");
        leaf("comment", "# Generated by factorials.py.rs.quilt — do not edit.").emit(&mut b_);
        b_.nl();
        tb("expression_statement").c(&tb("assignment").c(&leaf("identifier", "FACTORIALS")).w(" ").c(&sym("=")).w(" ").c(&py("list", list)).b()).b().emit(&mut b_);
        b_.nl();
        b_.nl();
        tb("function_definition").c(&sym("def")).w(" ").c(&leaf("identifier", "factorial")).c(&tb("parameters").c(&sym("(")).c(&leaf("identifier", "n")).c(&sym(")")).b()).c(&sym(":")).p("    ").n().c(&{
            let mut b_ = tb("block");
            tb("expression_statement").c(&tb("string").c(&leaf("string_start", "\"\"\"")).c(&leaf("string_content", "Factorial by table lookup; the table was baked in at generation time.")).c(&leaf("string_end", "\"\"\"")).b()).b().emit(&mut b_);
            b_.nl();
            tb("return_statement").c(&sym("return")).w(" ").c(&tb("subscript").c(&leaf("identifier", "FACTORIALS")).c(&sym("[")).c(&leaf("identifier", "n")).c(&sym("]")).b()).b().emit(&mut b_);
            b_.b()
        }).x().b().emit(&mut b_);
        b_.nl();
        b_.nl();
        tb("if_statement").c(&sym("if")).w(" ").c(&tb("comparison_operator").c(&leaf("identifier", "__name__")).w(" ").c(&sym("==")).w(" ").c(&tb("string").c(&leaf("string_start", "\"")).c(&leaf("string_content", "__main__")).c(&leaf("string_end", "\"")).b()).b()).c(&sym(":")).p("    ").n().c(&{
            let mut b_ = tb("block");
            tb("for_statement").c(&sym("for")).w(" ").c(&leaf("identifier", "i")).w(" ").c(&sym("in")).w(" ").c(&tb("call").c(&leaf("identifier", "range")).c(&tb("argument_list").c(&sym("(")).c(&tb("call").c(&leaf("identifier", "len")).c(&tb("argument_list").c(&sym("(")).c(&leaf("identifier", "FACTORIALS")).c(&sym(")")).b()).b()).c(&sym(")")).b()).b()).c(&sym(":")).p("    ").n().c(&{
                let mut b_ = tb("block");
                tb("expression_statement").c(&tb("call").c(&leaf("identifier", "print")).c(&tb("argument_list").c(&sym("(")).c(&tb("string").c(&leaf("string_start", "f\"")).c(&tb("interpolation").c(&sym("{")).c(&leaf("identifier", "i")).c(&sym("}")).b()).c(&leaf("string_content", "! = ")).c(&tb("interpolation").c(&sym("{")).c(&tb("call").c(&leaf("identifier", "factorial")).c(&tb("argument_list").c(&sym("(")).c(&leaf("identifier", "i")).c(&sym(")")).b()).b()).c(&sym("}")).b()).c(&leaf("string_end", "\"")).b()).c(&sym(")")).b()).b()).b().emit(&mut b_);
                b_.b()
            }).x().b().emit(&mut b_);
            b_.b()
        }).x().b().emit(&mut b_);
        b_.b()
    };
    
    println!("{}", module.coparse());
    Ok(())
}
