//! DO NOT EDIT. GENERATED BY `quilt expand /Users/avarga/Documents/QuiltLang/quilt/examples/fizzbuzz_gen.rs.quilt`.

#!/usr/bin/env quilt run
use quilt::prelude::*;

fn main() -> Result<()> {
    let n: i32 = std::env::args()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(20);
    
    // The FizzBuzz decision (branching) runs at *generation* time.
    // The produced program is a flat sequence of straight-line println! calls —
    // no if/match at runtime, no numbers, no modular arithmetic.
    let program = tb("expression_statement").c(&{
        let mut b_ = tb("block");
        sym("{").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            for i in 1..=n {
                let label = if i % 15 == 0 {
                    "FizzBuzz".to_string()
                } else if i % 3 == 0 {
                    "Fizz".to_string()
                } else if i % 5 == 0 {
                    "Buzz".to_string()
                } else {
                    i.to_string()
                };
                tb("expression_statement").c(&tb("macro_invocation").c(&leaf("identifier", "println")).c(&sym("!")).c(&tb("token_tree").c(&sym("(")).c(&label.qlift()).c(&sym(")")).b()).b()).c(&sym(";")).b().emit(&mut b_);
                NL.emit(&mut b_);
            }
        };
        b_.pop();
        b_.nl();
        sym("}").emit(&mut b_);
        b_.b()
    }).b();
    
    println!("=== Generated {n} println! calls ===");
    println!("{}", program.coparse());
    println!("\n=== Output ===");
    program.reduce()
}
