//! DO NOT EDIT. GENERATED BY `quilt expand /Users/avarga/Documents/QuiltLang/quilt/examples/hello.py.quilt`.

#!/usr/bin/env quilt run
from quilt import *

# A quoted Python expression expands to builder code that rebuilds the term;
# coparse() serializes a term back to source.
expr = tb("binary_operator").c(leaf("integer", "1")).w(" ").c(sym("+")).w(" ").c(leaf("integer", "2")).b()
print("expr   =", expr.coparse())

# An unquote splices an existing term into a quote.
ten = leaf("integer", "10")
scaled = tb("binary_operator").c(ten).w(" ").c(sym("*")).w(" ").c(leaf("integer", "100")).b()
print("scaled =", scaled.coparse())
