//! DO NOT EDIT. GENERATED BY `quilt expand examples/lean_do_pipeline.rs.quilt`.

#!/usr/bin/env quilt
//! Generate a Lean 4 `IO` program: a pipeline runner whose do-block is built
//! one statement at a time from a Rust-side table of stages.
//!
//! Lean is a *target* here, quoted inside a Rust host. The interesting part is
//! do-notation, which the other Lean examples do not reach: a `do` block is a
//! Variadic container, so statements can be *emitted* into it, and the binds
//! themselves are generated -- one `let <name> <- stage ...` per row.
//!
//! ## Monadic bind must be written `<-`, not `←`
//!
//! Lean spells monadic bind `←`, which is also Quilt's *emit* glyph. Inside a
//! quote, a bare `←` is consumed by Quilt as an emit and never reaches the Lean
//! parser, leaving a stray hole behind. Lean's ASCII alias `<-` means exactly
//! the same thing and has no meaning to Quilt, so it passes through untouched.
//! That is what this file uses, and it is the recommended spelling for
//! generated monadic Lean. (`\←` also works -- see issue #141.)
//!
//! Note the two kinds of `let` in the generated do-block are both here: `<-`
//! binds an `IO Nat`, while `:=` binds a pure term. The pure one is the folded
//! sum of every stage, built at *generation* time, so the emitted Lean contains
//! a flat `a + b + c` with no loop left in it.
//!
//! Run `quilt expand` on this file to see the Rust it becomes, or run it
//! directly (`quilt examples/lean_do_pipeline.rs.quilt`) to print the Lean.
use quilt::prelude::*;

/// A Lean identifier term, for splicing into name position.
fn ident(s: &str) -> Arc<QTerm> {
    leaf("identifier", s)
}

fn main() -> Result<()> {
    // The pipeline, fixed at generation time: (stage name, cost in ms).
    let stages = [("fetch", 12u32), ("parse", 30), ("render", 8)];
    // Generated into the emitted `if`, so the budget check is baked in too.
    let budget = 40u32;
    
    // The helper every generated bind calls. Plain quoted Lean, no splices.
    let helper = tb("def").c(&sym("def")).w(" ").c(&leaf("identifier", "stage")).w(" ").c(&tb("binders").c(&tb("explicit_binder").c(&sym("(")).c(&leaf("identifier", "name")).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "String")).c(&sym(")")).b()).w(" ").c(&tb("explicit_binder").c(&sym("(")).c(&leaf("identifier", "cost")).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Nat")).c(&sym(")")).b()).b()).w(" ").c(&sym(":")).w(" ").c(&tb("app").c(&leaf("identifier", "IO")).w(" ").c(&leaf("identifier", "Nat")).b()).w(" ").c(&sym(":=")).w(" ").c(&tb("do_block").c(&sym("do")).p("    ").n().c(&tb("app").c(&leaf("identifier", "IO.println")).w(" ").c(&tb("interpolated_str").c(&sym("s!\"")).w("  ").c(&tb("interpolation").c(&sym("{")).c(&leaf("identifier", "name")).c(&sym("}")).b()).w(": ").c(&tb("interpolation").c(&sym("{")).c(&leaf("identifier", "cost")).c(&sym("}")).b()).w("ms").c(&sym("\"")).b()).b()).n().c(&tb("app").c(&leaf("identifier", "pure")).w(" ").c(&leaf("identifier", "cost")).b()).x().b()).b();
    
    // The sum of every stage's binding, folded now so the emitted Lean is a
    // flat `fetch + parse + render` rather than anything recursive.
    let mut total = ident(stages[0].0);
    for (name, _) in &stages[1..] {
        let next = ident(name);
        total = tb("binary_op").c(&total).w(" ").c(&sym("+")).w(" ").c(&next).b();
    }
    
    // `main`, whose do-block is emitted statement by statement. A do-block is
    // Variadic, so each emitted term becomes one of its children; `NL.←`
    // emits the line break between them.
    let main = tb("def").c(&sym("def")).w(" ").c(&leaf("identifier", "main")).w(" ").c(&sym(":")).w(" ").c(&tb("app").c(&leaf("identifier", "IO")).w(" ").c(&leaf("identifier", "Unit")).b()).w(" ").c(&sym(":=")).w(" ").c(&{
        let mut b_ = tb("do_block");
        sym("do").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            tb("app").c(&leaf("identifier", "IO.println")).w(" ").c(&tb("str_lit").c(&sym("\"")).w("stages:").c(&sym("\"")).b()).b().emit(&mut b_);
            NL.emit(&mut b_);
            // One monadic bind per stage. `<-`, not `←` -- see the note above.
            for (name, cost) in stages {
                let var = ident(name);
                tb("let").c(&sym("let")).w(" ").c(&var).w(" ").c(&sym("<-")).w(" ").c(&tb("app").c(&tb("app").c(&leaf("identifier", "stage")).w(" ").c(&name.qlift_to::<Lean>()).b()).w(" ").c(&cost.qlift_to::<Lean>()).b()).b().emit(&mut b_);
                NL.emit(&mut b_);
            }
            // A *pure* let, bound to the generation-time fold.
            tb("let").c(&sym("let")).w(" ").c(&leaf("identifier", "total")).w(" ").c(&sym(":=")).w(" ").c(&total).b().emit(&mut b_);
            NL.emit(&mut b_);
            tb("app").c(&leaf("identifier", "IO.println")).w(" ").c(&tb("interpolated_str").c(&sym("s!\"")).w("total: ").c(&tb("interpolation").c(&sym("{")).c(&leaf("identifier", "total")).c(&sym("}")).b()).w("ms").c(&sym("\"")).b()).b().emit(&mut b_);
            NL.emit(&mut b_);
            // Kept on one line: an emitted fragment's own line breaks are
            // indented relative to the *enclosing* quote, so a multi-line
            // emit into an already-indented block needs care. A single-line
            // `if … then … else …` sidesteps it and is idiomatic Lean anyway.
            tb("if_then_else").c(&sym("if")).w(" ").c(&tb("binary_op").c(&leaf("identifier", "total")).w(" ").c(&sym(">")).w(" ").c(&budget.qlift_to::<Lean>()).b()).w(" ").c(&sym("then")).w(" ").c(&tb("app").c(&leaf("identifier", "IO.println")).w(" ").c(&tb("str_lit").c(&sym("\"")).w("over budget").c(&sym("\"")).b()).b()).w(" ").c(&sym("else")).w(" ").c(&tb("app").c(&leaf("identifier", "IO.println")).w(" ").c(&tb("str_lit").c(&sym("\"")).w("within budget").c(&sym("\"")).b()).b()).b().emit(&mut b_);
        };
        b_.pop();
        b_.b()
    }).b();
    
    println!("{}\n\n{}", helper.coparse(), main.coparse());
    Ok(())
}
