//! DO NOT EDIT. GENERATED BY `quilt expand examples/lean_datatypes.rs.quilt`.

#!/usr/bin/env quilt
//! Generate Lean 4 *data* declarations -- an `inductive` and a `structure` --
//! together with the functions and theorems that go with them, all from one
//! Rust-side schema.
//!
//! The other Lean examples generate `def`s and theorems; this one covers the
//! declaration forms that introduce new types, and shows exactly where Quilt's
//! structural approach stops and host-side assembly takes over.
//!
//! ## Where the boundary is
//!
//! A constructor list (`| red | green | blue`) and a field list (`red : Nat`)
//! are variable-length, and neither is a Variadic container in Lean's grammar
//! -- only `by` and `do` are. Nor is either a standalone parseable fragment:
//! `lean↖| Color.red => 0↗` and `lean↖red : Nat↗` are both parse errors,
//! because Lean's `module` holds *commands*, and a bare arm or binder is
//! neither a command nor a term. So the constructor and field lines are built
//! as host strings and joined -- the same idiom `lean_specialize.rs.quilt`
//! uses for declaration sequences. Issue #133 covers the grammar change that
//! would make them structural.
//!
//! *Everything else* is a real QTerm. Note in particular that the two
//! variable-length **terms** are folds, not string joins:
//!
//!   * `Color.code` is a right-nested `if … then … else …` chain, one arm per
//!     channel, folded at generation time; and
//!   * `Palette.total` is a folded `+` chain over the projections.
//!
//! Choosing `if`/`else` over a `match` is what makes that possible: the fold
//! composes complete Lean *terms* at every step, so each one is parsed and
//! checked by the Lean grammar as it is built. A `match` would have forced the
//! whole body into the string path.
//!
//! The theorems are the point of the exercise: `Color.code_lt` states a bound
//! that *is* generation-time data (the number of channels), and Lean proves it
//! by `cases … <;> decide` -- so if the schema and the generated bound ever
//! disagreed, the generated file would fail to compile.
use quilt::prelude::*;

/// A Lean identifier term, for splicing into name position.
fn ident(s: &str) -> Arc<QTerm> {
    leaf("identifier", s)
}

fn main() -> Result<()> {
    // The schema, fixed at generation time. Everything below follows from it.
    let channels = ["red", "green", "blue"];
    let n = u32::try_from(channels.len()).unwrap();
    
    let mut decls: Vec<String> = Vec::new();
    
    // --- The two declarations that need host-side assembly (see header). ---
    
    let ctors = channels
        .iter()
        .map(|c| format!("  | {c}"))
        .collect::<Vec<_>>()
        .join("\n");
    decls.push(format!(
        "inductive Color where\n{ctors}\n  deriving Repr, DecidableEq"
    ));
    
    let fields = channels
        .iter()
        .map(|c| format!("  {c} : Nat"))
        .collect::<Vec<_>>()
        .join("\n");
    decls.push(format!(
        "structure Palette where\n{fields}\n  deriving Repr, DecidableEq"
    ));
    
    // --- From here on everything is built structurally, as QTerms. ---
    
    // `Color.code`: a right-nested if/else chain, folded from the last channel
    // backwards. The final `else` is the last channel's index, so the chain
    // has one test fewer than there are channels.
    let last = u32::try_from(channels.len() - 1).unwrap();
    let mut code = last.qlift_to::<Lean>();
    for (i, ch) in channels.iter().enumerate().rev().skip(1) {
        let ctor = ident(&format!("Color.{ch}"));
        let idx = u32::try_from(i).unwrap();
        code = tb("if_then_else").c(&sym("if")).w(" ").c(&tb("binary_op").c(&leaf("identifier", "c")).w(" ").c(&sym("=")).w(" ").c(&ctor).b()).w(" ").c(&sym("then")).w(" ").c(&idx.qlift_to::<Lean>()).w(" ").c(&sym("else")).w(" ").c(&code).b();
    }
    decls.push({
        let mut b_ = tb("def");
        sym("def").emit(&mut b_);
        b_.write(" ");
        leaf("identifier", "Color.code").emit(&mut b_);
        b_.write(" ");
        tb("binders").c(&tb("explicit_binder").c(&sym("(")).c(&leaf("identifier", "c")).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Color")).c(&sym(")")).b()).b().emit(&mut b_);
        b_.write(" ");
        sym(":").emit(&mut b_);
        b_.write(" ");
        leaf("identifier", "Nat").emit(&mut b_);
        b_.write(" ");
        sym(":=").emit(&mut b_);
        b_.write(" ");
        code.emit(&mut b_);
        b_.b()
    }.coparse());
    
    // The bound is the channel count, lifted out of the Rust list. `decide`
    // closes each case, so a wrong bound would be a compile error downstream.
    decls.push(
        tb("theorem").c(&sym("theorem")).w(" ").c(&leaf("identifier", "Color.code_lt")).w(" ").c(&tb("binders").c(&tb("explicit_binder").c(&sym("(")).c(&leaf("identifier", "c")).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Color")).c(&sym(")")).b()).b()).w(" ").c(&sym(":")).w(" ").c(&tb("binary_op").c(&leaf("identifier", "c.code")).w(" ").c(&sym("<")).w(" ").c(&n.qlift_to::<Lean>()).b()).w(" ").c(&sym(":=")).w(" ").c(&tb("by").c(&sym("by")).p("  ").n().c(&tb("binary_op").c(&tb("induction").c(&sym("cases")).w(" ").c(&leaf("identifier", "c")).b()).w(" ").c(&sym("<;>")).w(" ").c(&leaf("identifier", "decide")).b()).x().b()).b()
        .coparse(),
    );
    
    // `Palette.total`: a folded `+` over the field projections. The projection
    // is built host-side as one identifier -- `p.↙ch↘` would work too, but a
    // whole name is clearer and matches how the other Lean examples do it.
    let mut total = ident(&format!("p.{}", channels[0]));
    for ch in &channels[1..] {
        let proj = ident(&format!("p.{ch}"));
        total = tb("binary_op").c(&total).w(" ").c(&sym("+")).w(" ").c(&proj).b();
    }
    decls.push({
        let mut b_ = tb("def");
        sym("def").emit(&mut b_);
        b_.write(" ");
        leaf("identifier", "Palette.total").emit(&mut b_);
        b_.write(" ");
        tb("binders").c(&tb("explicit_binder").c(&sym("(")).c(&leaf("identifier", "p")).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Palette")).c(&sym(")")).b()).b().emit(&mut b_);
        b_.write(" ");
        sym(":").emit(&mut b_);
        b_.write(" ");
        leaf("identifier", "Nat").emit(&mut b_);
        b_.write(" ");
        sym(":=").emit(&mut b_);
        b_.write(" ");
        total.emit(&mut b_);
        b_.b()
    }.coparse());
    
    // State what `total` computes on a literal `Palette.mk`. True by `rfl`:
    // `total` is a plain sum, so both sides are definitionally equal.
    //
    // The right-hand side is a folded `+` over the binder names, and the
    // constructor call is a folded *application* -- both are terms, so both
    // are built structurally.
    let mut rhs = ident(channels[0]);
    let mut mk = ident("Palette.mk");
    for ch in &channels[1..] {
        let arg = ident(ch);
        rhs = tb("binary_op").c(&rhs).w(" ").c(&sym("+")).w(" ").c(&arg).b();
    }
    for ch in channels {
        let arg = ident(ch);
        mk = tb("app").c(&mk).w(" ").c(&arg).b();
    }
    // The binder group `(red green blue : Nat)` is *not* a term -- it is the
    // same non-Variadic, non-standalone shape as the field list above, so it
    // is assembled host-side and spliced as one leaf.
    let binder_group = leaf("identifier", &channels.join(" "));
    // `mk` is an application, so it is parenthesised before `.total`: a splice
    // carries a term, not a precedence level.
    decls.push(
        tb("theorem").c(&sym("theorem")).w(" ").c(&leaf("identifier", "Palette.total_mk")).w(" ").c(&tb("binders").c(&{
            let mut b_ = tb("explicit_binder");
            sym("(").emit(&mut b_);
            binder_group.emit(&mut b_);
            b_.write(" ");
            sym(":").emit(&mut b_);
            b_.write(" ");
            leaf("identifier", "Nat").emit(&mut b_);
            sym(")").emit(&mut b_);
            b_.b()
        }).b()).w(" ").c(&sym(":")).w(" ").c(&tb("binary_op").c(&tb("proj").c(&{
            let mut b_ = tb("paren");
            sym("(").emit(&mut b_);
            mk.emit(&mut b_);
            sym(")").emit(&mut b_);
            b_.b()
        }).c(&sym(".")).c(&leaf("identifier", "total")).b()).w(" ").c(&sym("=")).w(" ").c(&rhs).b()).w(" ").c(&sym(":=")).w(" ").c(&tb("by").c(&sym("by")).w(" ").c(&leaf("identifier", "rfl")).b()).b()
        .coparse(),
    );
    
    // `main`, emitted statement by statement into the do-block -- one line per
    // channel, reporting the code Lean computed for it.
    //
    // Note the channel name is *lifted* into a Lean string literal and
    // concatenated, rather than spliced into an `s!"…"` interpolation. A hole
    // cannot go inside a string literal: Lean's grammar lexes the whole
    // literal as one token, so `__QUILT_HOLE__` inside it never becomes a node
    // for Quilt to plug. Interpolating Lean's *own* values (`{…}` over a Lean
    // binder, as in the `total` line below) is fine -- that is Lean's
    // interpolation, evaluated at Lean runtime, not a Quilt splice.
    let main = tb("def").c(&sym("def")).w(" ").c(&leaf("identifier", "main")).w(" ").c(&sym(":")).w(" ").c(&tb("app").c(&leaf("identifier", "IO")).w(" ").c(&leaf("identifier", "Unit")).b()).w(" ").c(&sym(":=")).w(" ").c(&{
        let mut b_ = tb("do_block");
        sym("do").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            for ch in channels {
                let ctor = ident(&format!("Color.{ch}"));
                tb("app").c(&leaf("identifier", "IO.println")).w(" ").c(&tb("paren").c(&sym("(")).c(&tb("binary_op").c(&ch.qlift_to::<Lean>()).w(" ").c(&sym("++")).w(" ").c(&tb("binary_op").c(&tb("str_lit").c(&sym("\"")).w(" -> ").c(&sym("\"")).b()).w(" ").c(&sym("++")).w(" ").c(&tb("proj").c(&tb("app").c(&leaf("identifier", "toString")).w(" ").c(&{
                    let mut b_ = tb("paren");
                    sym("(").emit(&mut b_);
                    ctor.emit(&mut b_);
                    sym(")").emit(&mut b_);
                    b_.b()
                }).b()).c(&sym(".")).c(&leaf("identifier", "code")).b()).b()).b()).c(&sym(")")).b()).b().emit(&mut b_);
                NL.emit(&mut b_);
            }
            tb("app").c(&leaf("identifier", "IO.println")).w(" ").c(&tb("interpolated_str").c(&sym("s!\"")).w("total = ").c(&tb("interpolation").c(&sym("{")).c(&tb("proj").c(&tb("paren").c(&sym("(")).c(&tb("app").c(&tb("app").c(&tb("app").c(&leaf("identifier", "Palette.mk")).w(" ").c(&leaf("num_lit", "1")).b()).w(" ").c(&leaf("num_lit", "2")).b()).w(" ").c(&leaf("num_lit", "3")).b()).c(&sym(")")).b()).c(&sym(".")).c(&leaf("identifier", "total")).b()).c(&sym("}")).b()).c(&sym("\"")).b()).b().emit(&mut b_);
        };
        b_.pop();
        b_.b()
    }).b();
    decls.push(main.coparse());
    
    println!("{}", decls.join("\n\n"));
    Ok(())
}
