//! DO NOT EDIT. GENERATED BY `quilt expand examples/lean_tactics.rs.quilt`.

#!/usr/bin/env quilt
//! Generate Lean 4 *proofs*: theorems whose tactic scripts are emitted one
//! tactic at a time, with the number of steps decided at generation time.
//!
//! A `by` block is a Variadic container -- like `do`, and unlike a `match`'s
//! arms or an `inductive`'s constructors -- so tactics can be *emitted* into
//! it with the postfix arrow. That is the whole point of this example: the
//! proof script is not a string being concatenated, it is a sequence of parsed
//! Lean tactic terms becoming children of the `by` node.
//!
//! What makes it worth doing is that both halves of each theorem come from the
//! same Rust data:
//!
//!   * the **statement** -- the chain `bump4 (bump3 (bump2 (bump1 x)))` and
//!     the constant `x + 10` it collapses to -- is folded over the increment
//!     table, with the total summed in Rust and lifted into a Lean literal; and
//!   * the **proof** -- one `unfold` per generated definition, closed by a
//!     single `omega` -- is emitted from that same table.
//!
//! So the script length tracks the schema. Add a row to `increments` and the
//! chain grows, the constant changes, and the proof grows by one `unfold`,
//! with no line edited by hand. If the lifted constant and the definitions
//! ever disagreed, `omega` would fail and the generated file would not
//! compile -- the generator cannot quietly emit a false theorem.
//!
//! `unfold` rather than `simp only` is deliberate: `simp` normalises the
//! arithmetic as it goes and closes the goal early, which would leave the
//! final `omega` with no goals ("No goals to be solved"). `unfold` does the
//! rewriting and nothing else, so the closing tactic stays meaningful.
//!
//! Verify with the real toolchain: run this file, then `lean` the output.
use quilt::prelude::*;

/// A Lean identifier term, for splicing into name position.
fn ident(s: &str) -> Arc<QTerm> {
    leaf("identifier", s)
}

/// Fold `names` into the nested application `last (… (first arg))`.
///
/// The innermost call takes `arg` bare -- it is an atom, so parenthesising it
/// would only add noise -- and each wrap after that parenthesises the
/// application it wraps, which is what Lean's left-associative application
/// requires.
fn apply_chain(names: &[String], arg: Arc<QTerm>) -> Arc<QTerm> {
    let first = ident(&names[0]);
    let mut chain = tb("app").c(&first).w(" ").c(&arg).b();
    for name in &names[1..] {
        let f = ident(name);
        chain = tb("app").c(&f).w(" ").c(&tb("paren").c(&sym("(")).c(&chain).c(&sym(")")).b()).b();
    }
    chain
}

fn main() -> Result<()> {
    // The chain to generate, fixed at generation time: bump1 adds 1, and so on.
    let increments = [1u32, 2, 3, 4];
    
    let names: Vec<String> = (1..=increments.len()).map(|i| format!("bump{i}")).collect();
    let total: u32 = increments.iter().sum();
    
    let mut decls: Vec<String> = Vec::new();
    
    // One `def` per increment.
    for (name, k) in names.iter().zip(increments) {
        let f = ident(name);
        decls.push(tb("def").c(&sym("def")).w(" ").c(&f).w(" ").c(&tb("binders").c(&tb("explicit_binder").c(&sym("(")).c(&leaf("identifier", "x")).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Nat")).c(&sym(")")).b()).b()).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Nat")).w(" ").c(&sym(":=")).w(" ").c(&tb("binary_op").c(&leaf("identifier", "x")).w(" ").c(&sym("+")).w(" ").c(&k.qlift_to::<Lean>()).b()).b().coparse());
    }
    
    // The nested application `bumpN (… (bump1 x))`, folded outward from the
    // argument so the emitted statement is already flat. The innermost call
    // takes a bare atom, so it is built without parentheses; every wrap after
    // that parenthesises the application it is wrapping.
    let chain = apply_chain(&names, leaf("identifier", "x"));
    
    // The proof script, emitted into the `by` block: one `unfold` per
    // definition, in the order they must be peeled, then `omega` to finish.
    // Building it twice (once per theorem) keeps each `by` block's children
    // distinct -- a term is emitted into exactly one parent.
    let value_thm = tb("theorem").c(&sym("theorem")).w(" ").c(&leaf("identifier", "bump_chain")).w(" ").c(&tb("binders").c(&tb("explicit_binder").c(&sym("(")).c(&leaf("identifier", "x")).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Nat")).c(&sym(")")).b()).b()).w(" ").c(&sym(":")).w(" ").c(&tb("binary_op").c(&chain).w(" ").c(&sym("=")).w(" ").c(&tb("binary_op").c(&leaf("identifier", "x")).w(" ").c(&sym("+")).w(" ").c(&total.qlift_to::<Lean>()).b()).b()).w(" ").c(&sym(":=")).w(" ").c(&{
        let mut b_ = tb("by");
        sym("by").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            for name in &names {
                let f = ident(name);
                tb("app").c(&leaf("identifier", "unfold")).w(" ").c(&f).b().emit(&mut b_);
                NL.emit(&mut b_);
            }
            leaf("identifier", "omega").emit(&mut b_);
        };
        b_.pop();
        b_.b()
    }).b();
    decls.push(value_thm.coparse());
    
    // The same emitted script proving a different statement -- the chain is
    // increasing. Same tactics, so the generator reuses the shape verbatim.
    let bound_thm = tb("theorem").c(&sym("theorem")).w(" ").c(&leaf("identifier", "bump_chain_ge")).w(" ").c(&tb("binders").c(&tb("explicit_binder").c(&sym("(")).c(&leaf("identifier", "x")).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Nat")).c(&sym(")")).b()).b()).w(" ").c(&sym(":")).w(" ").c(&tb("binary_op").c(&leaf("identifier", "x")).w(" ").c(&sym("≤")).w(" ").c(&chain).b()).w(" ").c(&sym(":=")).w(" ").c(&{
        let mut b_ = tb("by");
        sym("by").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            for name in &names {
                let f = ident(name);
                tb("app").c(&leaf("identifier", "unfold")).w(" ").c(&f).b().emit(&mut b_);
                NL.emit(&mut b_);
            }
            leaf("identifier", "omega").emit(&mut b_);
        };
        b_.pop();
        b_.b()
    }).b();
    decls.push(bound_thm.coparse());
    
    // A `main` that exercises the chain, so the generated file is runnable as
    // well as checkable. `x` is not in scope here, so the same fold is run
    // again rooted at a literal `0` -- cheaper and clearer than substituting
    // into the finished term.
    //
    // The splice is parenthesised: `applied` is an application, and Lean's
    // application is left-associative, so a bare `toString ↙applied↘` would
    // read as `toString bump4 (…)` -- two arguments to `toString` -- rather
    // than `toString` of the whole chain. Quilt splices a term, not a
    // precedence level, so the surrounding syntax has to say what it means.
    let applied = apply_chain(&names, leaf("num_lit", "0"));
    let main = tb("def").c(&sym("def")).w(" ").c(&leaf("identifier", "main")).w(" ").c(&sym(":")).w(" ").c(&tb("app").c(&leaf("identifier", "IO")).w(" ").c(&leaf("identifier", "Unit")).b()).w(" ").c(&sym(":=")).w(" ").c(&{
        let mut b_ = tb("do_block");
        sym("do").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            tb("app").c(&leaf("identifier", "IO.println")).w(" ").c(&tb("paren").c(&sym("(")).c(&tb("binary_op").c(&tb("str_lit").c(&sym("\"")).w("chain 0 = ").c(&sym("\"")).b()).w(" ").c(&sym("++")).w(" ").c(&tb("app").c(&leaf("identifier", "toString")).w(" ").c(&tb("paren").c(&sym("(")).c(&applied).c(&sym(")")).b()).b()).b()).c(&sym(")")).b()).b().emit(&mut b_);
        };
        b_.pop();
        b_.b()
    }).b();
    decls.push(main.coparse());
    
    println!("{}", decls.join("\n\n"));
    Ok(())
}
