//! DO NOT EDIT. GENERATED BY `quilt expand examples/lean_specialize.rs.quilt`.

#!/usr/bin/env quilt
//! Generate Lean 4 definitions, their correctness theorems, and a `main` that
//! exercises them -- all from one Rust table.
//!
//! Lean is a *target* language here: it only appears inside lean quote
//! brackets embedded in a host language (Rust). Quilt parses each fragment
//! into a QTerm, the Rust host splices values in at generation time, and
//! .coparse() serializes the tree back to plain Lean source.
//!
//! The point is staging. Specializing `x ^ n` for a fixed `n` is exactly the
//! sort of thing you do not want to write by hand once per exponent -- and in
//! Lean you also want the accompanying simp lemma for each one. The loop runs
//! at *generation* time, so the emitted Lean has no recursion left in it.
//!
//! Three ways of crossing the language boundary show up here:
//!
//!   * the lift operator (a postfix between the unquote brackets) turns a Rust
//!     integer into a Lean numeric literal;
//!   * a *name* is spliced as an ordinary Lean identifier term. Note it cannot
//!     be written `pow↙n.↑↘`: an identifier immediately before an unquote
//!     bracket is read as a language annotation, so the whole name is built on
//!     the Rust side and spliced as one term; and
//!   * emitting (the postfix arrow) appends into a *variadic* container. In
//!     Lean those are `module`, `by` and `do`, so `main`'s do-block below is
//!     built by emitting one statement per exponent.
//!
//! The declarations themselves are joined functionally rather than emitted.
//! Splicing a whole declaration at command position does work (`namespace D
//! ↙decl↘ end D`), but emitting a *sequence* of them needs a variadic module
//! container, which a bare-hole quote does not currently produce -- see issue
//! #133. Building the list in Rust and joining is the idiomatic alternative,
//! and is what the Nix host does too.
use quilt::prelude::*;

/// A Lean identifier term, for splicing into name position.
fn ident(s: &str) -> Arc<QTerm> {
    leaf("identifier", s)
}

/// The body of `pow<n>`: `x * x * ... * x`, with n factors. Folded at
/// generation time, so the emitted term is already flat.
fn body(n: u32) -> Arc<QTerm> {
    let mut acc = leaf("identifier", "x");
    for _ in 1..n {
        acc = tb("binary_op").c(&acc).w(" ").c(&sym("*")).w(" ").c(&leaf("identifier", "x")).b();
    }
    acc
}

fn main() -> Result<()> {
    // The exponents to specialize, fixed at generation time.
    let exponents = [2u32, 3, 4];
    
    // One `def` plus its `simp` lemma per exponent.
    let mut decls: Vec<String> = Vec::new();
    for n in exponents {
        let name = ident(&format!("pow{n}"));
        let lemma = ident(&format!("pow{n}_eq"));
        
        decls.push(tb("def").c(&sym("def")).w(" ").c(&name).w(" ").c(&tb("binders").c(&tb("explicit_binder").c(&sym("(")).c(&leaf("identifier", "x")).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Nat")).c(&sym(")")).b()).b()).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Nat")).w(" ").c(&sym(":=")).w(" ").c(&body(n)).b().coparse());
        decls.push(
            tb("declaration").c(&tb("attributes").c(&sym("@[")).c(&leaf("identifier", "simp")).c(&sym("]")).b()).w(" ").c(&tb("theorem").c(&sym("theorem")).w(" ").c(&lemma).w(" ").c(&tb("binders").c(&tb("explicit_binder").c(&sym("(")).c(&leaf("identifier", "x")).w(" ").c(&sym(":")).w(" ").c(&leaf("identifier", "Nat")).c(&sym(")")).b()).b()).w(" ").c(&sym(":")).w(" ").c(&tb("binary_op").c(&tb("app").c(&name).w(" ").c(&leaf("identifier", "x")).b()).w(" ").c(&sym("=")).w(" ").c(&tb("binary_op").c(&leaf("identifier", "x")).w(" ").c(&sym("^")).w(" ").c(&n.qlift_to::<Lean>()).b()).b()).w(" ").c(&sym(":=")).w(" ").c(&{
                let mut b_ = tb("by");
                {
                    let mut b_ = tb("by");
                    b_.write("by");
                    b_.b()
                }.emit(&mut b_);
                b_.push("  ");
                b_.nl();
                tb("app").c(&leaf("identifier", "simp")).w(" ").c(&tb("list_lit").c(&sym("[")).c(&name).c(&sym(",")).w(" ").c(&leaf("identifier", "Nat.pow_succ")).c(&sym(",")).w(" ").c(&leaf("identifier", "Nat.pow_zero")).c(&sym(",")).w(" ").c(&leaf("identifier", "Nat.one_mul")).c(&sym("]")).b()).b().emit(&mut b_);
                b_.pop();
                b_.b()
            }).b()).b()
            .coparse(),
        );
    }
    
    // `main`, built by emitting one statement per exponent into the do-block.
    // A do-block is variadic, so the emitted statements become its children.
    let main = tb("def").c(&sym("def")).w(" ").c(&leaf("identifier", "main")).w(" ").c(&sym(":")).w(" ").c(&tb("app").c(&leaf("identifier", "IO")).w(" ").c(&leaf("identifier", "Unit")).b()).w(" ").c(&sym(":=")).w(" ").c(&{
        let mut b_ = tb("do_block");
        sym("do").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            for n in exponents {
                let name = ident(&format!("pow{n}"));
                tb("app").c(&leaf("identifier", "IO.println")).w(" ").c(&tb("paren").c(&sym("(")).c(&tb("app").c(&name).w(" ").c(&leaf("num_lit", "5")).b()).c(&sym(")")).b()).b().emit(&mut b_);
                NL.emit(&mut b_);
            }
        };
        b_.pop();
        b_.b()
    }).b();
    decls.push(main.coparse());
    
    println!("{}", decls.join("\n\n"));
    Ok(())
}
