//! DO NOT EDIT. GENERATED BY `quilt expand examples/nix_module.rs.quilt`.

#!/usr/bin/env quilt
//! Generate a Nix derivation expression from a declarative Rust table.
//!
//! Nix is a *target* language in Quilt: it only appears inside nix quote
//! brackets embedded in a host language (here, Rust). Quilt parses each
//! fragment into a QTerm, the Rust host splices values in at generation time,
//! and .coparse() serializes the tree back to a plain Nix expression.
//!
//! Computed Rust values cross into the quoted Nix through the lift operator --
//! a postfix written between the unquote brackets. It turns a Rust string into
//! a double-quoted Nix string and a list into a space-separated Nix list, so
//! the example never builds terms by hand. The inner Rust block over the
//! dependencies runs at *generation* time: it emits one list element per
//! dependency, unrolling the list into the emitted source.
use quilt::prelude::*;

fn main() -> Result<()> {
    // The package, fixed at generation time.
    let pname = "hello";
    let version = "2.12.1";
    
    // Build dependencies; each becomes an element of the buildInputs list.
    let deps = ["gcc", "gnumake", "pkg-config"];
    
    // The lifted dependency names, emitted into a Nix list. The iteration runs
    // now; lifting a value (the postfix between the unquote brackets) crosses
    // it into the quoted Nix as a string literal, emitting appends it, and a
    // space is emitted before every element but the first to separate them.
    let build_inputs = {
        let mut b_ = tb("list_expression");
        sym("[").emit(&mut b_);
        b_.write(" ");
        {
            for (i, d) in deps.into_iter().enumerate() {
                if i > 0 { " ".emit(&mut b_); }
                d.qlift_to::<Nix>().emit(&mut b_);
            }
        }.emit(&mut b_);
        b_.write(" ");
        sym("]").emit(&mut b_);
        b_.b()
    };
    
    // Splice the scalars and the generated list into a derivation skeleton.
    let drv = tb("function_expression").c(&{
        let mut b_ = tb("formals");
        sym("{").emit(&mut b_);
        b_.write(" ");
        tb("formal").c(&leaf("identifier", "pkgs")).w(" ").c(&sym("?")).w(" ").c(&tb("apply_expression").c(&tb("apply_expression").c(&tb("variable_expression").c(&leaf("identifier", "import")).b()).w(" ").c(&leaf("spath_expression", "<nixpkgs>")).b()).w(" ").c(&tb("attrset_expression").c(&sym("{")).w(" ").c(&sym("}")).b()).b()).b().emit(&mut b_);
        b_.write(" ");
        sym("}").emit(&mut b_);
        b_.b()
    }).c(&sym(":")).n().c(&tb("apply_expression").c(&tb("select_expression").c(&tb("variable_expression").c(&leaf("identifier", "pkgs")).b()).c(&sym(".")).c(&tb("attrpath").c(&leaf("identifier", "stdenv")).c(&sym(".")).c(&leaf("identifier", "mkDerivation")).b()).b()).w(" ").c(&tb("attrset_expression").c(&sym("{")).p("  ").n().c(&{
        let mut b_ = tb("binding_set");
        tb("binding").c(&tb("attrpath").c(&leaf("identifier", "pname")).b()).w(" ").c(&sym("=")).w(" ").c(&pname.qlift_to::<Nix>()).c(&sym(";")).b().emit(&mut b_);
        b_.nl();
        tb("binding").c(&tb("attrpath").c(&leaf("identifier", "version")).b()).w(" ").c(&sym("=")).w(" ").c(&version.qlift_to::<Nix>()).c(&sym(";")).b().emit(&mut b_);
        b_.nl();
        tb("binding").c(&tb("attrpath").c(&leaf("identifier", "buildInputs")).b()).w(" ").c(&sym("=")).w(" ").c(&build_inputs).c(&sym(";")).b().emit(&mut b_);
        b_.b()
    }).x().n().c(&sym("}")).b()).b()).b();
    
    println!("{}", drv.coparse());
    Ok(())
}
