//! DO NOT EDIT. GENERATED BY `quilt expand examples/pow_specialize.rs.quilt`.

#!/usr/bin/env quilt run
// Partial evaluation of lam p: lam b: b^p specialized to a given p.
// The binary squaring loop runs at *generation* time; the emitted closure has
// no exponent, no loop, no branches — just let-bindings and multiplications.
use quilt::prelude::*;

fn main() -> Result<()> {
    let p: u32 = std::env::args()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(10);
    
    let body = pow_body(p)?;
    let p_lit = p.qlift();
    
    // Wrap the specialized body in a test harness that exercises it on a few
    // base values so we can verify the output immediately.
    let program = tb("expression_statement").c(&{
        let mut b_ = tb("block");
        sym("{").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        tb("let_declaration").c(&sym("let")).w(" ").c(&leaf("identifier", "f")).w(" ").c(&sym("=")).w(" ").c(&tb("closure_expression").c(&tb("closure_parameters").c(&sym("|")).c(&tb("parameter").c(&leaf("identifier", "b")).c(&sym(":")).w(" ").c(&leaf("primitive_type", "u64")).b()).c(&sym("|")).b()).w(" ").c(&sym("->")).w(" ").c(&leaf("primitive_type", "u64")).w(" ").c(&body).b()).c(&sym(";")).b().emit(&mut b_);
        b_.nl();
        tb("expression_statement").c(&tb("for_expression").c(&sym("for")).w(" ").c(&leaf("identifier", "b")).w(" ").c(&sym("in")).w(" ").c(&tb("array_expression").c(&sym("[")).c(&leaf("integer_literal", "2u64")).c(&sym(",")).w(" ").c(&leaf("integer_literal", "3")).c(&sym(",")).w(" ").c(&leaf("integer_literal", "5")).c(&sym(",")).w(" ").c(&leaf("integer_literal", "7")).c(&sym(",")).w(" ").c(&leaf("integer_literal", "11")).c(&sym("]")).b()).w(" ").c(&{
            let mut b_ = tb("block");
            sym("{").emit(&mut b_);
            b_.push("    ");
            b_.nl();
            tb("expression_statement").c(&tb("macro_invocation").c(&leaf("identifier", "println")).c(&sym("!")).c(&tb("token_tree").c(&sym("(")).c(&tb("string_literal").c(&sym("\"")).c(&leaf("string_content", "{}^{} = {}")).c(&sym("\"")).b()).c(&sym(",")).w(" ").c(&leaf("identifier", "b")).c(&sym(",")).w(" ").c(&p_lit).c(&sym(",")).w(" ").c(&leaf("identifier", "f")).c(&tb("token_tree").c(&sym("(")).c(&leaf("identifier", "b")).c(&sym(")")).b()).c(&sym(")")).b()).b()).c(&sym(";")).b().emit(&mut b_);
            b_.pop();
            b_.nl();
            sym("}").emit(&mut b_);
            b_.b()
        }).b()).b().emit(&mut b_);
        b_.pop();
        b_.nl();
        sym("}").emit(&mut b_);
        b_.b()
    }).b();
    
    println!("=== Specialized pow(b, {p}) by exponentiation by squaring ===");
    println!("{}", program.coparse());
    println!("\n=== Output ===");
    program.reduce()
}

/// Return a block QTerm `{ let t0 = ...; ...; t_n }` that computes `b^p`
/// using only multiplications.  `b` is a free variable that the caller's
/// closure binds as its parameter.
fn pow_body(p: u32) -> Result<Arc<QTerm>> {
    if p == 0 {
        return Ok(tb("expression_statement").c(&{
            let mut b_ = tb("block");
            sym("{").emit(&mut b_);
            b_.write(" ");
            leaf("integer_literal", "1u64").emit(&mut b_);
            b_.write(" ");
            sym("}").emit(&mut b_);
            b_.b()
        }).b());
    }
    if p == 1 {
        return Ok(tb("expression_statement").c(&{
            let mut b_ = tb("block");
            sym("{").emit(&mut b_);
            b_.write(" ");
            leaf("identifier", "b").emit(&mut b_);
            b_.write(" ");
            sym("}").emit(&mut b_);
            b_.b()
        }).b());
    }
    let (stmts, result) = pow_squaring(p)?;
    Ok(tb("expression_statement").c(&{
        let mut b_ = tb("block");
        sym("{").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            for stmt in stmts {
                stmt.emit(&mut b_);
                NL.emit(&mut b_);
            }
            result.emit(&mut b_);
        };
        b_.pop();
        b_.nl();
        sym("}").emit(&mut b_);
        b_.b()
    }).b())
}

/// Run the binary squaring algorithm at generation time.
///
/// Returns the sequence of `let` statement QTerms and the final result
/// expression QTerm.  Together they compute `b^p` using only multiplications.
///
/// Algorithm (right-to-left binary method):
///   acc   = 1 (identity; represented as None until first factor is absorbed)
///   sq    = b (the running b^(2^k), squaring on each loop step)
///   while exp > 0:
///     if exp & 1:  acc *= sq  (emit a new let-binding)
///     sq  *= sq               (emit a new let-binding; skip on last step)
///     exp >>= 1
fn pow_squaring(p: u32) -> Result<(Vec<Arc<QTerm>>, Arc<QTerm>)> {
    let mut stmts: Vec<Arc<QTerm>> = Vec::new();
    let mut sq: Arc<QTerm> = leaf("identifier", "b");          // current b^(2^k)
    let mut acc: Option<Arc<QTerm>> = None;  // accumulated product (None = 1)
    let mut exp = p;
    let mut n = 0usize; // counter for fresh temporary names t0, t1, ...
    
    while exp > 0 {
        // If the current bit is set, fold sq into the accumulator.
        if exp & 1 == 1 {
            acc = Some(match acc {
                None => sq.clone(), // first factor: just record sq, no binding needed
                Some(prev) => {
                    let var = name(&format!("t{n}"));
                    let var_expr = var.clone();
                    n += 1;
                    let sq2 = sq.clone();
                    stmts.push(tb("let_declaration").c(&sym("let")).w(" ").c(&var).w(" ").c(&sym("=")).w(" ").c(&tb("binary_expression").c(&prev).w(" ").c(&sym("*")).w(" ").c(&sq2).b()).c(&sym(";")).b());
                    var_expr
                }
            });
        }
        exp >>= 1;
        // Square the base for the next bit — skip on the final iteration.
        if exp > 0 {
            let var = name(&format!("t{n}"));
            let var_expr = var.clone();
            n += 1;
            let sq2 = sq.clone();
            let sq3 = sq.clone();
            stmts.push(tb("let_declaration").c(&sym("let")).w(" ").c(&var).w(" ").c(&sym("=")).w(" ").c(&tb("binary_expression").c(&sq2).w(" ").c(&sym("*")).w(" ").c(&sq3).b()).c(&sym(";")).b());
            sq = var_expr;
        }
    }
    
    let result = acc.expect("p >= 2 guarantees at least one bit is set");
    Ok((stmts, result))
}
