//! DO NOT EDIT. GENERATED BY `quilt expand /Users/avarga/Documents/QuiltLang/quilt/examples/pow_specialize.py.quilt`.

#!/usr/bin/env quilt
from quilt import *

# Partial evaluation of pow(b, p) by exponentiation by squaring.
# The loop runs at *generation* time; the emitted lambda has no loop or
# branches — just multiplications.
#
# Python has no let-bindings in expressions, so we encode them as nested
# lambda applications: (lambda t0: (lambda t1: result)(rhs1))(rhs0).

def pow_squaring(p):
    """Return (bindings, result) where bindings is [(var, rhs), ...] QTerm pairs."""
    bindings = []
    sq  = leaf("identifier", "b")      # current b^(2^k)
    acc = None      # accumulated product (None = identity, not yet started)
    n   = 0
    exp = p
    while exp > 0:
        if exp & 1:
            if acc is None:
                acc = sq
            else:
                var = name(f"t{n}"); n += 1
                bindings.append((var, tb("binary_operator").c(acc).w(" ").c(sym("*")).w(" ").c(sq).b()))
                acc = var
        exp >>= 1
        if exp > 0:
            var = name(f"t{n}"); n += 1
            bindings.append((var, tb("binary_operator").c(sq).w(" ").c(sym("*")).w(" ").c(sq).b()))
            sq = var
    return bindings, acc

def make_pow_lambda(p):
    if p == 0:
        return tb("lambda").c(sym("lambda")).w(" ").c(tb("lambda_parameters").c(leaf("identifier", "b")).b()).c(sym(":")).w(" ").c(leaf("integer", "1")).b()
    if p == 1:
        return tb("lambda").c(sym("lambda")).w(" ").c(tb("lambda_parameters").c(leaf("identifier", "b")).b()).c(sym(":")).w(" ").c(leaf("identifier", "b")).b()
    bindings, result = pow_squaring(p)
    # Encode bindings inside-out as nested lambda applications.
    for var, rhs in reversed(bindings):
        result = tb("call").c(tb("parenthesized_expression").c(sym("(")).c(tb("lambda").c(sym("lambda")).w(" ").c(var).c(sym(":")).w(" ").c(result).b()).c(sym(")")).b()).c(tb("argument_list").c(sym("(")).c(rhs).c(sym(")")).b()).b()
    return tb("lambda").c(sym("lambda")).w(" ").c(tb("lambda_parameters").c(leaf("identifier", "b")).b()).c(sym(":")).w(" ").c(result).b()

p = 10
lam = make_pow_lambda(p)

print(f"=== Specialized pow(b, {p}) by binary squaring ===")
print("source:", lam.coparse())
print()

f = lam.reduce()
for b in [2, 3, 5, 7, 11]:
    print(f"{b}^{p} = {f(b)}")
