//! DO NOT EDIT. GENERATED BY `quilt expand /Users/avarga/Documents/QuiltLang/quilt/examples/primes.rs.quilt`.

#!/usr/bin/env quilt
use quilt::prelude::*;

fn sieve(limit: u64) -> Vec<u64> {
    let mut composite = vec![false; (limit + 1) as usize];
    let mut primes = Vec::new();
    for n in 2..=limit {
        if !composite[n as usize] {
            primes.push(n);
            let mut m = n.saturating_mul(n);
            while m <= limit {
                composite[m as usize] = true;
                m += n;
            }
        }
    }
    primes
}

fn main() -> Result<()> {
    let limit: u64 = std::env::args()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(100);
    
    // Run the Sieve of Eratosthenes at *generation* time.
    // The generated program has the results baked in as string constants —
    // no sieve, no arithmetic, no heap allocation at runtime.
    let primes = sieve(limit);
    let count = primes.len();
    let sum: u64 = primes.iter().sum();
    
    let program = tb("expression_statement").c(&{
        let mut b_ = tb("block");
        sym("{").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            let title = format!("Primes up to {limit}: {count} found, sum = {sum}");
            tb("expression_statement").c(&tb("macro_invocation").c(&leaf("identifier", "println")).c(&sym("!")).c(&tb("token_tree").c(&sym("(")).c(&title.qlift()).c(&sym(")")).b()).b()).c(&sym(";")).b().emit(&mut b_);
            NL.emit(&mut b_);
            for chunk in primes.chunks(10) {
                let row: String = chunk
                    .iter()
                    .map(|p| format!("{p:5}"))
                    .collect::<Vec<_>>()
                    .join(" ");
                tb("expression_statement").c(&tb("macro_invocation").c(&leaf("identifier", "println")).c(&sym("!")).c(&tb("token_tree").c(&sym("(")).c(&row.qlift()).c(&sym(")")).b()).b()).c(&sym(";")).b().emit(&mut b_);
                NL.emit(&mut b_);
            }
        };
        b_.pop();
        b_.nl();
        sym("}").emit(&mut b_);
        b_.b()
    }).b();
    
    println!("=== Generated source ===");
    println!("{}", program.coparse());
    println!("\n=== Output ===");
    program.reduce()
}
