//! DO NOT EDIT. GENERATED BY `quilt expand /Users/avarga/Documents/QuiltLang/quilt/examples/reduce.py.quilt`.

#!/usr/bin/env quilt
from quilt import *

# reduce() (reduce) eval-s a QTerm's source back to a live Python value.
# Write `expr.reduce()` to call .reduce() on any QTerm.

print("=== Literal lambda ===")
double = tb("lambda").c(sym("lambda")).w(" ").c(tb("lambda_parameters").c(leaf("identifier", "x")).b()).c(sym(":")).w(" ").c(tb("binary_operator").c(leaf("identifier", "x")).w(" ").c(sym("*")).w(" ").c(leaf("integer", "2")).b()).b()
print("source :", double.coparse())
fn = double.reduce()
print("fn(5)  =", fn(5))    # 10
print("fn(21) =", fn(21))   # 42

print("\n=== Lambda composed from quoted sub-expressions ===")
factor = leaf("integer", "7")
scaled = tb("lambda").c(sym("lambda")).w(" ").c(tb("lambda_parameters").c(leaf("identifier", "x")).b()).c(sym(":")).w(" ").c(tb("binary_operator").c(leaf("identifier", "x")).w(" ").c(sym("*")).w(" ").c(factor).b()).b()
print("source    :", scaled.coparse())
times7 = scaled.reduce()
print("times7(6) =", times7(6))    # 42

print("\n=== Power lambda with a composed exponent ===")
n = leaf("integer", "3")
power_of_n = tb("lambda").c(sym("lambda")).w(" ").c(tb("lambda_parameters").c(leaf("identifier", "x")).b()).c(sym(":")).w(" ").c(tb("binary_operator").c(leaf("identifier", "x")).w(" ").c(sym("**")).w(" ").c(n).b()).b()
print("source      :", power_of_n.coparse())
cube = power_of_n.reduce()
print("cube(4)     =", cube(4))    # 64
print("cube(10)    =", cube(10))   # 1000

print("\n=== Generate a family of threshold filters ===")
for threshold in [leaf("integer", "2"), leaf("integer", "5"), leaf("integer", "8")]:
    above = (tb("lambda").c(sym("lambda")).w(" ").c(tb("lambda_parameters").c(leaf("identifier", "xs")).b()).c(sym(":")).w(" ").c(tb("list_comprehension").c(sym("[")).c(leaf("identifier", "x")).w(" ").c(tb("for_in_clause").c(sym("for")).w(" ").c(leaf("identifier", "x")).w(" ").c(sym("in")).w(" ").c(leaf("identifier", "xs")).b()).w(" ").c(tb("if_clause").c(sym("if")).w(" ").c(tb("comparison_operator").c(leaf("identifier", "x")).w(" ").c(sym(">")).w(" ").c(threshold).b()).b()).c(sym("]")).b()).b()).reduce()
    print(f"  threshold={threshold.coparse()}: {above(list(range(10)))}")
