# DO NOT EDIT. GENERATED BY `quilt expand examples/sql_session.sql.py.quilt`.

#!/usr/bin/env quilt
# A Python program creating and instrumenting a SQL machine with Quilt
# syntax (docs/design/machines.md). The `.sql.py` stem makes Python the
# ground language and SQL the default for bare quote brackets, so every
# fragment fed to the machine is authored as a SQL *term* — composed and
# spliced as data, never as string concatenation.
#
# `spawn("sql")` is a live sqlite3 connection behind quilt's Machine trait
# (issue #271); its temp tables are its definitions. The down-arrow glyph in
# method position is machine-directed reduce (issue #268): `db.` + down-arrow
# + `(term)` expands to `db.eval(term)`, which classifies the term with the
# language itself — definitions and statements feed, expressions answer.
# Lifting Python values into SQL literals is tracked as issue #272; until
# then, data rides inside quoted terms.
#
# Run with `quilt run examples/sql_session.sql.py.quilt`
# (needs the quilt_python module: bin/build-py; sqlite3 on PATH).
from quilt import *

# Create the machine and feed it definitions, authored as terms.
db = spawn("sql")
db.eval(tb("program").c(tb("statement").c(tb("create_table").c(leaf("keyword_create", "CREATE")).w(" ").c(leaf("keyword_temp", "TEMP")).w(" ").c(leaf("keyword_table", "TABLE")).w(" ").c(tb("object_reference").c(leaf("identifier", "menu")).b()).c(tb("column_definitions").c(sym("(")).c(tb("column_definition").c(leaf("identifier", "item")).w(" ").c(leaf("keyword_text", "TEXT")).b()).c(sym(",")).w(" ").c(tb("column_definition").c(leaf("identifier", "price")).w(" ").c(tb("double").c(leaf("keyword_real", "REAL")).b()).b()).c(sym(")")).b()).b()).b()).c(sym(";")).b())
db.eval(tb("program").c(tb("statement").c(tb("insert").c(leaf("keyword_insert", "INSERT")).w(" ").c(leaf("keyword_into", "INTO")).w(" ").c(tb("object_reference").c(leaf("identifier", "menu")).b()).w(" ").c(leaf("keyword_values", "VALUES")).w(" ").c(tb("list").c(sym("(")).c(leaf("literal", "'espresso'")).c(sym(",")).w(" ").c(leaf("literal", "2.5")).c(sym(")")).b()).c(sym(",")).w(" ").c(tb("list").c(sym("(")).c(leaf("literal", "'latte'")).c(sym(",")).w(" ").c(leaf("literal", "3.75")).c(sym(")")).b()).c(sym(",")).w(" ").c(tb("list").c(sym("(")).c(leaf("literal", "'cortado'")).c(sym(",")).w(" ").c(leaf("literal", "3.25")).c(sym(")")).b()).b()).b()).c(sym(";")).b())

# Instrument it: one predicate term, spliced into two different queries.
pricey = tb("binary_expression").c(tb("field").c(leaf("identifier", "price")).b()).w(" ").c(sym(">")).w(" ").c(leaf("literal", "3.0")).b()
print("pricey items:", db.eval(tb("statement").c(sym("(")).c(tb("select").c(leaf("keyword_select", "SELECT")).w(" ").c(tb("select_expression").c(tb("term").c(tb("invocation").c(tb("object_reference").c(leaf("identifier", "COUNT")).b()).c(sym("(")).c(tb("term").c(tb("all_fields").c(sym("*")).b()).b()).c(sym(")")).b()).b()).b()).b()).w(" ").c(tb("from").c(leaf("keyword_from", "FROM")).w(" ").c(tb("relation").c(tb("object_reference").c(leaf("identifier", "menu")).b()).b()).w(" ").c(tb("where").c(leaf("keyword_where", "WHERE")).w(" ").c(pricey).b()).b()).c(sym(")")).b()))
print("they are:", db.eval(tb("program").c(tb("statement").c(tb("select").c(leaf("keyword_select", "SELECT")).w(" ").c(tb("select_expression").c(tb("term").c(tb("field").c(leaf("identifier", "item")).b()).b()).b()).b()).w(" ").c(tb("from").c(leaf("keyword_from", "FROM")).w(" ").c(tb("relation").c(tb("object_reference").c(leaf("identifier", "menu")).b()).b()).w(" ").c(tb("where").c(leaf("keyword_where", "WHERE")).w(" ").c(pricey).b()).b()).b()).c(sym(";")).b()))

# The typing judgment, in the machine's own spelling.
print("SUM(price) is a", db.type_of(tb("statement").c(sym("(")).c(tb("select").c(leaf("keyword_select", "SELECT")).w(" ").c(tb("select_expression").c(tb("term").c(tb("invocation").c(tb("object_reference").c(leaf("identifier", "SUM")).b()).c(sym("(")).c(tb("term").c(tb("field").c(leaf("identifier", "price")).b()).b()).c(sym(")")).b()).b()).b()).b()).w(" ").c(tb("from").c(leaf("keyword_from", "FROM")).w(" ").c(tb("relation").c(tb("object_reference").c(leaf("identifier", "menu")).b()).b()).b()).c(sym(")")).b()))
