//! DO NOT EDIT. GENERATED BY `quilt expand examples/sql_query.rs.quilt`.

#!/usr/bin/env quilt
//! Build sanitized SQL queries from a Rust host.
//!
//! SQL is a *target* language in Quilt: it only appears inside sql quote
//! brackets embedded in a host language (here, Rust). Quilt parses each
//! fragment into a QTerm, the Rust host splices values in, and .coparse()
//! serializes the tree back to plain SQL.
//!
//! The reason to do this rather than build a query with format! is what
//! crossing the boundary means. A value enters the query through the lift
//! operator -- a postfix written between the unquote brackets -- which turns it
//! into a *literal node*, not into text. A string becomes one `literal` token
//! whose spelling is standard SQL with every quote doubled, so a value cannot
//! close the literal and continue the statement. The last query below is built
//! from a name chosen to break out of a format!-assembled string; it comes back
//! as a single literal instead.
//!
//! Composition works at two levels: a whole statement is a fragment, and so is
//! a bare predicate -- `sql↖a = 1↗` parses even though SQL's own grammar has no
//! place for an expression on its own.
use quilt::prelude::*;

/// One filter the report can apply, as a Rust value.
enum Filter {
    Org(&'static str),
    MinAge(u32),
    Active(bool),
}

impl Filter {
    // Turn a filter into a SQL predicate fragment: a bare expression quote,
    // with the value placed by a lift.
    fn predicate(&self) -> Arc<QTerm> {
        // `*self`, not `self`: every payload here is `Copy`, and matching
        // through the reference binds `&&str` / `&u32`, which the lift cannot
        // see through — `LiftTo` is implemented for `str`, not for `&str`.
        match *self {
            Filter::Org(name) => tb("binary_expression").c(&tb("field").c(&leaf("identifier", "org")).b()).w(" ").c(&sym("=")).w(" ").c(&name.qlift_to::<Sql>()).b(),
            Filter::MinAge(n) => tb("binary_expression").c(&tb("field").c(&leaf("identifier", "age")).b()).w(" ").c(&sym(">=")).w(" ").c(&n.qlift_to::<Sql>()).b(),
            Filter::Active(b) => tb("binary_expression").c(&tb("field").c(&leaf("identifier", "active")).b()).w(" ").c(&sym("=")).w(" ").c(&b.qlift_to::<Sql>()).b(),
        }
    }
}

/// `SELECT id, name FROM members WHERE <conjunction of the filters>`.
///
/// The predicates are combined at *generation* time by folding the Rust list,
/// so the emitted query is one flat statement with no runtime assembly left in
/// it.
fn report(filters: &[Filter]) -> Arc<QTerm> {
    let mut pred = tb("literal").c(&leaf("keyword_true", "TRUE")).b();
    for f in filters {
        let rhs = f.predicate();
        pred = tb("binary_expression").c(&pred).w(" ").c(&leaf("keyword_and", "AND")).w(" ").c(&rhs).b();
    }
    // Bound rather than returned directly: a *statement* quote sitting in Rust
    // tail position is the shape the expander reads as "emit me into the
    // enclosing builder" (see the `is_stmt_like` heuristic in `multi.rs`), which
    // is right inside an emit loop and wrong for a return value.
    let query = tb("statement").c(&tb("select").c(&leaf("keyword_select", "SELECT")).w(" ").c(&tb("select_expression").c(&tb("term").c(&tb("field").c(&leaf("identifier", "id")).b()).b()).c(&sym(",")).w(" ").c(&tb("term").c(&tb("field").c(&leaf("identifier", "name")).b()).b()).b()).b()).w(" ").c(&tb("from").c(&leaf("keyword_from", "FROM")).w(" ").c(&tb("relation").c(&tb("object_reference").c(&leaf("identifier", "members")).b()).b()).w(" ").c(&tb("where").c(&leaf("keyword_where", "WHERE")).w(" ").c(&pred).b()).b()).b();
    query
}

/// A seed script: one INSERT per member, wrapped in a script that creates the
/// table first and indexes it last.
///
/// The generated statements go into a hole at *statement* position -- a
/// position a bare identifier cannot occupy, since no SQL statement starts with
/// one, so `parse_pre` wraps the hole in `SELECT ...` and strips the wrapper
/// back out (issue #234). The hole has to stand alone on its line apart from
/// the `;`, which is what marks it as a statement slot rather than an operand.
///
/// The separators are placed by the loop, not by the splice: `;` goes *between*
/// the emitted statements and the source's own `;` terminates the last one --
/// the same shape `nix_module.rs.quilt` uses to space a Nix list.
fn seed_script(members: &[(&'static str, u32)]) -> Arc<QTerm> {
    // The closure body is a block with a `let`, not the quote itself: a quote
    // alone as a closure body does not parse today, because Rust's hole is `{}`
    // and `|&(name, age)| {}` reads as an or-pattern. See issue #241.
    let inserts: Vec<Arc<QTerm>> = members
        .iter()
        .map(|&(name, age)| {
            let ins = tb("statement").c(&tb("insert").c(&leaf("keyword_insert", "INSERT")).w(" ").c(&leaf("keyword_into", "INTO")).w(" ").c(&tb("object_reference").c(&leaf("identifier", "members")).b()).w(" ").c(&tb("list").c(&sym("(")).c(&tb("column").c(&leaf("identifier", "name")).b()).c(&sym(",")).w(" ").c(&tb("column").c(&leaf("identifier", "age")).b()).c(&sym(")")).b()).w(" ").c(&leaf("keyword_values", "VALUES")).w(" ").c(&{
                let mut b_ = tb("list");
                sym("(").emit(&mut b_);
                name.qlift_to::<Sql>().emit(&mut b_);
                sym(",").emit(&mut b_);
                b_.write(" ");
                age.qlift_to::<Sql>().emit(&mut b_);
                sym(")").emit(&mut b_);
                b_.b()
            }).b()).b();
            ins
        })
        .collect();
    
    let script = {
        let mut b_ = tb("program");
        tb("statement").c(&tb("create_table").c(&leaf("keyword_create", "CREATE")).w(" ").c(&leaf("keyword_table", "TABLE")).w(" ").c(&tb("object_reference").c(&leaf("identifier", "members")).b()).w(" ").c(&tb("column_definitions").c(&sym("(")).c(&tb("column_definition").c(&leaf("identifier", "id")).w(" ").c(&tb("int").c(&leaf("keyword_int", "INT")).b()).b()).c(&sym(",")).w(" ").c(&tb("column_definition").c(&leaf("identifier", "name")).w(" ").c(&leaf("keyword_text", "TEXT")).b()).c(&sym(",")).w(" ").c(&tb("column_definition").c(&leaf("identifier", "age")).w(" ").c(&tb("int").c(&leaf("keyword_int", "INT")).b()).b()).c(&sym(")")).b()).b()).b().emit(&mut b_);
        sym(";").emit(&mut b_);
        b_.nl();
        {
                for (i, ins) in inserts.into_iter().enumerate() {
                    if i > 0 { sym(";").emit(&mut b_); NL.emit(&mut b_); }
                    ins.emit(&mut b_);
                }
            };
        sym(";").emit(&mut b_);
        b_.nl();
        tb("statement").c(&tb("create_index").c(&leaf("keyword_create", "CREATE")).w(" ").c(&leaf("keyword_index", "INDEX")).w(" ").c(&leaf("identifier", "members_name")).w(" ").c(&leaf("keyword_on", "ON")).w(" ").c(&tb("object_reference").c(&leaf("identifier", "members")).b()).w(" ").c(&tb("index_fields").c(&sym("(")).c(&tb("field").c(&leaf("identifier", "name")).b()).c(&sym(")")).b()).b()).b().emit(&mut b_);
        sym(";").emit(&mut b_);
        b_.b()
    };
    script
}

fn main() -> Result<()> {
    // An ordinary report. Three Rust values of three different types, each
    // crossing into the query as the SQL literal for its own type.
    let q = report(&[
        Filter::Org("acme"),
        Filter::MinAge(21),
        Filter::Active(true),
    ]);
    println!("{};", q.coparse());
    
    // A value containing the delimiter. Standard SQL escapes a quote by
    // doubling it, which is exactly what the lift emits -- and what the
    // grammar's own string rule accepts, so the result reparses to the same
    // text.
    let q = report(&[Filter::Org("Bob's Bakery")]);
    println!("{};", q.coparse());
    
    // The case the whole exercise is for. Pasted into a format!-built query
    // this name ends the literal, closes the statement and comments out the
    // rest; lifted, it is one literal token and the query still has exactly
    // one predicate.
    let q = report(&[Filter::Org("x'; DROP TABLE members; --")]);
    println!("{};", q.coparse());
    
    // A whole script, assembled from a Rust list at generation time. The
    // apostrophe in the last name is escaped by the same lift as above, inside
    // a statement that was spliced rather than written.
    println!();
    println!(
        "{}",
        seed_script(&[("ada", 36), ("grace", 45), ("o'brien", 29)]).coparse()
    );
    
    Ok(())
}
