# DO NOT EDIT. GENERATED BY `quilt expand examples/sql_session.sql.py.quilt`.

#!/usr/bin/env quilt
# A Python program creating and instrumenting a SQL machine with Quilt
# syntax (docs/design/machines.md). The `.sql.py` stem makes Python the
# ground language and SQL the default for bare quote brackets, so every
# fragment fed to the machine is authored as a SQL *term* — inspected,
# composed and spliced as data — and only coparsed at the machine's door.
#
# The machine here is the stdlib sqlite3 connection: a native provider held
# by hand (temp tables are its definitions), until quilt-python grows
# bindings for the Machine trait itself. Values ride the machine's own `?`
# placeholders — never the SQL text — and a Python-side lift into SQL
# literals is the other tracked follow-up.
#
# Run with `quilt run examples/sql_session.sql.py.quilt`
# (needs the quilt_python module: bin/build-py).
from quilt import *
import sqlite3

# Create the machine: a live connection; its tables are its definitions.
db = sqlite3.connect(":memory:")

# Feed it a definition, built as a term.
schema = tb("program").c(tb("statement").c(tb("create_table").c(leaf("keyword_create", "CREATE")).w(" ").c(leaf("keyword_table", "TABLE")).w(" ").c(tb("object_reference").c(leaf("identifier", "menu")).b()).c(tb("column_definitions").c(sym("(")).c(tb("column_definition").c(leaf("identifier", "item")).w(" ").c(leaf("keyword_text", "TEXT")).b()).c(sym(",")).w(" ").c(tb("column_definition").c(leaf("identifier", "price")).w(" ").c(tb("double").c(leaf("keyword_real", "REAL")).b()).b()).c(sym(")")).b()).b()).b()).c(sym(";")).b()
db.execute(schema.coparse())

# Values go through the machine's own placeholders, so the statement is a
# fixed term with literal `?` holes and the data never touches SQL text.
insert = tb("program").c(tb("statement").c(tb("insert").c(leaf("keyword_insert", "INSERT")).w(" ").c(leaf("keyword_into", "INTO")).w(" ").c(tb("object_reference").c(leaf("identifier", "menu")).b()).w(" ").c(leaf("keyword_values", "VALUES")).w(" ").c(tb("list").c(sym("(")).c(leaf("parameter", "?")).c(sym(",")).w(" ").c(leaf("parameter", "?")).c(sym(")")).b()).b()).b()).c(sym(";")).b()
rows = [("espresso", 2.50), ("latte", 3.75), ("O'Malley's blend", 4.20)]
db.executemany(insert.coparse(), rows)

# Instrument it: one predicate term, spliced into two different queries —
# composition as data, not string concatenation.
pricey = tb("binary_expression").c(tb("field").c(leaf("identifier", "price")).b()).w(" ").c(sym(">")).w(" ").c(leaf("literal", "3.0")).b()
count = tb("program").c(tb("statement").c(tb("select").c(leaf("keyword_select", "SELECT")).w(" ").c(tb("select_expression").c(tb("term").c(tb("invocation").c(tb("object_reference").c(leaf("identifier", "COUNT")).b()).c(sym("(")).c(tb("term").c(tb("all_fields").c(sym("*")).b()).b()).c(sym(")")).b()).b()).b()).b()).w(" ").c(tb("from").c(leaf("keyword_from", "FROM")).w(" ").c(tb("relation").c(tb("object_reference").c(leaf("identifier", "menu")).b()).b()).w(" ").c(tb("where").c(leaf("keyword_where", "WHERE")).w(" ").c(pricey).b()).b()).b()).c(sym(";")).b()
names = tb("program").c(tb("statement").c(tb("select").c(leaf("keyword_select", "SELECT")).w(" ").c(tb("select_expression").c(tb("term").c(tb("field").c(leaf("identifier", "item")).b()).b()).b()).b()).w(" ").c(tb("from").c(leaf("keyword_from", "FROM")).w(" ").c(tb("relation").c(tb("object_reference").c(leaf("identifier", "menu")).b()).b()).w(" ").c(tb("where").c(leaf("keyword_where", "WHERE")).w(" ").c(pricey).b()).w(" ").c(tb("order_by").c(leaf("keyword_order", "ORDER")).w(" ").c(leaf("keyword_by", "BY")).w(" ").c(tb("order_target").c(tb("field").c(leaf("identifier", "price")).b()).w(" ").c(tb("direction").c(leaf("keyword_desc", "DESC")).b()).b()).b()).b()).b()).c(sym(";")).b()

(n,) = db.execute(count.coparse()).fetchone()
print("pricey items:", n)
for (item,) in db.execute(names.coparse()):
    print(" -", item)
