//! DO NOT EDIT. GENERATED BY `quilt expand /Users/avarga/Documents/QuiltLang/quilt/examples/times_table.rs.quilt`.

#!/usr/bin/env quilt run
use quilt::prelude::*;

fn main() -> Result<()> {
    let size: i32 = std::env::args()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(5);
    
    // Both loops run at *generation* time.
    // Every product is pre-computed; the output code has no loops, no variables,
    // and no multiply instructions — just baked-in string literals.
    let program = tb("expression_statement").c(&{
        let mut b_ = tb("block");
        sym("{").emit(&mut b_);
        b_.push("    ");
        b_.nl();
        {
            for a in 1..=size {
                for b in 1..=size {
                    let r = a * b;
                    let line = format!("{a:2} x {b:2} = {r:3}");
                    tb("expression_statement").c(&tb("macro_invocation").c(&leaf("identifier", "println")).c(&sym("!")).c(&tb("token_tree").c(&sym("(")).c(&line.qlift()).c(&sym(")")).b()).b()).c(&sym(";")).b().emit(&mut b_);
                    NL.emit(&mut b_);
                }
                tb("expression_statement").c(&tb("macro_invocation").c(&leaf("identifier", "println")).c(&sym("!")).c(&tb("token_tree").c(&sym("(")).c(&sym(")")).b()).b()).c(&sym(";")).b().emit(&mut b_);
                NL.emit(&mut b_);
            }
        };
        b_.pop();
        b_.nl();
        sym("}").emit(&mut b_);
        b_.b()
    }).b();
    
    let total_lines = size * (size + 1);
    println!("=== Generated {total_lines} lines ===\n");
    println!("{}", program.coparse());
    println!("=== Output ===");
    program.reduce()
}
