//! DO NOT EDIT. GENERATED BY `quilt expand examples/upper_tri_square.py.quilt`.

#!/usr/bin/env quilt
from quilt import *

import sys

# Generate a branch-free squaring function for an upper-triangular n x n
# matrix. The matrix is stored flat: just its n*(n+1)/2 entries on and above
# the diagonal, row-major. Because n is known at *generation* time, the loops
# over entries and the inner sums over k unroll completely; the emitted
# function is a single lambda returning the result list, with no loops, no
# branches, and no multiplications by the known zeros below the diagonal.
# (The product of two upper-triangular matrices is upper-triangular, so the
# result uses the same flat layout.)


def idx(n, i, j):
    """Flat index of entry (i, j), i <= j: row i starts after the n, n-1, ...,
    n-i+1 stored entries of the rows above it."""
    return i * n - i * (i - 1) // 2 + (j - i)


# Join QTerms into one splice-able fragment: the variadic-emit pattern, one
# .e() child after another, separated by `sep` text (or newlines by default).
# Unlike HTML fragments, comma-separated Python can't be folded through a
# quote of two holes: a bare tuple quote has no single wrapping node.
def nodes(terms, sep=None):
    b = tb("document")
    for i, t in enumerate(terms):
        if i:
            b = b.n() if sep is None else b.w(sep)
        b = b.e(t)
    return b.b()


def entry(n, i, j):
    """The (i, j) entry of A*A as a quoted sum of products. A[i][k] is nonzero
    only for k >= i and A[k][j] only for k <= j, so k ranges over i..j and the
    zeros below the diagonal are never touched."""
    total = None
    for k in range(i, j + 1):
        # qlift turns the computed index into an integer term. (The postfix
        # lift glyph spells a .qlift() method call, which QTerms have but
        # plain ints don't — ground Python lifts values with the function.)
        prod = tb("binary_operator").c(tb("subscript").c(leaf("identifier", "a")).c(sym("[")).c(qlift(idx(n, i, k))).c(sym("]")).b()).w(" ").c(sym("*")).w(" ").c(tb("subscript").c(leaf("identifier", "a")).c(sym("[")).c(qlift(idx(n, k, j))).c(sym("]")).b()).b()
        total = prod if total is None else tb("binary_operator").c(total).w(" ").c(sym("+")).w(" ").c(prod).b()
    return total


def make_squarer(n):
    """Return a QTerm for a lambda that squares a flat upper-triangular
    matrix, one unrolled sum of products per output entry."""
    entries = nodes((entry(n, i, j) for i in range(n) for j in range(i, n)), sep=", ")
    return tb("lambda").c(sym("lambda")).w(" ").c(tb("lambda_parameters").c(leaf("identifier", "a")).b()).c(sym(":")).w(" ").c(tb("list").c(sym("[")).c(entries).c(sym("]")).b()).b()


n = int(sys.argv[1]) if len(sys.argv) > 1 else 4
fn = make_squarer(n)
print(f"=== Generated upper-triangular squarer for n = {n} ===")
print(fn.coparse())

# Reduce the term back to a live function and check it against a naive
# full-matrix product.
square = fn.reduce()
flat = list(range(1, n * (n + 1) // 2 + 1))
got = square(flat)

full = [[flat[idx(n, i, j)] if j >= i else 0 for j in range(n)] for i in range(n)]
prod = [[sum(full[i][k] * full[k][j] for k in range(n)) for j in range(n)] for i in range(n)]
want = [prod[i][j] for i in range(n) for j in range(i, n)]
print(f"\nmatches naive full-matrix product: {got == want}")
