//! DO NOT EDIT. GENERATED BY `quilt expand examples/zsh_backup.rs.quilt`.

#!/usr/bin/env quilt
//! Generate a zsh backup script from a declarative job table.
//!
//! Zsh is a *target* language in Quilt: it only appears inside zsh quote
//! brackets embedded in a host language (here, Rust). Quilt parses each
//! fragment into a QTerm, the Rust host splices values in, and .coparse()
//! serializes the tree back to a plain zsh script.
//!
//! Computed Rust values cross into the quoted zsh through the lift operator --
//! a postfix written between the unquote brackets. It turns a Rust String into
//! a double-quoted zsh string literal, so the example never builds terms by
//! hand. Everything interesting -- the job table and the loop over it -- runs
//! at *generation* time; the emitted script is a flat, unrolled sequence of
//! commands, one grouped block per job.
use quilt::prelude::*;

fn main() -> Result<()> {
    // The backup jobs, fixed at generation time: (label, source directory).
    let jobs = [
        ("home", "/home/alice"),
        ("etc", "/etc"),
        ("logs", "/var/log"),
    ];
    let dest = "/backups";
    
    // Each job becomes a grouped block of three zsh statements. The Rust `.map`
    // runs now; lifting a value (`↑`) crosses it into the quoted zsh as a
    // string literal.
    let blocks: Vec<Arc<QTerm>> = jobs
        .iter()
        .map(|&(label, src)| {
            let archive = format!("{dest}/{label}.tar.gz");
            let msg = format!("==> backing up {label}");
            tb("compound_statement").c(&sym("{")).p("    ").n().c(&{
                let mut b_ = tb("command");
                tb("command_name").c(&leaf("word", "echo")).b().emit(&mut b_);
                b_.write(" ");
                msg.qlift_to::<Zsh>().emit(&mut b_);
                b_.b()
            }).n().c(&{
                let mut b_ = tb("command");
                tb("command_name").c(&leaf("word", "tar")).b().emit(&mut b_);
                b_.write(" ");
                leaf("word", "-czf").emit(&mut b_);
                b_.write(" ");
                archive.qlift_to::<Zsh>().emit(&mut b_);
                b_.write(" ");
                src.qlift_to::<Zsh>().emit(&mut b_);
                b_.b()
            }).n().c(&{
                let mut b_ = tb("command");
                tb("command_name").c(&leaf("word", "du")).b().emit(&mut b_);
                b_.write(" ");
                leaf("word", "-h").emit(&mut b_);
                b_.write(" ");
                archive.qlift_to::<Zsh>().emit(&mut b_);
                b_.b()
            }).x().n().c(&sym("}")).b()
        })
        .collect();
    
    // Splice the per-job blocks into a script skeleton. The inner Rust block
    // loops at generation time and emits each block, with a separating newline
    // between them. `set -e` aborts on the first failure, so the trailing
    // "complete" line runs only if every job did.
    let script = {
        let mut b_ = tb("program");
        tb("command").c(&tb("command_name").c(&leaf("word", "set")).b()).w(" ").c(&leaf("word", "-e")).b().emit(&mut b_);
        b_.nl();
        {
            let mut b_ = tb("command");
            tb("command_name").c(&leaf("word", "mkdir")).b().emit(&mut b_);
            b_.write(" ");
            leaf("word", "-p").emit(&mut b_);
            b_.write(" ");
            dest.qlift_to::<Zsh>().emit(&mut b_);
            b_.b()
        }.emit(&mut b_);
        b_.nl();
        { for (i, b) in blocks.into_iter().enumerate() { if i > 0 { NL.emit(&mut b_); } b.emit(&mut b_); } };
        b_.nl();
        tb("command").c(&tb("command_name").c(&leaf("word", "echo")).b()).w(" ").c(&tb("string").c(&sym("\"")).c(&leaf("string_content", "all backups complete")).c(&sym("\"")).b()).b().emit(&mut b_);
        b_.b()
    };
    
    println!("{}", script.coparse());
    Ok(())
}
