/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 25
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__char = 1,
  sym__non_escape = 2,
  sym_escape = 3,
  sym_newline = 4,
  sym_left_quote = 5,
  sym_right_quote = 6,
  sym_left_unquote = 7,
  sym_right_unquote = 8,
  sym_lift = 9,
  sym_reduce = 10,
  sym_emit = 11,
  sym_type = 12,
  sym_name = 13,
  sym_plain_line_comment = 14,
  sym_bounded_plain_line_comment = 15,
  sym_plain_block_comment = 16,
  sym__comment = 17,
  sym__bounded_comment = 18,
  sym_source_file = 19,
  sym__node = 20,
  sym__bracketed_node = 21,
  sym_content = 22,
  sym_quote = 23,
  sym_unquote = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_content_repeat1 = 26,
  aux_sym_quote_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__char] = "_char",
  [sym__non_escape] = "_non_escape",
  [sym_escape] = "escape",
  [sym_newline] = "newline",
  [sym_left_quote] = "left_quote",
  [sym_right_quote] = "right_quote",
  [sym_left_unquote] = "left_unquote",
  [sym_right_unquote] = "right_unquote",
  [sym_lift] = "lift",
  [sym_reduce] = "reduce",
  [sym_emit] = "emit",
  [sym_type] = "type",
  [sym_name] = "name",
  [sym_plain_line_comment] = "plain_line_comment",
  [sym_bounded_plain_line_comment] = "plain_line_comment",
  [sym_plain_block_comment] = "plain_block_comment",
  [sym__comment] = "_comment",
  [sym__bounded_comment] = "_bounded_comment",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym__bracketed_node] = "_bracketed_node",
  [sym_content] = "content",
  [sym_quote] = "quote",
  [sym_unquote] = "unquote",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_quote_repeat1] = "quote_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__char] = sym__char,
  [sym__non_escape] = sym__non_escape,
  [sym_escape] = sym_escape,
  [sym_newline] = sym_newline,
  [sym_left_quote] = sym_left_quote,
  [sym_right_quote] = sym_right_quote,
  [sym_left_unquote] = sym_left_unquote,
  [sym_right_unquote] = sym_right_unquote,
  [sym_lift] = sym_lift,
  [sym_reduce] = sym_reduce,
  [sym_emit] = sym_emit,
  [sym_type] = sym_type,
  [sym_name] = sym_name,
  [sym_plain_line_comment] = sym_plain_line_comment,
  [sym_bounded_plain_line_comment] = sym_plain_line_comment,
  [sym_plain_block_comment] = sym_plain_block_comment,
  [sym__comment] = sym__comment,
  [sym__bounded_comment] = sym__bounded_comment,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym__bracketed_node] = sym__bracketed_node,
  [sym_content] = sym_content,
  [sym_quote] = sym_quote,
  [sym_unquote] = sym_unquote,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_quote_repeat1] = aux_sym_quote_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__char] = {
    .visible = false,
    .named = true,
  },
  [sym__non_escape] = {
    .visible = false,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_left_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_right_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_left_unquote] = {
    .visible = true,
    .named = true,
  },
  [sym_right_unquote] = {
    .visible = true,
    .named = true,
  },
  [sym_lift] = {
    .visible = true,
    .named = true,
  },
  [sym_reduce] = {
    .visible = true,
    .named = true,
  },
  [sym_emit] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_bounded_plain_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym__bounded_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym__bracketed_node] = {
    .visible = false,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 8,
  [10] = 3,
  [11] = 4,
  [12] = 7,
  [13] = 13,
  [14] = 14,
  [15] = 14,
  [16] = 13,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 20,
  [22] = 17,
  [23] = 19,
  [24] = 18,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '\n', 42,
        '/', 36,
        '\\', 32,
        0x2190, 51,
        0x2191, 49,
        0x2193, 50,
        0x2196, 45,
        0x2197, 46,
        0x2198, 48,
        0x2199, 47,
        0x27e8, 10,
      );
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != 0x27e8 &&
          lookahead != 0x27e9) ADVANCE(35);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 44,
        '/', 38,
        '\\', 32,
        0x2190, 51,
        0x2191, 49,
        0x2193, 50,
        0x2196, 45,
        0x2197, 46,
        0x2198, 48,
        0x2199, 47,
        0x27e8, 16,
      );
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != 0x27e8 &&
          lookahead != 0x27e9) ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '/') ADVANCE(57);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '/') ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '/') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'N') ADVANCE(23);
      if (lookahead == 'T') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(28);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(30);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(6);
      END_STATE();
    case 14:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == 'N') ADVANCE(23);
      if (lookahead == 'T') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == '/') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == 'N') ADVANCE(23);
      if (lookahead == 'T') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 0x2193) ADVANCE(50);
      if (lookahead == 0x2196) ADVANCE(45);
      if (lookahead == 0x2199) ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == 0x27e8) ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == 0x27e8) ADVANCE(4);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == 0x27e8) ADVANCE(7);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == 0x27e8) ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 22:
      if (lookahead == 0x27e8) ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 23:
      if (lookahead == 0x27e9) ADVANCE(53);
      END_STATE();
    case 24:
      if (lookahead == 0x27e9) ADVANCE(52);
      END_STATE();
    case 25:
      if (lookahead == 0x27e9) ADVANCE(19);
      END_STATE();
    case 26:
      if (lookahead == 0x27e9) ADVANCE(59);
      END_STATE();
    case 27:
      if (lookahead == 0x27e9) ADVANCE(60);
      END_STATE();
    case 28:
      if (lookahead == 0x27e9) ADVANCE(58);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 29:
      if (lookahead == 0x27e9) ADVANCE(62);
      END_STATE();
    case 30:
      if (lookahead == 0x27e9) ADVANCE(61);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 31:
      if (lookahead == 0x27e9) ADVANCE(20);
      END_STATE();
    case 32:
      if (lookahead == 0x2190 ||
          lookahead == 0x2191 ||
          lookahead == 0x2193 ||
          (0x2196 <= lookahead && lookahead <= 0x2199) ||
          lookahead == 0x27e8 ||
          lookahead == 0x27e9) ADVANCE(41);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 33:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '\n', 43,
        '/', 37,
        '\\', 32,
        0x2190, 51,
        0x2191, 49,
        0x2193, 50,
        0x2196, 45,
        0x2199, 47,
        0x27e8, 14,
      );
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < 0x2196 || 0x2199 < lookahead) &&
          lookahead != 0x27e8 &&
          lookahead != 0x27e9) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__char);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(54);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(55);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(56);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == 0x2193) ADVANCE(50);
      if (lookahead == 0x2196) ADVANCE(45);
      if (lookahead == 0x2199) ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__non_escape);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == 0x27e8) ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == 0x27e8) ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == 0x27e8) ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_left_quote);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_right_quote);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_left_unquote);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_right_unquote);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_lift);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_reduce);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_emit);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_type);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_name);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_plain_line_comment);
      if (lookahead == 0x2197 ||
          lookahead == 0x2198) ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_plain_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_bounded_plain_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x2197 &&
          lookahead != 0x2198) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_plain_block_comment);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__comment);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__comment);
      if (lookahead == 0x2197 ||
          lookahead == 0x2198) ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__bounded_comment);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__bounded_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x2197 &&
          lookahead != 0x2198) ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 33},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 33},
  [6] = {.lex_state = 33},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 33},
  [16] = {.lex_state = 33},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 33},
  [22] = {.lex_state = 33},
  [23] = {.lex_state = 33},
  [24] = {.lex_state = 33},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__char] = ACTIONS(1),
    [sym__non_escape] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_left_quote] = ACTIONS(1),
    [sym_right_quote] = ACTIONS(1),
    [sym_left_unquote] = ACTIONS(1),
    [sym_right_unquote] = ACTIONS(1),
    [sym_lift] = ACTIONS(1),
    [sym_reduce] = ACTIONS(1),
    [sym_emit] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_plain_line_comment] = ACTIONS(1),
    [sym_bounded_plain_line_comment] = ACTIONS(1),
    [sym_plain_block_comment] = ACTIONS(1),
    [sym__comment] = ACTIONS(1),
    [sym__bounded_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym__node] = STATE(6),
    [sym_content] = STATE(6),
    [sym_quote] = STATE(6),
    [sym_unquote] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_content_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__char] = ACTIONS(5),
    [sym__non_escape] = ACTIONS(7),
    [sym_escape] = ACTIONS(9),
    [sym_newline] = ACTIONS(11),
    [sym_left_quote] = ACTIONS(13),
    [sym_left_unquote] = ACTIONS(15),
    [sym_lift] = ACTIONS(9),
    [sym_reduce] = ACTIONS(9),
    [sym_emit] = ACTIONS(9),
    [sym_type] = ACTIONS(9),
    [sym_name] = ACTIONS(9),
    [sym_plain_line_comment] = ACTIONS(9),
    [sym_plain_block_comment] = ACTIONS(9),
    [sym__comment] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__bracketed_node] = STATE(2),
    [sym_content] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_content_repeat1] = STATE(13),
    [aux_sym_quote_repeat1] = STATE(2),
    [sym__char] = ACTIONS(17),
    [sym__non_escape] = ACTIONS(20),
    [sym_escape] = ACTIONS(23),
    [sym_newline] = ACTIONS(26),
    [sym_left_quote] = ACTIONS(29),
    [sym_right_quote] = ACTIONS(32),
    [sym_left_unquote] = ACTIONS(34),
    [sym_right_unquote] = ACTIONS(32),
    [sym_lift] = ACTIONS(23),
    [sym_reduce] = ACTIONS(23),
    [sym_emit] = ACTIONS(23),
    [sym_type] = ACTIONS(23),
    [sym_name] = ACTIONS(23),
    [sym_bounded_plain_line_comment] = ACTIONS(23),
    [sym_plain_block_comment] = ACTIONS(23),
    [sym__bounded_comment] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__bracketed_node] = STATE(7),
    [sym_content] = STATE(7),
    [sym_quote] = STATE(7),
    [sym_unquote] = STATE(7),
    [aux_sym_content_repeat1] = STATE(13),
    [aux_sym_quote_repeat1] = STATE(7),
    [sym__char] = ACTIONS(37),
    [sym__non_escape] = ACTIONS(39),
    [sym_escape] = ACTIONS(41),
    [sym_newline] = ACTIONS(43),
    [sym_left_quote] = ACTIONS(45),
    [sym_right_quote] = ACTIONS(47),
    [sym_left_unquote] = ACTIONS(49),
    [sym_lift] = ACTIONS(41),
    [sym_reduce] = ACTIONS(41),
    [sym_emit] = ACTIONS(41),
    [sym_type] = ACTIONS(41),
    [sym_name] = ACTIONS(41),
    [sym_bounded_plain_line_comment] = ACTIONS(41),
    [sym_plain_block_comment] = ACTIONS(41),
    [sym__bounded_comment] = ACTIONS(41),
  },
  [STATE(4)] = {
    [sym__bracketed_node] = STATE(8),
    [sym_content] = STATE(8),
    [sym_quote] = STATE(8),
    [sym_unquote] = STATE(8),
    [aux_sym_content_repeat1] = STATE(13),
    [aux_sym_quote_repeat1] = STATE(8),
    [sym__char] = ACTIONS(37),
    [sym__non_escape] = ACTIONS(39),
    [sym_escape] = ACTIONS(51),
    [sym_newline] = ACTIONS(53),
    [sym_left_quote] = ACTIONS(45),
    [sym_left_unquote] = ACTIONS(49),
    [sym_right_unquote] = ACTIONS(55),
    [sym_lift] = ACTIONS(51),
    [sym_reduce] = ACTIONS(51),
    [sym_emit] = ACTIONS(51),
    [sym_type] = ACTIONS(51),
    [sym_name] = ACTIONS(51),
    [sym_bounded_plain_line_comment] = ACTIONS(51),
    [sym_plain_block_comment] = ACTIONS(51),
    [sym__bounded_comment] = ACTIONS(51),
  },
  [STATE(5)] = {
    [sym__node] = STATE(5),
    [sym_content] = STATE(5),
    [sym_quote] = STATE(5),
    [sym_unquote] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_content_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym__char] = ACTIONS(59),
    [sym__non_escape] = ACTIONS(62),
    [sym_escape] = ACTIONS(65),
    [sym_newline] = ACTIONS(68),
    [sym_left_quote] = ACTIONS(71),
    [sym_left_unquote] = ACTIONS(74),
    [sym_lift] = ACTIONS(65),
    [sym_reduce] = ACTIONS(65),
    [sym_emit] = ACTIONS(65),
    [sym_type] = ACTIONS(65),
    [sym_name] = ACTIONS(65),
    [sym_plain_line_comment] = ACTIONS(65),
    [sym_plain_block_comment] = ACTIONS(65),
    [sym__comment] = ACTIONS(65),
  },
  [STATE(6)] = {
    [sym__node] = STATE(5),
    [sym_content] = STATE(5),
    [sym_quote] = STATE(5),
    [sym_unquote] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_content_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(77),
    [sym__char] = ACTIONS(5),
    [sym__non_escape] = ACTIONS(7),
    [sym_escape] = ACTIONS(79),
    [sym_newline] = ACTIONS(81),
    [sym_left_quote] = ACTIONS(13),
    [sym_left_unquote] = ACTIONS(15),
    [sym_lift] = ACTIONS(79),
    [sym_reduce] = ACTIONS(79),
    [sym_emit] = ACTIONS(79),
    [sym_type] = ACTIONS(79),
    [sym_name] = ACTIONS(79),
    [sym_plain_line_comment] = ACTIONS(79),
    [sym_plain_block_comment] = ACTIONS(79),
    [sym__comment] = ACTIONS(79),
  },
  [STATE(7)] = {
    [sym__bracketed_node] = STATE(2),
    [sym_content] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_content_repeat1] = STATE(13),
    [aux_sym_quote_repeat1] = STATE(2),
    [sym__char] = ACTIONS(37),
    [sym__non_escape] = ACTIONS(39),
    [sym_escape] = ACTIONS(83),
    [sym_newline] = ACTIONS(85),
    [sym_left_quote] = ACTIONS(45),
    [sym_right_quote] = ACTIONS(87),
    [sym_left_unquote] = ACTIONS(49),
    [sym_lift] = ACTIONS(83),
    [sym_reduce] = ACTIONS(83),
    [sym_emit] = ACTIONS(83),
    [sym_type] = ACTIONS(83),
    [sym_name] = ACTIONS(83),
    [sym_bounded_plain_line_comment] = ACTIONS(83),
    [sym_plain_block_comment] = ACTIONS(83),
    [sym__bounded_comment] = ACTIONS(83),
  },
  [STATE(8)] = {
    [sym__bracketed_node] = STATE(2),
    [sym_content] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_content_repeat1] = STATE(13),
    [aux_sym_quote_repeat1] = STATE(2),
    [sym__char] = ACTIONS(37),
    [sym__non_escape] = ACTIONS(39),
    [sym_escape] = ACTIONS(83),
    [sym_newline] = ACTIONS(85),
    [sym_left_quote] = ACTIONS(45),
    [sym_left_unquote] = ACTIONS(49),
    [sym_right_unquote] = ACTIONS(89),
    [sym_lift] = ACTIONS(83),
    [sym_reduce] = ACTIONS(83),
    [sym_emit] = ACTIONS(83),
    [sym_type] = ACTIONS(83),
    [sym_name] = ACTIONS(83),
    [sym_bounded_plain_line_comment] = ACTIONS(83),
    [sym_plain_block_comment] = ACTIONS(83),
    [sym__bounded_comment] = ACTIONS(83),
  },
  [STATE(9)] = {
    [sym__bracketed_node] = STATE(2),
    [sym_content] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_content_repeat1] = STATE(13),
    [aux_sym_quote_repeat1] = STATE(2),
    [sym__char] = ACTIONS(37),
    [sym__non_escape] = ACTIONS(39),
    [sym_escape] = ACTIONS(83),
    [sym_newline] = ACTIONS(85),
    [sym_left_quote] = ACTIONS(45),
    [sym_left_unquote] = ACTIONS(49),
    [sym_right_unquote] = ACTIONS(91),
    [sym_lift] = ACTIONS(83),
    [sym_reduce] = ACTIONS(83),
    [sym_emit] = ACTIONS(83),
    [sym_type] = ACTIONS(83),
    [sym_name] = ACTIONS(83),
    [sym_bounded_plain_line_comment] = ACTIONS(83),
    [sym_plain_block_comment] = ACTIONS(83),
    [sym__bounded_comment] = ACTIONS(83),
  },
  [STATE(10)] = {
    [sym__bracketed_node] = STATE(12),
    [sym_content] = STATE(12),
    [sym_quote] = STATE(12),
    [sym_unquote] = STATE(12),
    [aux_sym_content_repeat1] = STATE(13),
    [aux_sym_quote_repeat1] = STATE(12),
    [sym__char] = ACTIONS(37),
    [sym__non_escape] = ACTIONS(39),
    [sym_escape] = ACTIONS(93),
    [sym_newline] = ACTIONS(95),
    [sym_left_quote] = ACTIONS(45),
    [sym_right_quote] = ACTIONS(97),
    [sym_left_unquote] = ACTIONS(49),
    [sym_lift] = ACTIONS(93),
    [sym_reduce] = ACTIONS(93),
    [sym_emit] = ACTIONS(93),
    [sym_type] = ACTIONS(93),
    [sym_name] = ACTIONS(93),
    [sym_bounded_plain_line_comment] = ACTIONS(93),
    [sym_plain_block_comment] = ACTIONS(93),
    [sym__bounded_comment] = ACTIONS(93),
  },
  [STATE(11)] = {
    [sym__bracketed_node] = STATE(9),
    [sym_content] = STATE(9),
    [sym_quote] = STATE(9),
    [sym_unquote] = STATE(9),
    [aux_sym_content_repeat1] = STATE(13),
    [aux_sym_quote_repeat1] = STATE(9),
    [sym__char] = ACTIONS(37),
    [sym__non_escape] = ACTIONS(39),
    [sym_escape] = ACTIONS(99),
    [sym_newline] = ACTIONS(101),
    [sym_left_quote] = ACTIONS(45),
    [sym_left_unquote] = ACTIONS(49),
    [sym_right_unquote] = ACTIONS(103),
    [sym_lift] = ACTIONS(99),
    [sym_reduce] = ACTIONS(99),
    [sym_emit] = ACTIONS(99),
    [sym_type] = ACTIONS(99),
    [sym_name] = ACTIONS(99),
    [sym_bounded_plain_line_comment] = ACTIONS(99),
    [sym_plain_block_comment] = ACTIONS(99),
    [sym__bounded_comment] = ACTIONS(99),
  },
  [STATE(12)] = {
    [sym__bracketed_node] = STATE(2),
    [sym_content] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_content_repeat1] = STATE(13),
    [aux_sym_quote_repeat1] = STATE(2),
    [sym__char] = ACTIONS(37),
    [sym__non_escape] = ACTIONS(39),
    [sym_escape] = ACTIONS(83),
    [sym_newline] = ACTIONS(85),
    [sym_left_quote] = ACTIONS(45),
    [sym_right_quote] = ACTIONS(105),
    [sym_left_unquote] = ACTIONS(49),
    [sym_lift] = ACTIONS(83),
    [sym_reduce] = ACTIONS(83),
    [sym_emit] = ACTIONS(83),
    [sym_type] = ACTIONS(83),
    [sym_name] = ACTIONS(83),
    [sym_bounded_plain_line_comment] = ACTIONS(83),
    [sym_plain_block_comment] = ACTIONS(83),
    [sym__bounded_comment] = ACTIONS(83),
  },
  [STATE(13)] = {
    [aux_sym_content_repeat1] = STATE(14),
    [sym__char] = ACTIONS(107),
    [sym__non_escape] = ACTIONS(109),
    [sym_escape] = ACTIONS(111),
    [sym_newline] = ACTIONS(113),
    [sym_left_quote] = ACTIONS(111),
    [sym_right_quote] = ACTIONS(111),
    [sym_left_unquote] = ACTIONS(111),
    [sym_right_unquote] = ACTIONS(111),
    [sym_lift] = ACTIONS(111),
    [sym_reduce] = ACTIONS(111),
    [sym_emit] = ACTIONS(111),
    [sym_type] = ACTIONS(111),
    [sym_name] = ACTIONS(111),
    [sym_bounded_plain_line_comment] = ACTIONS(111),
    [sym_plain_block_comment] = ACTIONS(111),
    [sym__bounded_comment] = ACTIONS(111),
  },
  [STATE(14)] = {
    [aux_sym_content_repeat1] = STATE(14),
    [sym__char] = ACTIONS(115),
    [sym__non_escape] = ACTIONS(118),
    [sym_escape] = ACTIONS(121),
    [sym_newline] = ACTIONS(123),
    [sym_left_quote] = ACTIONS(121),
    [sym_right_quote] = ACTIONS(121),
    [sym_left_unquote] = ACTIONS(121),
    [sym_right_unquote] = ACTIONS(121),
    [sym_lift] = ACTIONS(121),
    [sym_reduce] = ACTIONS(121),
    [sym_emit] = ACTIONS(121),
    [sym_type] = ACTIONS(121),
    [sym_name] = ACTIONS(121),
    [sym_bounded_plain_line_comment] = ACTIONS(121),
    [sym_plain_block_comment] = ACTIONS(121),
    [sym__bounded_comment] = ACTIONS(121),
  },
  [STATE(15)] = {
    [aux_sym_content_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(121),
    [sym__char] = ACTIONS(125),
    [sym__non_escape] = ACTIONS(128),
    [sym_escape] = ACTIONS(121),
    [sym_newline] = ACTIONS(123),
    [sym_left_quote] = ACTIONS(121),
    [sym_left_unquote] = ACTIONS(121),
    [sym_lift] = ACTIONS(121),
    [sym_reduce] = ACTIONS(121),
    [sym_emit] = ACTIONS(121),
    [sym_type] = ACTIONS(121),
    [sym_name] = ACTIONS(121),
    [sym_plain_line_comment] = ACTIONS(121),
    [sym_plain_block_comment] = ACTIONS(121),
    [sym__comment] = ACTIONS(121),
  },
  [STATE(16)] = {
    [aux_sym_content_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(111),
    [sym__char] = ACTIONS(131),
    [sym__non_escape] = ACTIONS(133),
    [sym_escape] = ACTIONS(111),
    [sym_newline] = ACTIONS(113),
    [sym_left_quote] = ACTIONS(111),
    [sym_left_unquote] = ACTIONS(111),
    [sym_lift] = ACTIONS(111),
    [sym_reduce] = ACTIONS(111),
    [sym_emit] = ACTIONS(111),
    [sym_type] = ACTIONS(111),
    [sym_name] = ACTIONS(111),
    [sym_plain_line_comment] = ACTIONS(111),
    [sym_plain_block_comment] = ACTIONS(111),
    [sym__comment] = ACTIONS(111),
  },
  [STATE(17)] = {
    [sym__char] = ACTIONS(135),
    [sym__non_escape] = ACTIONS(137),
    [sym_escape] = ACTIONS(137),
    [sym_newline] = ACTIONS(135),
    [sym_left_quote] = ACTIONS(137),
    [sym_right_quote] = ACTIONS(137),
    [sym_left_unquote] = ACTIONS(137),
    [sym_right_unquote] = ACTIONS(137),
    [sym_lift] = ACTIONS(137),
    [sym_reduce] = ACTIONS(137),
    [sym_emit] = ACTIONS(137),
    [sym_type] = ACTIONS(137),
    [sym_name] = ACTIONS(137),
    [sym_bounded_plain_line_comment] = ACTIONS(137),
    [sym_plain_block_comment] = ACTIONS(137),
    [sym__bounded_comment] = ACTIONS(137),
  },
  [STATE(18)] = {
    [sym__char] = ACTIONS(139),
    [sym__non_escape] = ACTIONS(141),
    [sym_escape] = ACTIONS(141),
    [sym_newline] = ACTIONS(139),
    [sym_left_quote] = ACTIONS(141),
    [sym_right_quote] = ACTIONS(141),
    [sym_left_unquote] = ACTIONS(141),
    [sym_right_unquote] = ACTIONS(141),
    [sym_lift] = ACTIONS(141),
    [sym_reduce] = ACTIONS(141),
    [sym_emit] = ACTIONS(141),
    [sym_type] = ACTIONS(141),
    [sym_name] = ACTIONS(141),
    [sym_bounded_plain_line_comment] = ACTIONS(141),
    [sym_plain_block_comment] = ACTIONS(141),
    [sym__bounded_comment] = ACTIONS(141),
  },
  [STATE(19)] = {
    [sym__char] = ACTIONS(143),
    [sym__non_escape] = ACTIONS(145),
    [sym_escape] = ACTIONS(145),
    [sym_newline] = ACTIONS(143),
    [sym_left_quote] = ACTIONS(145),
    [sym_right_quote] = ACTIONS(145),
    [sym_left_unquote] = ACTIONS(145),
    [sym_right_unquote] = ACTIONS(145),
    [sym_lift] = ACTIONS(145),
    [sym_reduce] = ACTIONS(145),
    [sym_emit] = ACTIONS(145),
    [sym_type] = ACTIONS(145),
    [sym_name] = ACTIONS(145),
    [sym_bounded_plain_line_comment] = ACTIONS(145),
    [sym_plain_block_comment] = ACTIONS(145),
    [sym__bounded_comment] = ACTIONS(145),
  },
  [STATE(20)] = {
    [sym__char] = ACTIONS(147),
    [sym__non_escape] = ACTIONS(149),
    [sym_escape] = ACTIONS(149),
    [sym_newline] = ACTIONS(147),
    [sym_left_quote] = ACTIONS(149),
    [sym_right_quote] = ACTIONS(149),
    [sym_left_unquote] = ACTIONS(149),
    [sym_right_unquote] = ACTIONS(149),
    [sym_lift] = ACTIONS(149),
    [sym_reduce] = ACTIONS(149),
    [sym_emit] = ACTIONS(149),
    [sym_type] = ACTIONS(149),
    [sym_name] = ACTIONS(149),
    [sym_bounded_plain_line_comment] = ACTIONS(149),
    [sym_plain_block_comment] = ACTIONS(149),
    [sym__bounded_comment] = ACTIONS(149),
  },
  [STATE(21)] = {
    [ts_builtin_sym_end] = ACTIONS(149),
    [sym__char] = ACTIONS(147),
    [sym__non_escape] = ACTIONS(149),
    [sym_escape] = ACTIONS(149),
    [sym_newline] = ACTIONS(147),
    [sym_left_quote] = ACTIONS(149),
    [sym_left_unquote] = ACTIONS(149),
    [sym_lift] = ACTIONS(149),
    [sym_reduce] = ACTIONS(149),
    [sym_emit] = ACTIONS(149),
    [sym_type] = ACTIONS(149),
    [sym_name] = ACTIONS(149),
    [sym_plain_line_comment] = ACTIONS(149),
    [sym_plain_block_comment] = ACTIONS(149),
    [sym__comment] = ACTIONS(149),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(137),
    [sym__char] = ACTIONS(135),
    [sym__non_escape] = ACTIONS(137),
    [sym_escape] = ACTIONS(137),
    [sym_newline] = ACTIONS(135),
    [sym_left_quote] = ACTIONS(137),
    [sym_left_unquote] = ACTIONS(137),
    [sym_lift] = ACTIONS(137),
    [sym_reduce] = ACTIONS(137),
    [sym_emit] = ACTIONS(137),
    [sym_type] = ACTIONS(137),
    [sym_name] = ACTIONS(137),
    [sym_plain_line_comment] = ACTIONS(137),
    [sym_plain_block_comment] = ACTIONS(137),
    [sym__comment] = ACTIONS(137),
  },
  [STATE(23)] = {
    [ts_builtin_sym_end] = ACTIONS(145),
    [sym__char] = ACTIONS(143),
    [sym__non_escape] = ACTIONS(145),
    [sym_escape] = ACTIONS(145),
    [sym_newline] = ACTIONS(143),
    [sym_left_quote] = ACTIONS(145),
    [sym_left_unquote] = ACTIONS(145),
    [sym_lift] = ACTIONS(145),
    [sym_reduce] = ACTIONS(145),
    [sym_emit] = ACTIONS(145),
    [sym_type] = ACTIONS(145),
    [sym_name] = ACTIONS(145),
    [sym_plain_line_comment] = ACTIONS(145),
    [sym_plain_block_comment] = ACTIONS(145),
    [sym__comment] = ACTIONS(145),
  },
  [STATE(24)] = {
    [ts_builtin_sym_end] = ACTIONS(141),
    [sym__char] = ACTIONS(139),
    [sym__non_escape] = ACTIONS(141),
    [sym_escape] = ACTIONS(141),
    [sym_newline] = ACTIONS(139),
    [sym_left_quote] = ACTIONS(141),
    [sym_left_unquote] = ACTIONS(141),
    [sym_lift] = ACTIONS(141),
    [sym_reduce] = ACTIONS(141),
    [sym_emit] = ACTIONS(141),
    [sym_type] = ACTIONS(141),
    [sym_name] = ACTIONS(141),
    [sym_plain_line_comment] = ACTIONS(141),
    [sym_plain_block_comment] = ACTIONS(141),
    [sym__comment] = ACTIONS(141),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(25)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quote_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quote_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quote_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_quilt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "quilt",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
