/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 15
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__char = 1,
  sym__non_escape = 2,
  sym_escape = 3,
  sym_newline = 4,
  sym_left_quote = 5,
  sym_right_quote = 6,
  sym_left_unquote = 7,
  sym_right_unquote = 8,
  sym_lift = 9,
  sym_reduce = 10,
  sym_emit = 11,
  sym_type = 12,
  sym_name = 13,
  sym_plain_line_comment = 14,
  sym_plain_block_comment = 15,
  sym__comment = 16,
  sym_source_file = 17,
  sym__node = 18,
  sym_content = 19,
  sym_quote = 20,
  sym_unquote = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_content_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__char] = "_char",
  [sym__non_escape] = "_non_escape",
  [sym_escape] = "escape",
  [sym_newline] = "newline",
  [sym_left_quote] = "left_quote",
  [sym_right_quote] = "right_quote",
  [sym_left_unquote] = "left_unquote",
  [sym_right_unquote] = "right_unquote",
  [sym_lift] = "lift",
  [sym_reduce] = "reduce",
  [sym_emit] = "emit",
  [sym_type] = "type",
  [sym_name] = "name",
  [sym_plain_line_comment] = "plain_line_comment",
  [sym_plain_block_comment] = "plain_block_comment",
  [sym__comment] = "_comment",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym_content] = "content",
  [sym_quote] = "quote",
  [sym_unquote] = "unquote",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__char] = sym__char,
  [sym__non_escape] = sym__non_escape,
  [sym_escape] = sym_escape,
  [sym_newline] = sym_newline,
  [sym_left_quote] = sym_left_quote,
  [sym_right_quote] = sym_right_quote,
  [sym_left_unquote] = sym_left_unquote,
  [sym_right_unquote] = sym_right_unquote,
  [sym_lift] = sym_lift,
  [sym_reduce] = sym_reduce,
  [sym_emit] = sym_emit,
  [sym_type] = sym_type,
  [sym_name] = sym_name,
  [sym_plain_line_comment] = sym_plain_line_comment,
  [sym_plain_block_comment] = sym_plain_block_comment,
  [sym__comment] = sym__comment,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym_content] = sym_content,
  [sym_quote] = sym_quote,
  [sym_unquote] = sym_unquote,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__char] = {
    .visible = false,
    .named = true,
  },
  [sym__non_escape] = {
    .visible = false,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_left_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_right_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_left_unquote] = {
    .visible = true,
    .named = true,
  },
  [sym_right_unquote] = {
    .visible = true,
    .named = true,
  },
  [sym_lift] = {
    .visible = true,
    .named = true,
  },
  [sym_reduce] = {
    .visible = true,
    .named = true,
  },
  [sym_emit] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\n', 23,
        '/', 19,
        '\\', 16,
        0x2190, 30,
        0x2191, 28,
        0x2193, 29,
        0x2196, 24,
        0x2197, 25,
        0x2198, 27,
        0x2199, 26,
        0x27e8, 6,
      );
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != 0x27e8 &&
          lookahead != 0x27e9) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(1);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(13);
      if (lookahead == '/') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'N') ADVANCE(11);
      if (lookahead == 'T') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(15);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 0x2193) ADVANCE(29);
      if (lookahead == 0x2196) ADVANCE(24);
      if (lookahead == 0x2199) ADVANCE(26);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == 0x27e8) ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == 0x27e8) ADVANCE(3);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == 0x27e9) ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 0x27e9) ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == 0x27e9) ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 0x27e9) ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 0x27e9) ADVANCE(35);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 0x2191 ||
          lookahead == 0x2193 ||
          (0x2196 <= lookahead && lookahead <= 0x2199) ||
          lookahead == 0x27e8 ||
          lookahead == 0x27e9) ADVANCE(22);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__char);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '/') ADVANCE(33);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == 0x2193) ADVANCE(29);
      if (lookahead == 0x2196) ADVANCE(24);
      if (lookahead == 0x2199) ADVANCE(26);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__non_escape);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == 0x27e8) ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_left_quote);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_right_quote);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_left_unquote);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_right_unquote);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_lift);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_reduce);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_emit);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_type);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_name);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_plain_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_plain_block_comment);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__comment);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__char] = ACTIONS(1),
    [sym__non_escape] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_left_quote] = ACTIONS(1),
    [sym_right_quote] = ACTIONS(1),
    [sym_left_unquote] = ACTIONS(1),
    [sym_right_unquote] = ACTIONS(1),
    [sym_lift] = ACTIONS(1),
    [sym_reduce] = ACTIONS(1),
    [sym_emit] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_plain_line_comment] = ACTIONS(1),
    [sym_plain_block_comment] = ACTIONS(1),
    [sym__comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(14),
    [sym__node] = STATE(5),
    [sym_content] = STATE(5),
    [sym_quote] = STATE(5),
    [sym_unquote] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_content_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__char] = ACTIONS(5),
    [sym__non_escape] = ACTIONS(7),
    [sym_escape] = ACTIONS(9),
    [sym_newline] = ACTIONS(11),
    [sym_left_quote] = ACTIONS(13),
    [sym_left_unquote] = ACTIONS(15),
    [sym_lift] = ACTIONS(9),
    [sym_reduce] = ACTIONS(9),
    [sym_emit] = ACTIONS(9),
    [sym_type] = ACTIONS(9),
    [sym_name] = ACTIONS(9),
    [sym_plain_line_comment] = ACTIONS(9),
    [sym_plain_block_comment] = ACTIONS(9),
    [sym__comment] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__node] = STATE(2),
    [sym_content] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym__char] = ACTIONS(19),
    [sym__non_escape] = ACTIONS(22),
    [sym_escape] = ACTIONS(25),
    [sym_newline] = ACTIONS(28),
    [sym_left_quote] = ACTIONS(31),
    [sym_right_quote] = ACTIONS(17),
    [sym_left_unquote] = ACTIONS(34),
    [sym_right_unquote] = ACTIONS(17),
    [sym_lift] = ACTIONS(25),
    [sym_reduce] = ACTIONS(25),
    [sym_emit] = ACTIONS(25),
    [sym_type] = ACTIONS(25),
    [sym_name] = ACTIONS(25),
    [sym_plain_line_comment] = ACTIONS(25),
    [sym_plain_block_comment] = ACTIONS(25),
    [sym__comment] = ACTIONS(25),
  },
  [STATE(3)] = {
    [sym__node] = STATE(6),
    [sym_content] = STATE(6),
    [sym_quote] = STATE(6),
    [sym_unquote] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_content_repeat1] = STATE(8),
    [sym__char] = ACTIONS(5),
    [sym__non_escape] = ACTIONS(7),
    [sym_escape] = ACTIONS(37),
    [sym_newline] = ACTIONS(39),
    [sym_left_quote] = ACTIONS(13),
    [sym_right_quote] = ACTIONS(41),
    [sym_left_unquote] = ACTIONS(15),
    [sym_lift] = ACTIONS(37),
    [sym_reduce] = ACTIONS(37),
    [sym_emit] = ACTIONS(37),
    [sym_type] = ACTIONS(37),
    [sym_name] = ACTIONS(37),
    [sym_plain_line_comment] = ACTIONS(37),
    [sym_plain_block_comment] = ACTIONS(37),
    [sym__comment] = ACTIONS(37),
  },
  [STATE(4)] = {
    [sym__node] = STATE(7),
    [sym_content] = STATE(7),
    [sym_quote] = STATE(7),
    [sym_unquote] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_content_repeat1] = STATE(8),
    [sym__char] = ACTIONS(5),
    [sym__non_escape] = ACTIONS(7),
    [sym_escape] = ACTIONS(43),
    [sym_newline] = ACTIONS(45),
    [sym_left_quote] = ACTIONS(13),
    [sym_left_unquote] = ACTIONS(15),
    [sym_right_unquote] = ACTIONS(47),
    [sym_lift] = ACTIONS(43),
    [sym_reduce] = ACTIONS(43),
    [sym_emit] = ACTIONS(43),
    [sym_type] = ACTIONS(43),
    [sym_name] = ACTIONS(43),
    [sym_plain_line_comment] = ACTIONS(43),
    [sym_plain_block_comment] = ACTIONS(43),
    [sym__comment] = ACTIONS(43),
  },
  [STATE(5)] = {
    [sym__node] = STATE(2),
    [sym_content] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym__char] = ACTIONS(5),
    [sym__non_escape] = ACTIONS(7),
    [sym_escape] = ACTIONS(51),
    [sym_newline] = ACTIONS(53),
    [sym_left_quote] = ACTIONS(13),
    [sym_left_unquote] = ACTIONS(15),
    [sym_lift] = ACTIONS(51),
    [sym_reduce] = ACTIONS(51),
    [sym_emit] = ACTIONS(51),
    [sym_type] = ACTIONS(51),
    [sym_name] = ACTIONS(51),
    [sym_plain_line_comment] = ACTIONS(51),
    [sym_plain_block_comment] = ACTIONS(51),
    [sym__comment] = ACTIONS(51),
  },
  [STATE(6)] = {
    [sym__node] = STATE(2),
    [sym_content] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(8),
    [sym__char] = ACTIONS(5),
    [sym__non_escape] = ACTIONS(7),
    [sym_escape] = ACTIONS(51),
    [sym_newline] = ACTIONS(53),
    [sym_left_quote] = ACTIONS(13),
    [sym_right_quote] = ACTIONS(55),
    [sym_left_unquote] = ACTIONS(15),
    [sym_lift] = ACTIONS(51),
    [sym_reduce] = ACTIONS(51),
    [sym_emit] = ACTIONS(51),
    [sym_type] = ACTIONS(51),
    [sym_name] = ACTIONS(51),
    [sym_plain_line_comment] = ACTIONS(51),
    [sym_plain_block_comment] = ACTIONS(51),
    [sym__comment] = ACTIONS(51),
  },
  [STATE(7)] = {
    [sym__node] = STATE(2),
    [sym_content] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(8),
    [sym__char] = ACTIONS(5),
    [sym__non_escape] = ACTIONS(7),
    [sym_escape] = ACTIONS(51),
    [sym_newline] = ACTIONS(53),
    [sym_left_quote] = ACTIONS(13),
    [sym_left_unquote] = ACTIONS(15),
    [sym_right_unquote] = ACTIONS(57),
    [sym_lift] = ACTIONS(51),
    [sym_reduce] = ACTIONS(51),
    [sym_emit] = ACTIONS(51),
    [sym_type] = ACTIONS(51),
    [sym_name] = ACTIONS(51),
    [sym_plain_line_comment] = ACTIONS(51),
    [sym_plain_block_comment] = ACTIONS(51),
    [sym__comment] = ACTIONS(51),
  },
  [STATE(8)] = {
    [aux_sym_content_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym__char] = ACTIONS(61),
    [sym__non_escape] = ACTIONS(63),
    [sym_escape] = ACTIONS(59),
    [sym_newline] = ACTIONS(65),
    [sym_left_quote] = ACTIONS(59),
    [sym_right_quote] = ACTIONS(59),
    [sym_left_unquote] = ACTIONS(59),
    [sym_right_unquote] = ACTIONS(59),
    [sym_lift] = ACTIONS(59),
    [sym_reduce] = ACTIONS(59),
    [sym_emit] = ACTIONS(59),
    [sym_type] = ACTIONS(59),
    [sym_name] = ACTIONS(59),
    [sym_plain_line_comment] = ACTIONS(59),
    [sym_plain_block_comment] = ACTIONS(59),
    [sym__comment] = ACTIONS(59),
  },
  [STATE(9)] = {
    [aux_sym_content_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(67),
    [sym__char] = ACTIONS(69),
    [sym__non_escape] = ACTIONS(72),
    [sym_escape] = ACTIONS(67),
    [sym_newline] = ACTIONS(75),
    [sym_left_quote] = ACTIONS(67),
    [sym_right_quote] = ACTIONS(67),
    [sym_left_unquote] = ACTIONS(67),
    [sym_right_unquote] = ACTIONS(67),
    [sym_lift] = ACTIONS(67),
    [sym_reduce] = ACTIONS(67),
    [sym_emit] = ACTIONS(67),
    [sym_type] = ACTIONS(67),
    [sym_name] = ACTIONS(67),
    [sym_plain_line_comment] = ACTIONS(67),
    [sym_plain_block_comment] = ACTIONS(67),
    [sym__comment] = ACTIONS(67),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [sym__char] = ACTIONS(79),
    [sym__non_escape] = ACTIONS(77),
    [sym_escape] = ACTIONS(77),
    [sym_newline] = ACTIONS(79),
    [sym_left_quote] = ACTIONS(77),
    [sym_right_quote] = ACTIONS(77),
    [sym_left_unquote] = ACTIONS(77),
    [sym_right_unquote] = ACTIONS(77),
    [sym_lift] = ACTIONS(77),
    [sym_reduce] = ACTIONS(77),
    [sym_emit] = ACTIONS(77),
    [sym_type] = ACTIONS(77),
    [sym_name] = ACTIONS(77),
    [sym_plain_line_comment] = ACTIONS(77),
    [sym_plain_block_comment] = ACTIONS(77),
    [sym__comment] = ACTIONS(77),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym__char] = ACTIONS(83),
    [sym__non_escape] = ACTIONS(81),
    [sym_escape] = ACTIONS(81),
    [sym_newline] = ACTIONS(83),
    [sym_left_quote] = ACTIONS(81),
    [sym_right_quote] = ACTIONS(81),
    [sym_left_unquote] = ACTIONS(81),
    [sym_right_unquote] = ACTIONS(81),
    [sym_lift] = ACTIONS(81),
    [sym_reduce] = ACTIONS(81),
    [sym_emit] = ACTIONS(81),
    [sym_type] = ACTIONS(81),
    [sym_name] = ACTIONS(81),
    [sym_plain_line_comment] = ACTIONS(81),
    [sym_plain_block_comment] = ACTIONS(81),
    [sym__comment] = ACTIONS(81),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym__char] = ACTIONS(87),
    [sym__non_escape] = ACTIONS(85),
    [sym_escape] = ACTIONS(85),
    [sym_newline] = ACTIONS(87),
    [sym_left_quote] = ACTIONS(85),
    [sym_right_quote] = ACTIONS(85),
    [sym_left_unquote] = ACTIONS(85),
    [sym_right_unquote] = ACTIONS(85),
    [sym_lift] = ACTIONS(85),
    [sym_reduce] = ACTIONS(85),
    [sym_emit] = ACTIONS(85),
    [sym_type] = ACTIONS(85),
    [sym_name] = ACTIONS(85),
    [sym_plain_line_comment] = ACTIONS(85),
    [sym_plain_block_comment] = ACTIONS(85),
    [sym__comment] = ACTIONS(85),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [sym__char] = ACTIONS(91),
    [sym__non_escape] = ACTIONS(89),
    [sym_escape] = ACTIONS(89),
    [sym_newline] = ACTIONS(91),
    [sym_left_quote] = ACTIONS(89),
    [sym_right_quote] = ACTIONS(89),
    [sym_left_unquote] = ACTIONS(89),
    [sym_right_unquote] = ACTIONS(89),
    [sym_lift] = ACTIONS(89),
    [sym_reduce] = ACTIONS(89),
    [sym_emit] = ACTIONS(89),
    [sym_type] = ACTIONS(89),
    [sym_name] = ACTIONS(89),
    [sym_plain_line_comment] = ACTIONS(89),
    [sym_plain_block_comment] = ACTIONS(89),
    [sym__comment] = ACTIONS(89),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_quilt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "quilt",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
