pub mod arity;
#[cfg(feature = "bash")]
pub mod bash;
#[cfg(feature = "bootstrap")]
pub mod bootstrap;
#[cfg(feature = "html")]
pub mod html;
#[cfg(feature = "lean")]
pub mod lean;
#[cfg(feature = "nix")]
pub mod nix;
#[cfg(feature = "parse")]
pub mod omni;
#[cfg(feature = "python")]
pub mod python;
#[cfg(any(feature = "rust", feature = "bootstrap"))]
pub mod rust;
#[cfg(any(feature = "bash", feature = "zsh"))]
pub mod shell;
#[cfg(feature = "sql")]
pub mod sql;
#[cfg(feature = "text")]
pub mod text;
#[cfg(feature = "typescript")]
pub mod typescript;
#[cfg(feature = "wgsl")]
pub mod wgsl;
#[cfg(feature = "zsh")]
pub mod zsh;

/// How each language spells comments, keyed by canonical name or alias.
///
/// Both are generated by `define_omni!` from the registry table, and each
/// language's answer is the [`Comments`](crate::lang::Comments) impl beside its
/// `Language` impl — there is no second table to keep in agreement with the
/// first. See [`Comments`](crate::lang::Comments) for why the fact lives there
/// and not on `Language` itself (issues #136, #194).
#[cfg(feature = "parse")]
pub use omni::{header_comment, line_comment};
