//! `Multi`s containing all languages enabled by Rust features.
//!
//! All the per-language boilerplate is generated by [`define_omni!`]; adding a
//! language means adding one line to the `languages` section of the invocation
//! at the bottom of this file (plus a `metas` line if it can act as a host).

#[cfg(feature = "bash")]
use super::bash::lang::{BashLanguage, DynBashLanguage};
#[cfg(feature = "html")]
use super::html::lang::{DynHtmlLanguage, HtmlLanguage};
#[cfg(feature = "python")]
use super::python::{
    lang::{DynPythonLanguage, PythonLanguage},
    meta::PythonMetaLanguage,
};
#[cfg(feature = "rust")]
use super::rust::{
    lang::{DynRustLanguage, RustLanguage},
    meta::RustMetaLanguage,
};
#[cfg(feature = "text")]
use super::text::lang::{DynTextLanguage, TextLanguage};
#[cfg(feature = "wgsl")]
use super::wgsl::lang::{DynWgslLanguage, WgslLanguage};
#[cfg(feature = "zsh")]
use super::zsh::lang::{DynZshLanguage, ZshLanguage};
use crate::lang::{Arity, FlatNode, Hole, InnerKind, Language, LanguagePost};
use crate::meta::{MetaLanguage, OuterKind};
use crate::multi::{DictMulti, Languages, MetaLanguages, Multi};
use crate::prelude::*;
use crate::qterm::QTerm;
use crate::term::CmdOrHole;
use miette::miette;

/**************************************************************/

/// Generates the entire Omni language surface from one table:
/// `OmniLanguages`/`OmniMetaLanguages` (the registries), `OmniLanguage`/
/// `OmniLanguagePost`/`OmniMetaLanguage` (the enum-dispatch wrappers), the
/// `DynOmni*` registries, and [`dict_omni_language`].
///
/// Each `languages` entry reads:
///
/// ```text
/// field if "feature" => Variant(LanguageTy, DynLanguageTy): ["canonical", "alias", ...];
/// ```
///
/// The `metas` section lists the subset of languages that can act as hosts
/// (drive expansion); languages absent from it are target-only.
macro_rules! define_omni {
    (
        languages {
            $( $field:ident if $feat:literal => $variant:ident($lang:ty, $dyn_lang:ty):
                [$canon:literal $(, $alias:literal)* $(,)?] );* $(;)?
        }
        metas {
            $( $mfield:ident if $mfeat:literal => $mvariant:ident($meta:ty):
                [$mcanon:literal $(, $malias:literal)* $(,)?] );* $(;)?
        }
    ) => {
        /// An "Omni"-language using enums.
        pub struct OmniLanguages {
            $(
                #[cfg(feature = $feat)]
                $field: OmniLanguage,
            )*
        }

        impl Default for OmniLanguages {
            #[allow(clippy::default_constructed_unit_structs)]
            fn default() -> Self {
                Self {
                    $(
                        #[cfg(feature = $feat)]
                        $field: OmniLanguage::$variant(<$lang>::default()),
                    )*
                }
            }
        }

        impl Languages for OmniLanguages {
            type Language = OmniLanguage;

            fn get(&self, lang: &str) -> Result<&Self::Language> {
                match lang {
                    $(
                        #[cfg(feature = $feat)]
                        $canon $(| $alias)* => Ok(&self.$field),
                    )*
                    _ => Err(miette!("{lang:?} can't be used as Language")),
                }
            }
            fn get_mut(&mut self, lang: &str) -> Result<&mut Self::Language> {
                match lang {
                    $(
                        #[cfg(feature = $feat)]
                        $canon $(| $alias)* => Ok(&mut self.$field),
                    )*
                    _ => Err(miette!("{lang:?} can't be used as Language")),
                }
            }
        }

        pub struct OmniMetaLanguages {
            $(
                #[cfg(feature = $mfeat)]
                $mfield: OmniMetaLanguage,
            )*
        }

        impl Default for OmniMetaLanguages {
            #[allow(clippy::default_constructed_unit_structs)]
            fn default() -> Self {
                Self {
                    $(
                        #[cfg(feature = $mfeat)]
                        $mfield: OmniMetaLanguage::$mvariant(<$meta>::default()),
                    )*
                }
            }
        }

        impl MetaLanguages for OmniMetaLanguages {
            type MetaLanguage = OmniMetaLanguage;

            fn get(&self, lang: &str) -> Result<&Self::MetaLanguage> {
                match lang {
                    $(
                        #[cfg(feature = $mfeat)]
                        $mcanon $(| $malias)* => Ok(&self.$mfield),
                    )*
                    _ => Err(miette!("{lang:?} can't be used as MetaLanguage")),
                }
            }
            fn get_mut(&mut self, lang: &str) -> Result<&mut Self::MetaLanguage> {
                match lang {
                    $(
                        #[cfg(feature = $mfeat)]
                        $mcanon $(| $malias)* => Ok(&mut self.$mfield),
                    )*
                    _ => Err(miette!("{lang:?} can't be used as MetaLanguage")),
                }
            }
        }

        /// A `Language` used by `Omni`.
        pub enum OmniLanguage {
            $(
                #[cfg(feature = $feat)]
                $variant($lang),
            )*
        }

        impl Language for OmniLanguage {
            type Post = OmniLanguagePost;

            #[allow(unused_variables)]
            fn parse_pre(
                &mut self,
                ikind: Option<InnerKind>,
                code: &[FlatNode],
            ) -> Result<Self::Post> {
                match self {
                    $(
                        #[cfg(feature = $feat)]
                        OmniLanguage::$variant(lang) => {
                            lang.parse_pre(ikind, code).map(OmniLanguagePost::$variant)
                        }
                    )*
                    #[allow(unreachable_patterns)]
                    _ => unreachable!(),
                }
            }

            fn hashbang(&self) -> Option<&'static str> {
                match self {
                    $(
                        #[cfg(feature = $feat)]
                        OmniLanguage::$variant(lang) => lang.hashbang(),
                    )*
                    #[allow(unreachable_patterns)]
                    _ => None,
                }
            }

            #[allow(unused_variables)]
            fn arity(&self, tag: &str) -> Arity {
                match self {
                    $(
                        #[cfg(feature = $feat)]
                        OmniLanguage::$variant(lang) => lang.arity(tag),
                    )*
                    #[allow(unreachable_patterns)]
                    _ => Default::default(),
                }
            }

            #[allow(unused_variables)]
            fn typ(&self, tag: &str) -> InnerKind {
                match self {
                    $(
                        #[cfg(feature = $feat)]
                        OmniLanguage::$variant(lang) => lang.typ(tag),
                    )*
                    #[allow(unreachable_patterns)]
                    _ => Default::default(),
                }
            }
        }

        /// A `LanguagePost` used by `Omni`.
        #[derive(Debug)]
        pub enum OmniLanguagePost {
            $(
                #[cfg(feature = $feat)]
                $variant(<$lang as Language>::Post),
            )*
        }

        impl LanguagePost for OmniLanguagePost {
            fn holes(&self) -> &[Hole] {
                match self {
                    $(
                        #[cfg(feature = $feat)]
                        OmniLanguagePost::$variant(post) => post.holes(),
                    )*
                    #[allow(unreachable_patterns)]
                    _ => unreachable!(),
                }
            }

            #[allow(unused_variables)]
            fn parse_post(&self, plugs: &[Arc<QTerm>]) -> Result<Arc<QTerm>> {
                match self {
                    $(
                        #[cfg(feature = $feat)]
                        OmniLanguagePost::$variant(post) => post.parse_post(plugs),
                    )*
                    #[allow(unreachable_patterns)]
                    _ => unreachable!(),
                }
            }
        }

        /// A `MetaLanguage` used by `Omni`.
        pub enum OmniMetaLanguage {
            $(
                #[cfg(feature = $mfeat)]
                $mvariant($meta),
            )*
        }

        impl OmniMetaLanguage {
            fn inner(&self) -> &dyn MetaLanguage {
                match self {
                    $(
                        #[cfg(feature = $mfeat)]
                        OmniMetaLanguage::$mvariant(lang) => lang,
                    )*
                    #[allow(unreachable_patterns)]
                    _ => unreachable!(),
                }
            }
        }

        /// A `MultiLanguage` using `Box<dyn>`s.
        #[derive(Default)]
        pub struct DynOmniLanguages {
            $(
                #[cfg(feature = $feat)]
                $field: $dyn_lang,
            )*
        }

        impl Languages for DynOmniLanguages {
            type Language = dyn Language<Post = Box<dyn LanguagePost>>;

            fn get(&self, lang: &str) -> Result<&Self::Language> {
                match lang {
                    $(
                        #[cfg(feature = $feat)]
                        $canon $(| $alias)* => Ok(&self.$field),
                    )*
                    _ => Err(miette!("{lang:?} can't be used as Language")),
                }
            }
            fn get_mut(&mut self, lang: &str) -> Result<&mut Self::Language> {
                match lang {
                    $(
                        #[cfg(feature = $feat)]
                        $canon $(| $alias)* => Ok(&mut self.$field),
                    )*
                    _ => Err(miette!("{lang:?} can't be used as Language")),
                }
            }
        }

        /// A `MultiLanguage` using `Box<dyn>`s.
        #[derive(Default)]
        pub struct DynOmniMetaLanguages {
            $(
                #[cfg(feature = $mfeat)]
                $mfield: $meta,
            )*
        }

        impl MetaLanguages for DynOmniMetaLanguages {
            type MetaLanguage = dyn MetaLanguage;

            fn get(&self, lang: &str) -> Result<&Self::MetaLanguage> {
                match lang {
                    $(
                        #[cfg(feature = $mfeat)]
                        $mcanon $(| $malias)* => Ok(&self.$mfield),
                    )*
                    _ => Err(miette!("{lang:?} can't be used as MetaLanguage")),
                }
            }

            fn get_mut(&mut self, lang: &str) -> Result<&mut Self::MetaLanguage> {
                match lang {
                    $(
                        #[cfg(feature = $mfeat)]
                        $mcanon $(| $malias)* => Ok(&mut self.$mfield),
                    )*
                    _ => Err(miette!("{lang:?} can't be used as MetaLanguage")),
                }
            }
        }

        /// A `DictMulti` over all enabled languages. Each language is
        /// registered once under its canonical name; aliases resolve to that
        /// single instance through the alias registry.
        #[allow(clippy::default_constructed_unit_structs)]
        pub fn dict_omni_language() -> DictMulti {
            #[allow(unused_mut)]
            let mut ret = DictMulti::default();
            $(
                #[cfg(feature = $feat)]
                {
                    ret.add_lang($canon, bx(<$dyn_lang>::default()));
                    $( ret.add_alias($alias, $canon); )*
                }
            )*
            $(
                #[cfg(feature = $mfeat)]
                {
                    ret.add_meta($mcanon, bx(<$meta>::default()));
                    $( ret.add_alias($malias, $mcanon); )*
                }
            )*
            ret
        }
    };
}

impl MetaLanguage for OmniMetaLanguage {
    fn expand_quote(
        &self,
        lang1: &str,
        tag: &str,
        i: Index,
        lang2: &str,
        qterm: &Arc<QTerm>,
        cmds: &[CmdOrHole],
    ) -> Result<Arc<QTerm>> {
        self.inner().expand_quote(lang1, tag, i, lang2, qterm, cmds)
    }

    fn expand_unquote(
        &self,
        lang1: &str,
        tag: &str,
        i: Index,
        lang2: &str,
        qterm: &Arc<QTerm>,
        cmds: &[CmdOrHole],
    ) -> Result<Arc<QTerm>> {
        self.inner()
            .expand_unquote(lang1, tag, i, lang2, qterm, cmds)
    }

    fn expand_tuple(
        &self,
        lang1: &str,
        tag: &str,
        qterms: &[Arc<QTerm>],
        cmds: &[CmdOrHole],
        arity: Arity,
    ) -> Result<Arc<QTerm>> {
        self.inner().expand_tuple(lang1, tag, qterms, cmds, arity)
    }

    fn wrap_child(&self, qterm: Arc<QTerm>, okind: OuterKind) -> Result<Arc<QTerm>> {
        self.inner().wrap_child(qterm, okind)
    }

    fn lift_str(&self, target: &str) -> Result<&'static str> {
        self.inner().lift_str(target)
    }

    fn reduce_str(&self) -> &'static str {
        self.inner().reduce_str()
    }

    fn emit_str(&self) -> &'static str {
        self.inner().emit_str()
    }

    fn type_str(&self) -> &'static str {
        self.inner().type_str()
    }

    fn name_str(&self) -> &'static str {
        self.inner().name_str()
    }
}

pub type Omni = Multi<OmniLanguages, OmniMetaLanguages>;

#[cfg(test)]
mod tests {
    use super::*;

    /// Aliases resolve through the registry to the canonical entry instead of
    /// owning a second instance.
    #[test]
    fn dict_aliases_resolve() {
        let dict = dict_omni_language();
        #[cfg(feature = "python")]
        {
            assert!(dict.get_lang("python").is_ok());
            assert!(dict.get_lang("py").is_ok());
            assert!(dict.get_meta("py").is_ok());
        }
        #[cfg(feature = "rust")]
        {
            assert!(dict.get_lang("rs").is_ok());
            assert!(dict.get_meta("rs").is_ok());
        }
        #[cfg(feature = "text")]
        {
            assert!(dict.get_lang("txt").is_ok());
            // text is target-only: the alias exists but has no meta entry
            assert!(dict.get_meta("txt").is_err());
        }
        assert!(dict.get_lang("nope").is_err());
    }
}

// Languages absent from `metas` (text, wgsl, html, zsh, bash) are target
// languages only — the host's MetaLanguage drives expansion.
define_omni! {
    languages {
        bash if "bash"   => Bash(BashLanguage, DynBashLanguage):       ["bash"];
        html if "html"   => Html(HtmlLanguage, DynHtmlLanguage):       ["html"];
        py   if "python" => Python(PythonLanguage, DynPythonLanguage): ["python", "py"];
        rs   if "rust"   => Rust(RustLanguage, DynRustLanguage):       ["rust", "rs"];
        txt  if "text"   => Text(TextLanguage, DynTextLanguage):       ["text", "txt"];
        wgsl if "wgsl"   => Wgsl(WgslLanguage, DynWgslLanguage):       ["wgsl"];
        zsh  if "zsh"    => Zsh(ZshLanguage, DynZshLanguage):          ["zsh"];
    }
    metas {
        py   if "python" => Python(PythonMetaLanguage):                ["python", "py"];
        rs   if "rust"   => Rust(RustMetaLanguage):                    ["rust", "rs"];
    }
}
